### ISSUE TITLE
Green ticks in store not working as expected

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1000]
## Description

The implementation of green ticks were to show a green tick on items that have been already bought and is set on the avatar. 
Currently, there are several errors on the implementation that needs to be handled like ticks not appearing for the items that are set on avatar, ticks appearing on multiple items, ticks appearing on items that are not selected

## Mocks
No ticks:
![no ticks](https://user-images.githubusercontent.com/26908195/36190078-18cdf200-117c-11e8-94b2-5455c869a1bd.png)

![no tick](https://user-images.githubusercontent.com/26908195/36190092-2b5fa562-117c-11e8-9fdb-da8d915c3ef6.png)

Tick on wrong store item:
![wrong tick](https://user-images.githubusercontent.com/26908195/36190087-2459b456-117c-11e8-9cc1-5d57abb50367.png)

Appearance of multiple ticks:
![mutiple ticks](https://user-images.githubusercontent.com/26908195/36190097-37ddd03e-117c-11e8-9408-dd525cc15422.png)

### Update
- [ ] Rectification to methods in StoreActivity.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**I would like to work on the issue**

**Comment by tanvidadu** [comment]
@Rimjhim28 can debanjanah take this issue as a part of her outreachy task ?

**Comment by Rimjhim28** [comment]
@tanvidadu The issue is not approved yet by any of the maintainer so I did not send a PR. 
This basically arose in the way of resolving conflicts and merging GCI PRs. I have actually resolved the issue locally on my machine. Once the issue is approved I will send the PR. :)

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by niksj** [comment]
@Rimjhim28 Issue approved. You can work on it.

**Comment by Rimjhim28** [comment]
@niksj Thanks a lot!! Will send a PR soon. :)
