### ISSUE TITLE
Handling of mini games if already played scenario is chosen

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1001]
## Description

If a minigame is left in middle and some other scenario is clicked, the user is first forced to complete the mini game.
Though this may seem a good option if a mini game is left in middle and next scenario in the queue is chosen, it may not be good enough if a previous/ already played scenario is chosen.

## Mocks

![videotogif_2018 02 14_12 13 35](https://user-images.githubusercontent.com/26908195/36191246-3ac167b0-1182-11e8-86cc-384ca30285df.gif)

### Update
- [ ] Rectification of newly created Session Managers
- [ ] Identification of previous and next scenarios in Session Managers

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours 

**I would like to work on this**

**Comment by MeepyMay** [comment]
I think this is a duplicate issue.

**Comment by Rimjhim28** [comment]
@MeepyMay Could you please specify the issue number.
This issue was mainly encourtered by me after merging the creation of mini games session managers into the code.

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by debanjanah** [comment]
can be solved by solving #777
