### ISSUE TITLE
Redundant query calls to database

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#1004]
## Description
As a developer ,I need query operations from database only when needed,
So that no redundant query operations( inside AvatarRoomActivity.java) are executed.
But line no 72 , 84, 94 , 104(develop branch) have repeated query operation.

## Example
Line 67 : eye= *getmDbHandler().getAvatarEye()* ;
Line 72 : eyeImageName = eyeImageName + *getmDbHandler().getAvatarEye()* ;
 
## Acceptance Criteria
- [ ] Removing redundant database operation( AvatarRoomActivity.java )

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by geekanamika** [comment]
@Rimjhim28 @anubhakushwaha I would like to work on this issue.

**Comment by DipanshKhandelwal** [comment]
@geekanamika are you working on it ? If not can I work on it ?

**Comment by geekanamika** [comment]
Hey dipansh, I have solved it locally. Since, it hasn't been approved by any mentor yet, I haven't created pull request.

**Comment by DipanshKhandelwal** [comment]
@geekanamika no issues please carry on.

**Comment by geekanamika** [comment]
I added GSoC label on it as there is a probability that we might shift the project to Room. That's why I'm not solving any database issues currently. As Room provides an abstraction layer, the redundant code will automatically get removed.

**Comment by geekanamika** [comment]
This can be closed as I'll be handling it during Room implementation.
