### ISSUE TITLE
Disappearance of home button when Cancel is pressed

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1006]
## Description
As a user, the home button disppears in GameActivity if Cancel from the warning dialog is chosen.
I need make changes to function goToMapDialog()
so that the home button does not disappear no matter how many times it is cancelled.

## Mocks

![videotogif_2018 02 18_09 54 28](https://user-images.githubusercontent.com/26908195/36348354-b8972cd8-1493-11e8-9030-6f46b6324bde.gif)

The button on top right corner disappears after appearance of the dialog.

### Update
- [ ] [Changes in goToMap() function]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by isunitha98selvan** [comment]
I would like to work on this.

**Comment by Rimjhim28** [comment]
@isunitha98selvan I have already resolved the issue on my local machine and will be sending a PR once the issue is approved. Please look into some other open issues if available.

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by m-murad** [comment]
You have sent the PR to the wrong repo.

**Comment by Rimjhim28** [comment]
@m-murad I have sent the PR to my own repo since the issue was not approved. Once approved I will send it to systers/powerup

**Comment by Rimjhim28** [comment]
@ m-murad should I do the changes and send a PR to Systers repo??

**Comment by m-murad** [comment]
Yes

**Comment by m-murad** [comment]
Please upload a gif as well

**Comment by Rimjhim28** [comment]
@m-murad Done!! :)
