### ISSUE TITLE
Remove reductant code

### ISSUE THREAD

**Issue by DipanshKhandelwal** [systers/powerup-android#1013]
## Description
There are a lot of places where code length could be reduced.

## Mocks
![pu](https://user-images.githubusercontent.com/24923974/36635031-39570024-19d4-11e8-8134-970e3cbf4863.png)

## Acceptance Criteria
- [ ] Removing redundant operations in various files

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours 

**I would like to work on this issue.**

**Comment by pprathameshmore** [comment]
Cool!

**Comment by Rimjhim28** [comment]
@DipanshKhandelwal I think this issue is similar to #1010

**Comment by DipanshKhandelwal** [comment]
@Rimjhim28  in #1010 its written about using some loop for the assignment. I personally did not understand about how will that take place. I thought she is talking about some different redundancy. But anyways I will first check that pull request, if that solves it ill just close the issue :smile: 
Thanks :+1:

**Comment by geekanamika** [comment]
@DipanshKhandelwal This issue covers code refactoring & full code refactoring will taken up in GSoC. Please go through GSoC-Infrastructure & automation proposal list.

**Comment by DipanshKhandelwal** [comment]
@geekanamika  Ya sure thanks :+1:

**Comment by Rimjhim28** [comment]
The issue was covered during GSoC.
