### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by pprathameshmore** [systers/powerup-android#1020]
## Description
App is crashing.
In 'Load Game' , after clicking any seen, app get crashes.

## Mocks

![screenshot_1519932254](https://user-images.githubusercontent.com/17108186/36865060-6d925eea-1db4-11e8-9afd-8309771f9896.png)

## Acceptance Criteria
App must be work properly without crashing

Android API 26

## Estimation
4 hours 

@Rimjhim28

**Comment by DipanshKhandelwal** [comment]
@pprathameshmore I cant understand, How to reproduce the problem ?

**Comment by Rimjhim28** [comment]
I think this issue is already among opened ones.

**Comment by geekanamika** [comment]
@Rimjhim28 Can you mention the issues which includes this issue ? If it's duplicate , it should be closed. Also , @pprathameshmore Please go through all the open issues before creating a new issue. (refer to contribution guidelines. )

**Comment by geekanamika** [comment]
@pprathameshmore Re-open this issue if you face it again( with log messages).
