### ISSUE TITLE
Add these new dress color

### ISSUE THREAD

**Issue by pprathameshmore** [systers/powerup-android#1021]
## Description

Add these new dress color

## Mocks
![dress_avatar5](https://user-images.githubusercontent.com/17108186/36884948-ff3c2722-1e09-11e8-9de2-bd41711e663a.png)
![dress5](https://user-images.githubusercontent.com/17108186/36884949-ff7d2a88-1e09-11e8-925b-cdea66ce3e2f.png)

## Estimation
48 hours 

@Rimjhim28 @MeepyMay  Can I work on this?

**Comment by hacker5210** [comment]
I would like to work on this.

**Comment by Tagsahil** [comment]
@pprathameshmore is already working on this. Please find another issue.

**Comment by geekanamika** [comment]
@pprathameshmore This should be discussed with UI team & There has been alot improvement during outreachy work, please refer to it.
