### ISSUE TITLE
App crashing after clipboard game.

### ISSUE THREAD

**Issue by Akanshi32** [systers/powerup-android#1023]
## Description
App is crashing when match the clipboard game ends. It doesn't happen every time but seldom.

## Mocks

![crash](https://user-images.githubusercontent.com/15654390/36936654-18618736-1f2e-11e8-869d-c2afa95c7246.jpeg)

## Acceptance Criteria
App should not crash at this point.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-6 hours

**Comment by Akanshi32** [comment]
@MeepyMay  @Rimjhim28  Kindly review, thanks.

**Comment by Rimjhim28** [comment]
@Akanshi32 Can you provide the error log. I would like to work on this if this is valid.

**Comment by Rimjhim28** [comment]
@Akanshi32 Are you still on it?
I have not encountered this yet. 
@geekanamika What do you think?

**Comment by geekanamika** [comment]
I haven't encountered it too. Closing it. @Akanshi32 Please reopen the issue with gif file & log file if you encounter it again. Thank you.
