### ISSUE TITLE
Tagline For the App

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1024]
# Description
To add some more meaning to the game ,we can add a tagline for the app.For example the tagline KNOW YOUR POWER will be the best as it is quite motivating for the girls entering the puberty stage to know their real power.
# Mocks

# Acceptance Criteria
The tagline (KNOW YOUR POWER )added to the starting page of the .

# Definition of Done
- All of the required items are completed.
-  Approval by 1 mentor.

# Estimation
1 hr

**Comment by Mandeepsinghchadha** [comment]
@MeepyMay  can you approve this tagline feature  as I want to work on it

**Comment by geekanamika** [comment]
As discussed on slack , it's not required currently. Closing it for now.
