### ISSUE TITLE
Animation in the start activity

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1025]
## Description
To make the starting of the game more interactive we can add animations like left to right transition of the tagline or the name of the app when the  activity_main.xml of the app loads on the screen
# Acceptance Criteria
Animation of the kind left to right added in the activity_main.xml loads
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

# Estimation
2 hours

**Comment by Mandeepsinghchadha** [comment]
@may can you approve this feature as i want to work on this feature

**Comment by m-murad** [comment]
please discuss this on slack first.

**Comment by Rimjhim28** [comment]
As far as I can remember, this was discussed on slack and didn't have any clear decision.
I think this can be closed with an OPEN-LATER label, taking into consideration that if any decision is reached the PR can be addressed.
@geekanamika @m-murad What is your opinion?

**Comment by geekanamika** [comment]
Yeah, agreed. We can re-open it whenever required.

**Comment by Mandeepsinghchadha** [comment]
@geekanamika @Rimjhim28  sometimes I really get confused are you a Gsoc participant or a mentor or maintainer.I think closing an issue should require a mentor's approval .Also If you have power to close an issue then do you have the authority of approving a PR in the same way?

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha Sorry for the confusion.
With the new member levels of Systers we are also working as maintainers for the repo.
Yes, we can approve issues and PRs, provided they are valid ones.
We are also GSoC aspirants. I hope this clears up your doubt.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28 In that case there is no difference between a maintainer  and a mentor . Also if a Gsoc participant has the power to approve this own issues and pr's then why do we need a mentor for this project?

**Comment by m-murad** [comment]
@Mandeepsinghchadha 
That's not the case.
If a maintainer is selected as a GSoC student they will not be allowed to approve issues or PRs. It will be done be GSoC mentors.

Maintainers can only do stuff on related to GitHub (approving PRs etc), stuff related to GSoC like selecting students, passing/failing student can only be done by GSoC mentors.

**Comment by Rimjhim28** [comment]
We can give our opinions on other contributors' issues and prs. We don't have the authority to approve our owns. In that case we require other maintainers and mentors to approve them.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
