### ISSUE TITLE
Sharing Karma Points On Facebook

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1026]
## Description
Facebook api integration  with the app to share the karma point on social networking platforms like facebook to promote the app among the girls and their peers

## Acceptance Criteria
Facebook api integration with the app to successfully share the karma points

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-7  hours

**Comment by Mandeepsinghchadha** [comment]
@may can i work on this issue?

**Comment by geekanamika** [comment]
It's not required currently. Though you can discuss it in slack channel :)
