### ISSUE TITLE
POINTS TO TAKE AWAY

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1027]
## Description
At the completion of every scenario  we can have points to take away which can brief about all the ideas
and lessons learnt after the scenario point wise.This will help the young girls recollect all the ideas she was shown in the respective scenario 

## Acceptance Criteria
An xml page(Before the completion of every scenario) of points to remember added after every scenario(home,school,library,hospital).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4  hours

**Comment by Mandeepsinghchadha** [comment]
@MeepyMay  kindly approve this I would like to work and complete this feature.

**Comment by m-murad** [comment]
this is a new idea and should be discussed on slack first

**Comment by AjaySharvesh3** [comment]
Is this discussed on slack? Or shall I claim this issue? @m-murad

**Comment by Rimjhim28** [comment]
I think this will be covered in outro sequences to be ported from iOS.
