### ISSUE TITLE
Healthcare Tracking

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1028]
## Description
In order to make power-up app more informative we can add GOOGLE LOCATION API to track the location of the girl using  the power-up app and how various healthcare centres for women nearby her which could help her in the time of need 

## Acceptance Criteria
Added the google's location API

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-7 hours

**Comment by Mandeepsinghchadha** [comment]
@may can you kindly approve this feature

**Comment by geekanamika** [comment]
This doesn't fit well with the idea of powerup application, please discuss new idea in #ideas channel on slack. :)
