### ISSUE TITLE
Languages Extension

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1029]
## Description
To increase the range of the app in various countries we can add few more languages drop down option in  the start activity to help the girls who cannot read English language that well

## Acceptance Criteria
Different languages added in the start activity

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
7-8 hours

**Comment by Mandeepsinghchadha** [comment]
@may can you kindly approve this feature

**Comment by geekanamika** [comment]
@Mandeepsinghchadha As it will be a major change to provide more language support, It needs discussion in slack channel/open session.

**Comment by Rimjhim28** [comment]
@geekanamika This is a kind of enhancement. I am adding the label, while the issue can still be kept open to avoid any duplication.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
