### ISSUE TITLE
UI fixes in Scenario 

### ISSUE THREAD

**Issue by Akanshi32** [systers/powerup-android#1031]
## Description
The scenarios need UI fixes, the Scenario name is not visible in some of the cases.

## Mocks
![screenshot_2018-03-03-22-09-43](https://user-images.githubusercontent.com/15654390/36975290-abd35d7e-209f-11e8-8f0d-645bbfa54a93.png)
![screenshot_2018-03-03-22-08-52](https://user-images.githubusercontent.com/15654390/36975292-ad7bfd34-209f-11e8-9f37-ff700cfca66f.png)

## Acceptance Criteria
Clearer view of scenario name to make the application look more professional.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-6 hours.

@MeepyMay  @prachi1210  @Rimjhim28  I would like to work on this

**Comment by Rimjhim28** [comment]
@Akanshi32 It would be better if you could provide some mocks on how you intend to solve this.
Moreover, since this is an UI change, it would require decision from community as well, so initiating the dicussion on slack channel could be a better option.

**Comment by AjaySharvesh3** [comment]
Shall I claim this make the UI better @Rimjhim28

**Comment by Rimjhim28** [comment]
@AjaySharvesh3 as explained earlier, this is a ui enhancement and would require community decision.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
