### ISSUE TITLE
Fix memory leak in SplashActivity.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1032]
## Description
There is memory lean in `SplashActivity`. The callbacks on the handler should be removed in the `onDestroy` mentod.

### Update [Required]
- [ ] Fix the leak
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by DipanshKhandelwal** [comment]
@m-murad can I work on it?

**Comment by m-murad** [comment]
@DipanshKhandelwal 
Sure but ask for the mentor's approval first.

**Comment by geekanamika** [comment]
@m-murad Can i work in this issue ?

**Comment by DipanshKhandelwal** [comment]
@geekanamika I have solved it, I am just waiting for an approval.

**Comment by m-murad** [comment]
@DipanshKhandelwal 
please send the PR

**Comment by DipanshKhandelwal** [comment]
@m-murad give it a look please. Thanks :+1:

**Comment by AjaySharvesh3** [comment]
Can I claim this issue? @m-murad @Rimjhim28 @geekanamika
