### ISSUE TITLE
AboutActivityTest is failing.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1033]
## Description
The `AboutActivityTest` is failing because `android.os.Build;` has not been imported.

### Update [Required]
- [ ] Import the `Build` class from `android.os` package.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by geekanamika** [comment]
@m-murad I will look into it & update. Thanks :)

**Comment by m-murad** [comment]
@geekanamika 
happy to help
