### ISSUE TITLE
MINI GAME

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1034]
## Description
In order to educate the girls in a interactive manner we can make a menstrual island mini game and the aim of the game will be corresponding to earning  karma points at each and every step of menstrual island game to maximise your score.
1)Game will start with mountain of pain which is are the initial days of the periods every month.
There can be question pop ups related to dealing with this pain which on suitably answering will 
Maximise your karma points based on the answers.
2)Then the girl will reach crampy island where the pain reduces a bit but there are overall cramps and weakness in their bodies. 
3)Snack bar and drug cabin fuel house for girls to increase their energy at this painful time
4)if the girl takes the wrong path(doing some physical exercise or anything that complicates her pain) such as  clot island or misery island it can reduce her karma points.
5)Another scenario related to mood swings can be added to this game.
6)Finally after  reaching the hms sanity ship which indicated the end of periods cycle of the months the mini game can end.

## Mocks
![menstural_island](https://user-images.githubusercontent.com/27005975/37000084-37dcaba2-20e8-11e8-8de8-7e2acb5cfdce.jpg)

## Acceptance Criteria
Mini game approved and made
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4 days

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this so that i can work on this as this mini game can be really interactive and educative

**Comment by geekanamika** [comment]
Hello @Mandeepsinghchadha You only need to discuss it on slack & make changes as suggested , creating an issue is not required.
