### ISSUE TITLE
Dance classes Scenario

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1036]
## Description
Apart from school,library girls of age 12-13 perform extracurricular activities such as dance classes where the there can be chances of sexual assault and violence .So we can extend the game by adding this scenario

## Acceptance Criteria
Scenario added

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-6 days

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this issue so that i can work on it

**Comment by geekanamika** [comment]
Please create mockups for this idea & discuss it in #ideas channel. :)
