### ISSUE TITLE
Change of characters in Scenarios

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1037]
## Description
As a user seeing the same character in every scenario(Marcello) can be monotonous So if we change the character in different scenarios(talking about marcello) or have a option for it in the starting will make the game better

## Acceptance Criteria
New characters added in context of marcello

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this i would like to work on this

**Comment by geekanamika** [comment]
You must discuss it in ideas channel & include it in your GSoC proposal , please refer to contribution guidelines before creating an issue.
