### ISSUE TITLE
Adding voice behind mini games

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1038]
## Description
In order to attract more and more users we can add mario or any different game sound in the mini games to make it more interactive 

## Acceptance Criteria
Sound added in every mini game

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this So  that i can work on it

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha Can you please explain what do you aim to do here since the mini games already have some sound implementations.

**Comment by geekanamika** [comment]
@Mandeepsinghchadha You should it in ideas channel & include it in your proposal :) Please don't create an issue for every idea :)
