### ISSUE TITLE
KARMA POINTS

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1039]
## Description
To make the UI better we can replace the karma points stars with emoji's or smileys 

## Acceptance Criteria
Karma points stars replaced with better options

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Mandeepsinghchadha** [comment]
@may I would like to work on this kindly approve this

**Comment by geekanamika** [comment]
@Mandeepsinghchadha Systers will be following software design cycle & TDD onwards , please discuss it in ideas channel & include it in your proposal :)
