### ISSUE TITLE
Fix avatar on horizontal mobile displays

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#104]
On mobile devices on landscape mode, the different body parts of the avatar are not correctly places and lay on top of each other. This should be fixed so the avatar is correctly displayed

**Comment by AkankshaBodhankar** [comment]
I will try to work on this

**Comment by AkankshaBodhankar** [comment]
You mean this overlay of avatar right? I'll work on it and make a PR 
![screenshot_2016-02-16-14-38-17_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13073891/34054af8-d4c7-11e5-9cda-bae5f24c9c09.png)

The conversation box (i.e the listview is also not showing all the options 
Like here it should show
Maybe some another time
Sure (not showing)
![screenshot_2016-02-16-15-07-11_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13073934/6ab8041e-d4c7-11e5-83ce-9953f7bbb7bb.png)
![screenshot_2016-02-16-14-38-59_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13073937/73d77980-d4c7-11e5-9f36-58cb4edec772.png)
