### ISSUE TITLE
Home scenario video

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1040]
## Description
As the home scenario in the game is related to molestation and assault so after completion of home scenario ,a link of a video on youtube can be added to the home completion scenario to make the game more educative.

## Acceptance Criteria
Video after after home scenario

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this I would like to work on this

**Comment by geekanamika** [comment]
@Mandeepsinghchadha Please discuss it in ideas channel & include it in your proposal. :)
