### ISSUE TITLE
School scenario video

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1041]
## Description
As the home scenario in the game is related to unprotected and un timed sex so after completion of home scenario ,a link of a video on youtube can be added to the school completion scenario to make the game more educative.
## Acceptance Criteria
Video added after completion of school scenario
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by prachi0311** [comment]
@Mandeepsinghchadha I would like to solve this issue.

**Comment by geekanamika** [comment]
@Mandeepsinghchadha You should discuss ideas on slack , please avoid creating an issue for new ideas. Create any mockups & include it in your proposal :)
