### ISSUE TITLE
Do you Know

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1042]
## Description
In every scenario apart from character and text boxes there is a lot of empty space to make every scenario more educative we can add DO YOU KNOW type informatory ideas in every scenario.

## Acceptance Criteria
DO YOU KNOW boxes added in every scenario.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by geekanamika** [comment]
@Mandeepsinghchadha Please follow the issue template before creating an issue.
