### ISSUE TITLE
Sexually transmited diseases mini game

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1043]
## Description
We can add a crossword puzzle time mini game which contain the hints abouts some STD and the user has to mark the correct disease in the puzzle .This will be interactive and educative on the same level

## Acceptance Criteria
Crossword puzzle added as the mini game

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12-13 hours

**Comment by Mandeepsinghchadha** [comment]
@may kindly approve this As I want to work on this mini-game

**Comment by geekanamika** [comment]
@Mandeepsinghchadha mini-game development will be taken during GSoC period, please create mockups & discuss it in ideas channel :)
