### ISSUE TITLE
Improve Karma points distribution

### ISSUE THREAD

**Issue by DipanshKhandelwal** [systers/powerup-android#1044]
## Description
As a user
I need change how karma points is given to player,
so that I can bring consistency in game play and points earned.

## Mocks
N/A

### Update [Required]
- [ ] Change how karma points are distributed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

I would like to work on this.

**Comment by geekanamika** [comment]
Hi @DipanshKhandelwal , Can you explain it more ? Looks like an enhancement, we should discuss it on slack channel.

**Comment by DipanshKhandelwal** [comment]
Yes, @geekanamika we must discuss it. Actually I think, the karma points distribution earning from a scenario, is not clear or correct. Some places I saw that if we choose the options that should not be chosen gives you a better karma score than the correct one. So we must define a good map about how the points should be distributed in the scenarios.

**Comment by AjaySharvesh3** [comment]
Is there any discussion going on for this issue? @geekanamika @DipanshKhandelwal

**Comment by DipanshKhandelwal** [comment]
@AjaySharvesh3 No we didn't have any discussion on this topic till date.

**Comment by asclepiusgal** [comment]
@geekanamika @DipanshKhandelwal what is the status of this? Our GSoC student is ready & willing to resolve this
