### ISSUE TITLE
Add authentication and save highscores

### ISSUE THREAD

**Issue by DipanshKhandelwal** [systers/powerup-android#1045]
## Description
As a user,
I need add authentication system,
so that I can add accounts and save highscores and leaderboard.

## Mocks
N/A

### Update [Required]
- [ ] Add Authentication
### Enhancement to Update [Optional]
- [ ] Add Profile section

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-17 hours 

I would like to work on this

**Comment by pprathameshmore** [comment]
@DipanshKhandelwal I think there is no need of authentication in this game! This game for girls age between 12-14.
@prachi1210 @Rimjhim28 @m-murad

**Comment by geekanamika** [comment]
@DipanshKhandelwal Please discuss it in powerup channel , if mentors approve , we'll open it later.

**Comment by AjaySharvesh3** [comment]
It's in opened. Is there any discuss for this issue? Or can I claim it? @geekanamika @Rimjhim28 @m-murad

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
