### ISSUE TITLE
Grammatical Error in the About section

### ISSUE THREAD

**Issue by aayushinigam** [systers/powerup-android#1049]
There is this grammatical error that I have encountered in the  'About' section of the app.
It says "Why this App is needed", which should be changed to "Why is this App needed?" 

![screenshot_20180311-084848](https://user-images.githubusercontent.com/24635221/37249285-b9088040-250a-11e8-9076-5768bd13e794.png)

**Comment by aayushinigam** [comment]
@MeepyMay  @Rimjhim28  As a newcomer, for my first PR, I would like to work on this. Kindly approve.

**Comment by Rimjhim28** [comment]
As far as I know concentrating on the content here was more important than language.
@MeepyMay could give a better suggestion here.

**Comment by geekanamika** [comment]
@aayushinigam Try working on any existing first-timers issue ? I remember it being mentioned on slack somewhere that All the statements were documented with consideration & it's not the utmost importance now. 
Also , mentors might not be active currently. So , you can find any issues (without PR) & work on it on your own fork, if it's a valid issue, It'll be consider as a contribution too. :)
