### ISSUE TITLE
No layout preview in xml files

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1051]
## Description
As a user,
I need update the gradle dependecies version, tagetSdkVersion and compileSdkVersion,
so that the layouts are properly displayed in xml files.

## Mocks
![error log](https://user-images.githubusercontent.com/26908195/37252458-10105304-2547-11e8-8947-9e9afc79f2da.png)
![no layout views](https://user-images.githubusercontent.com/26908195/37252459-104f6c38-2547-11e8-8fdc-708460be4b93.png)

### Update 
- [ ] Fix the gradle dependencies

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by Rimjhim28** [comment]
@geekanamika @m-murad  Please approve. I would like to work and fix the same.

**Comment by m-murad** [comment]
This is a valid issue. Please send a PR to fix this.
