### ISSUE TITLE
Dr Bulma Hospital scenario

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1053]
## Description
As  a user in the hospital scenario instead of marcello ,Doctor bulma should appear as this would create a negative impact/misunderstanding among the users. 
##Mocks
![screenshot_2018-03-11-21-29-39-586_powerup systers com powerup](https://user-images.githubusercontent.com/27005975/37255619-cf64a4a8-2574-11e8-9856-14cd48b8cbdb.png)

## Acceptance Criteria
Under the doctor character there should be Dr bulma appearing instead of marcello

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
@may @prachi @m-murad  I would like to work on this kindly approve

**Comment by Rimjhim28** [comment]
I think this is quite similar to #1054 
Please don't create multiple issues for same implementation.
@geekanamika Kindly look into this.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  This is a different issue as it for a different scenario with  a different name of the person

**Comment by geekanamika** [comment]
@Mandeepsinghchadha You have mentioned hospital(scenario) in both issues ( #1054 ) .

**Comment by Mandeepsinghchadha** [comment]
@geekanamika  The situation  may be similar in terms of code but making two issues for two different scenarios  won't hurt much.

**Comment by m-murad** [comment]
discuss this on slack first
