### ISSUE TITLE
Uncle Mathew Home scenario

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1054]
## Description
As a user in the hospital scenario instead of marcello ,Uncle Mathew should appear as this would create a negative impact/misunderstanding among the users.
##Mocks
![screenshot_2018-03-11-22-56-00-394_powerup systers com powerup](https://user-images.githubusercontent.com/27005975/37256379-e5356f96-257f-11e8-88eb-28d4d95eba52.png)

## Acceptance Criteria
Under the doctor character there should be Dr bulma appearing instead of marcello

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this I want to work on this

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha Replacing marcello with Uncle Mathew won't be an appropriate option.
Moreover, this is among among GSoC idea list so it would be better if you include some mockups and implementation ideas in your proposal instead of creating an issue.
@geekanamika Kindly look into this.

**Comment by geekanamika** [comment]
@Mandeepsinghchadha This is a new idea that must be discussed first before the coding. As suggested in various closed issues , Please discuss it on slack channel :)

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  In the Text boxes the name of the person is Uncle mathew not marcello  also this issue is different from hospital scenario so remove this reference as they are different .Morever this is a  bug not an idea

**Comment by Mandeepsinghchadha** [comment]
@geekanamika  I am again pointing out this is not an idea it is a bug that needs to be fixed.

**Comment by m-murad** [comment]
discuss this on slack first
