### ISSUE TITLE
Map Button On Library Page

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1055]
## Description
When the user visits the library page once there is a map button on the top right but when user visits the maps and comes again to the library the button disappears

## Acceptance Criteria
Map button added at top right corner in the library scenario

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this as I want to work on this issue

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha The map button is present in all scenarios ( including library )
Please make sure that you are on correct branch with the latest code.
@geekanamika Kindly look into this.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  I have updated the issue  kindly see it again

**Comment by Rimjhim28** [comment]
So now it is similar to #1056 and that is again an invalid one.
