### ISSUE TITLE
Map Button Home Page

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1056]
## Description
When the user visits the Home page once there is a map button on the top right but when user visits the maps and comes again to the Home the button disappears

## Acceptance Criteria
Map button added at top right corner in the Home scenario

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Rimjhim28** [comment]
The issue was already reported through #725 and was solved through #739 .
Please go through contributing guidelines.
Make sure that you are working on latest version of code.
