### ISSUE TITLE
Previous Scenarios not in sync with current scenario

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1059]
## Description
Right Now when a user plays a current scenario and go to map then there is a page popup that the current scenario  is completed and you have gained some karma points but the screen popup should be that first finish the current scenario to give the user a better picture

## Acceptance Criteria
Navigation screen added

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  I would like to work on this bug

**Comment by m-murad** [comment]
Valid issue, please send a PR.

**Comment by Rimjhim28** [comment]
@murad @Mandeepsinghchhada I have already created this issue. Please go through open issues once again

**Comment by Rimjhim28** [comment]
Similar to #999

**Comment by m-murad** [comment]
This is a duplicate issue. 
@Rimjhim28 please send a PR for this.
@Mandeepsinghchadha you can close this issue
