### ISSUE TITLE
After Game completes

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1060]
## Description
After the game is completed there is no option of new game or replay the game which creates  a confusion for user

## Acceptance Criteria
After game completion new game or replay screen navigation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this bug so that i can work on it

**Comment by m-murad** [comment]
You point seems valid to me.
But I'm not sure if this is an issue or as planned.

Let's discuss more on this on slack.

**Comment by Rimjhim28** [comment]
After the game is completed there is a button which can direct the user back to map and then from map she can choose to play any scenario of her choice here.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  when you create a game it has to be user friendly you cant just assume the users to use their instincts to navigate in the game

**Comment by m-murad** [comment]
like I said let's discuss this on slack.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
