### ISSUE TITLE
Scenario Resume

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1061]
## Description
When the users plays a scenario then go back to map and again come back to the current scenario it finishes rather than resuming that scenario

## Acceptance Criteria
Resuming the current scenario after visiting of map 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this i would like to work on this bug

**Comment by m-murad** [comment]
Valid issue, please send a PR

**Comment by Rimjhim28** [comment]
@m-murad I think it would be better if @Mandeepsinghchadha could provide a gif file here to explain the issue properly. 
If a scenario is left in mid and is chosen again it restarts which I think is absolutely fine to get the flow of the conversation.
If a scenario is already played and is chosen again the user is first presented with a scenario over screen.

**Comment by Rimjhim28** [comment]
I don't think this is a valid one and it can be closed.
@geekanamika @m-murad What do you think?

**Comment by Rimjhim28** [comment]
Closing as this is not a valid issue.
