### ISSUE TITLE
Exit Button on Main Page

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1063]
## Description
Right now the main page only has new game and Load game but there is no Exit Button on the Main page and every game should have an Exit Game option and not having such exit button will reduce the user friendly nature of the game
## Acceptance Criteria
Exit Button added

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this issue so that i can work on it

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha I think this would be an enhancement. As you know, for every  enhancement you first need to discuss it on slack. Moreover there is a confirmation toast "press again to exit" that pops up when the user hits the back button on device on home screen so putting an exit button won't be much feasible idea.
Though @m-murad could provide a better suggestion here.

**Comment by Mandeepsinghchadha** [comment]
@I think it is necessity of the game and reduces the user friendly nature .Also likewise on a scenario why do we have a go to map activity when user can press the back button on the scenario to go to the map  .I think this will answer your query .

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  Also this is not an enhancement just a mere need of the game right now

**Comment by Rimjhim28** [comment]
But it is not a "bug" I guess. The project creates have created it that way so if they have not felt the necessity to create an exit button there must be a reason.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  In that way there is also not a necessity for go to maps activity in the scenario but to make it user friendly it has to be done .Having an exit button is  a part of every game you play and not adding this will be considered as downfall of the game(It is a major bug) not just a mere enhancement or luxury button of the game but this game will go into masses and not adding a exit button is not justified

**Comment by m-murad** [comment]
@Mandeepsinghchadha 
nice idea, but let's have a discussion on this. 

Discussion is necessary because there is an iOS version of the project. The two versions must remain similar.

**Comment by pprathameshmore** [comment]
@Mandeepsinghchadha I think there is no need for Exit Button. If you press Exit Button app will close automatically!

**Comment by Mandeepsinghchadha** [comment]
@pprathameshmore please read the explainations i have given above for its necessity kindly see it first

**Comment by pprathameshmore** [comment]
@Mandeepsinghchadha Let discuss in Slack! I think it looks great!

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
