### ISSUE TITLE
Mini Games

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1064]
## Description
As a user while playing a mini game I should have a option to exit the mini game and go the map  without resuming the game(Losing all the karma points of that mini game) and when user comes again to that scenario he has to play the mini game again from scratch

## Acceptance Criteria
Go to map without resuming button added

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this issue

**Comment by m-murad** [comment]
discuss on slack first

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
