### ISSUE TITLE
Mini Game with resuming 

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1065]
## Description
As an user if i want visit a map with the resuming of the game it should be possible and there should another button

## Acceptance Criteria
Go to maps activity with resuming button should be there 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad  kindly approve this I would like to work on this .

**Comment by m-murad** [comment]
please discuss on slack

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha Can you please be more clear on this.
I think LOAD GAME nutton is doing the same thing now.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
