### ISSUE TITLE
Skip Option

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#1066]
## Description
While playing a mini game I should have skip mini game option to end the mini game and move forward in the game

## Acceptance Criteria
Skip mini game button added 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by Mandeepsinghchadha** [comment]
@m-murad kindly approve this

**Comment by m-murad** [comment]
discuss on slack first

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha @m-murad This is similar to #774  #775  #776

**Comment by geekanamika** [comment]
Since , Similar issue exist , Closing it.
