### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aayushinigam** [systers/powerup-android#1068]
As a developer,

I need to update the README.md file which asks to fetch the latest code from branch "GSoC17" even though the latest code is in branch "develop"

so that I can fetch the latest code correctly.

### Update [Required]
- [ ] [README.md]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by aayushinigam** [comment]
@m-murad kindly approve this.

**Comment by geekanamika** [comment]
@aayushinigam I think @Janiceilene is handling the documentation part as an outreachy intern.

**Comment by aayushinigam** [comment]
@geekanamika Oh I didn't know. So I shouldn't bother waiting for its approval then?

**Comment by geekanamika** [comment]
You can ask it on slack , you might get approval too as outreachy has ended.

**Comment by Janiceilene** [comment]
I'm okay with this change, as long as you are @geekanamika.

**Comment by geekanamika** [comment]
Hey @aayushinigam Ask for mentors approval & go ahead, once approved. :)

**Comment by Rimjhim28** [comment]
This instruction is misleading and it's better to solve it as soon as possible.
@aayushinigam Please send a PR for this.

**Comment by aayushinigam** [comment]
@geekanamika  @Rimjhim28 Okay, I will. Thanks :)

**Comment by m-murad** [comment]
@aayushinigam @Rimjhim28 @geekanamika 
`Readme.md` needs some other changes, should those be done along with this?

**Comment by Rimjhim28** [comment]
@m-murad this issue only pointed out the misleading instruction. 
I think you are pointing the changes for contribution guidelines. We had a conversation on this on slack and @geekanamika pointed that it had some discussion in one of maintainers call. I think we can hold this change for now and come back to it after a proper decision has been taken.
