### ISSUE TITLE
Back to Map and Replay button dont finish activity

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#107]
When replay or backtoMap is pressed from within a scenario, the corresponding activity is called but current not finished which leads to multiple instances of the same scenario in various stages. Also the visibility of buttons needs to be fixed accordingly. Willing to work on this if required.

**Comment by yatna** [comment]
Multiple instances of the same scenario have been fixed by popping off the backstack in PR #83 .

**Comment by chhavip** [comment]
I probably tested on older code, closed issue!
