### ISSUE TITLE
Use Room Persistence library.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1077]
## Description
As a developer,
one can observe that the application is still using the conventional SQLite database without any ORM library,
we should use the Room persistence library on top of existing SQLite to make the DB handling convenient.

### Update [Required]
- [ ] Use Room for SQLite queries
- [ ] Write tests for database

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1 week

**Comment by Rimjhim28** [comment]
@m-murad May I work on this?

**Comment by geekanamika** [comment]
@m-murad Since this will be a big change , I've added it in my timeline. Is this open currently ?

**Comment by m-murad** [comment]
@Rimjhim28 @geekanamika 
This enhancement should be added during the GSoC period.

**Comment by geekanamika** [comment]
@m-murad I think, we can close this issue as I'll be needing step wise issues to create PRs. I'm working on it.
