### ISSUE TITLE
Use Butterknife for view injection

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1078]
## Description
As developers,
we can use view injection library [Butterknife](http://jakewharton.github.io/butterknife/) for view injection. This will reduce the lines of code and make the code readable.

### Update [Required]
- [ ] Use butterknife for view injection

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
3 days

**Comment by geekanamika** [comment]
@m-murad Can i work on this ?

**Comment by m-murad** [comment]
@geekanamika
This enhancement should be added during the GSoC period.

**Comment by Mandeepsinghchadha** [comment]
@m-murad i have worked on butterknife before can i work on this

**Comment by swaroop-nath** [comment]
Hey @geekanamika and @m-murad, Can I work on this too?

**Comment by geekanamika** [comment]
@swaroop-nath As murad mentioned, it would be added during GSoC period.

**Comment by geekanamika** [comment]
As per community decision, we'll use Butterknife for view injection. Closing it.
