### ISSUE TITLE
Implement the observable pattern throughout the application.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1079]
## Description
Use [LiveData](https://developer.android.com/topic/libraries/architecture/livedata.html) to implement observable pattern throughout the application.

### Update [Required]
- [ ] Integrate LiveData library to follow the observable pattern throughout the application.
- [ ] Write tests for all the LiveData integrations.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 Weeks

**Comment by Mandeepsinghchadha** [comment]
@m-murad  can i work on this

**Comment by m-murad** [comment]
To be done during GSoC

**Comment by geekanamika** [comment]
Closing it as We'll be following MVP for design pattern & there isn't much need of LiveData in powerup application(as per community open session discussion).
