### ISSUE TITLE
Create ' Play Again ' option. 

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#108]
Right now once the user has completed the game , she cannot replay the game . To replay she must re install the .apk file.
I think it would be better if , we provide a option to replay the game. If suggested we can also implement the feature to activate the replay button only when the entire game is finished.

**Comment by yatna** [comment]
Willing to work on this issue if required.

**Comment by alma-castant** [comment]
Each scenario can only be replayed once right after it has been finished ;)
