### ISSUE TITLE
Create ViewModel for all activities.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1080]
## Description
As developers, we need to create [ViewModels](https://developer.android.com/topic/libraries/architecture/viewmodel.html) for all activities. This will make the code readable and testable. 

### Update [Required]
- [ ] Add ViewModels for all activities

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1 Week

**Comment by pprathameshmore** [comment]
Should I work on this?

**Comment by geekanamika** [comment]
@pprathameshmore This will be taken during GSoC period.

**Comment by pprathameshmore** [comment]
@geekanamika Okay!

**Comment by pprathameshmore** [comment]
@geekanamika Add GSoC lable

**Comment by AjaySharvesh3** [comment]
Can I claim this issue?

**Comment by AjaySharvesh3** [comment]
@m-murad can I claim this?

**Comment by Rimjhim28** [comment]
@AjaySharvesh3 as mentioned by @geekanamika the issue will be taken up during gsoc.

**Comment by geekanamika** [comment]
Closing it as We'll be following MVP for design pattern.
