### ISSUE TITLE
Create ViewModel for all fragments.

### ISSUE THREAD

**Issue by m-murad** [systers/powerup-android#1081]
## Description
As developers, we need to create [ViewModels](https://developer.android.com/topic/libraries/architecture/viewmodel.html) for all fragments. This will make the code readable and testable. 

### Update [Required]
- [ ] Add ViewModels for all activities

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1 Week

**Comment by manddy** [comment]
@m-murad i want to work on this

**Comment by Mandeepsinghchadha** [comment]
@m-murad i want to work on it

**Comment by m-murad** [comment]
This is for GSoC period

**Comment by geekanamika** [comment]
Closing it as We'll be following MVP for design pattern.
