### ISSUE TITLE
Convert existing PNG, JPG images into WebP image format

### ISSUE THREAD

**Issue by pprathameshmore** [systers/powerup-android#1082]
## Description
Convert existing PNG, JPG images into WebP image format,
so that I can help to reduce apk size.

## Mocks
The left side has PNG Image and the right side has WebP image.

After converting into WebP.

![apksize reduce](https://user-images.githubusercontent.com/17108186/37489919-2b7c505e-28bf-11e8-9414-b91f20ba33bf.JPG)

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [x] APK size get reduced.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours 

@m-murad @MeepyMay Can Do I work on this?

**Comment by m-murad** [comment]
@pprathameshmore 
Because of GSoC all mentors are busy (gathering requirements and reviewing proposals) and will not be able to review a PR of this scale now. It's better if this is completed during the GSoC period.

**Comment by m-murad** [comment]
For future reference - 
![screen shot 2018-03-16 at 2 39 19 am](https://user-images.githubusercontent.com/17262180/37491388-aff9eb58-28c3-11e8-9d56-31e9f4cdbbe1.png)

**Comment by pprathameshmore** [comment]
@m-murad Okay! I will complete this in GSoC period. Can I add this to my proposal?

**Comment by m-murad** [comment]
Sure

**Comment by Nuwini** [comment]
@pprathameshmore It is very much needed that you pay attention to the quality of the images, when doing the suggested change

**Comment by pprathameshmore** [comment]
@Got it!

**Comment by Rimjhim28** [comment]
The issue was covered during GSoC.
