### ISSUE TITLE
Safe remove unnecessary methods and code

### ISSUE THREAD

**Issue by pprathameshmore** [systers/powerup-android#1085]
## Description
As a developer,
I need safe remove unnecessary methods and code,
so that I can make code look better and maintainable.

## Mocks

![gith](https://user-images.githubusercontent.com/17108186/37593457-106ef0ce-2b98-11e8-8719-ed4d447e44b9.JPG)

### Update [Required]
- [ ] Removed innecessary code from all files.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 

@m-murad Please take look at this issue.

**Comment by Rimjhim28** [comment]
IMO, these are not completely unnecessary but the basic getters and setters. Though they are not being used right now but can be expected to be used in future with addition of more scenarios and mini games. Removing them completely would be costly, in a way that if they are needed in next development cycle, time has to be invested again to write them.

**Comment by pprathameshmore** [comment]
@Rimjhim28 You are right!
