### ISSUE TITLE
Bad Readability in AboutActivity

### ISSUE THREAD

**Issue by nirupamgunwal** [systers/powerup-android#1088]
## Description
As a [USER],
I need [to give a white background behind the text],
so that I can [make the text readable].

### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by geekanamika** [comment]
@nirupamgunwal You are supposed to use the issue template to create an issue. Leaving Acceptance criteria blank & not mentioning the enhancement is not the goal of providing the issue template. 
This is a enhancement. Please join slack channel #powerup  & discuss it. You can reopen this issue once it's approved & Please go through contribution guidelines!
