### ISSUE TITLE
Appearing a corrupted image in ReadMe.md

### ISSUE THREAD

**Issue by PiumiHR** [systers/powerup-android#1090]
## Description
As a GSoC Aspirant,
I need improve the ReadMe documentation.
The Travis icon is corrupted. 

## Mocks
![readme-powerup-uppersection](https://user-images.githubusercontent.com/19715380/37958308-cd458326-31cd-11e8-839a-c2b3b6d825a2.PNG)

### Update [Required]
- [ ] https://img.shields.io/travis/rust-lang/rust.svg?style=plastic file is not loading
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by geekanamika** [comment]
This is a valid issue. Though  PR 1091 doesn't solve the problem.  Replacing the existing link with [![Build Status](https://travis-ci.org/systers/powerup-android.svg?branch=develop)](https://travis-ci.org/systers/powerup-android) will solve the issue. 

@m-murad @Rimjhim28 What do you think?

**Comment by geekanamika** [comment]
Strange, It is working fine now. ![image](https://user-images.githubusercontent.com/16922933/37969517-929620de-31ee-11e8-86d0-9f8f7a53413b.png)

**Comment by Rimjhim28** [comment]
It is working fine on my end @geekanamika @PiumiHR

**Comment by geekanamika** [comment]
@PiumiHR I'm closing this issue for now.
