### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#1095]
## Description
As a developer,
I need to update README.md,
so that Information available is consistent with the repository.

## Acceptance Criteria
All the following changes will be completed:
* Remove the link provided in Point 1 under `Set up for developers`
* Delete point 5 under `Set up for developers`
* Remove step 1 under `Configure remotes`
* Update command `git merge upstream/master` to `git rebase upstream/develop`
* Update `master` branch to `develop` in the file.
* Add a point under `Set up for developers` which directs to build `Powerup` which is inside the base directory.
* Change the documentation link under `Documentation of PowerUp (Android)` to [link](https://github.com/systers/powerup-android/wiki#overview)
* Correct `Code of Conduct` link provided in `CONTRIBUTING.md`

### Update [Required]
- [ ] README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 hours 

Issue discussion  : [Slack thread](https://systers-opensource.slack.com/archives/C0C9VK8UE/p1522316456000019)

**Comment by Rimjhim28** [comment]
@geekanamika Looks good to me.

**Comment by AjaySharvesh3** [comment]
@geekanamika @Rimjhim28 Can I claim this now?

**Comment by Rimjhim28** [comment]
@AjaySharvesh3 as the label suggests, the issue is for first timers.
Since you have already worked on one of the first timer issue you cannot work on this one.

**Comment by AjaySharvesh3** [comment]
Oh! Yah, I'm sorry!

**Comment by Sabihashaik** [comment]
Hi! I'd like to work on this.

**Comment by Rimjhim28** [comment]
@Sabihashaik sure! Send a PR.

**Comment by Sabihashaik** [comment]
Thanks, I have a question regarding the 6th change. Adding a point which directs to build Powerup. Does that mean I should link it to the build.gradle file in the base directory? I didn't quite get that task.

**Comment by geekanamika** [comment]
@Sabihashaik Usually base repo project is the android project, many newcomers make this mistake while building the project. You just have to add a point that will mention "Build powerup(link with if possible) as an android project instead of building the base directory"

**Comment by Sabihashaik** [comment]
@geekanamika Thank you for the clarification. I have sent a PR.

**Comment by ghost** [comment]
@geekanamika Is this issue still open? If so can I work on it? I ask because I saw that you changed the status to "Available."

**Comment by geekanamika** [comment]
@Arbalest007 Yes, this issue is available. Go ahead :)

**Comment by ghost** [comment]
Awesome thanks! I'll get on it!

**Comment by ghost** [comment]
@geekanamika I have a question regarding the first requirement for the README changes. The instructions say to remove the link provided under Point 1 for "Set Up." There are 3 links total - 1 directing to Android Studio's SDK, and 2 referring to links regarding the AD 3.0 Gradle Plugin Migration + Gradle Plugin. Would you like all 3 links to be removed?

**Comment by rhythm1705** [comment]
Hey, I would like to contribute to this issue too. Can I please?

**Comment by ghost** [comment]
@rhythm1705 I'm not working on this issue anymore so it's up for grabs!

**Comment by FIITAY** [comment]
hey, can I contribute to this issue?

**Comment by namrata-jha** [comment]
Looks like this issue is still open, can I go ahead and work on this issue?

**Comment by geekanamika** [comment]
@namrata-jha Refer to PR #1313 . It's almost complete except one required change. @FIITAY hasn't responded since review so you can go ahead & create PR. Let me know if you need any help :)

**Comment by namrata-jha** [comment]
Yes, I have created a PR, please check.

**Comment by Rimjhim28** [comment]
@namrata-jha You have already claimed one first timer issue, #1102. You can claim and work on only one first timer issue. I am considering the older one and closing the PR related to this issue.

**Comment by namrata-jha** [comment]
Alright, I thought I'd claimed so I could do it, sorry for this.

**Comment by hridyakrishna** [comment]
Hello, Can I please work on this?

**Comment by Rimjhim28** [comment]
@hsymphonyk The issue is already solved and is not available anymore!
Nevertheless, you can work on other issues!
This is a link to one beginner friendly issue: https://github.com/systers/powerup-android/issues/1102
You can go ahead and solve any one of the errors.

**Comment by hridyakrishna** [comment]
@Rimjhim28 Okay. I did not know it. I will try other issues then.
