### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1102]
## Description
As a maintainer,
I need remove the lint errors in the code,
so that the overall code structure and app performance can be improved.

## Mocks
Not applicable

### Update 

The warnings/error that need to fixed are
- [ ] Android Resource Validation ( 8 errors )
- [ ] Extraneous text in resource file ( 1 waining )
- [ ] Missing commit() on SharedPreference editor ( 4 warnings )
- [ ] Wrong Resource Type ( 4 warnings )
- [ ] Hardcoded text ( 27 warnings )
- [ ] TextView Internationalization ( 18 warnings )
- [ ] Using left/right instead of start/end attributes ( 3 warnings )
- [ ] FrameLayout can be replaced with <merge> tag ( 5 warnings )
- [ ] Missing baselineAligned attribute ( 5 warnings )
- [ ] Obsolete layout params ( 5 warnings )
- [ ] Pointless boolean expression ( 4 warnings )
- [ ] Redundant local variable ( 4 warnings )
- [ ] Declaration can have final modifier ( 27 warnings )
- [ ] Method can be void ( 1 warning )
- [x] Redundant throws clause ( 22 warnings )
- [x] Unused import ( 40 warnings )
- [ ] 'if' replaceable with 'switch' ( 3 warnings )
- [x] Unused XML schema declaration ( 5 warnings )

**Note** : Only of the above listed items can be claimed and fixed by one contributor

## Definition of Done
- [ ] One of the required item is completed
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Rimjhim28** [comment]
Sure @krshma! You may choose *any one* of the listed items.
Comment here which warning you are taking up to fix.

**Comment by pprathameshmore** [comment]
Can I work on this? @Rimjhim28

**Comment by krshma** [comment]
@Rimjhim28 
Hi Rimjhim! I have fixed warnings for unused imports and hardcoded strings.
https://github.com/krshma/powerup-android/commit/2a3a73008e6aa12b7d1e552579b2e6c9ab9c62f8

**Comment by Rimjhim28** [comment]
@pprathameshmore As the label clearly specifies that the issue is intended for first time contributors, you cannot claim this since you already have PRs sent to the repository.
Also, you have sent a PR without approval and to fix the error that has already been claimed by @krshma 
Please folow instructions and contributing guidelines.

**Comment by pprathameshmore** [comment]
Oh! 👍

**Comment by smieras** [comment]
May I help with the task - Redundant throws clause @Rimjhim28 ?

**Comment by Rimjhim28** [comment]
Sure @smieras! Go ahead and send a PR

**Comment by RocknrolliRakacolli** [comment]
May I help with the task "Method Can be Void"?

**Comment by Rimjhim28** [comment]
Sure @RocknrolliRakacolli ! Go ahead and send a PR.

**Comment by namrata-jha** [comment]
Looks like this issue is still open, can I go ahead and work on this issue?

**Comment by hridyakrishna** [comment]
Hello, can I work on this?

**Comment by DamianNieves** [comment]
Would it be ok if I tried to fix the "Extraneous text in resource file error."

**Comment by Rimjhim28** [comment]
Sure @DamianNieves! Please go ahead and send a PR.
