### ISSUE TITLE
Audio for Button OnClick()

### ISSUE THREAD

**Issue by AjaySharvesh3** [systers/powerup-android#1108]
## Description
As a maintainer,
I need to add an audio for the button,
so that the app will more be entertained and looks great.
## Mocks
Not Applicable

### Update [Required]
- [ ] Adding audio files to raw folder
- [ ] Implementing the audio to the buttons onClick() method.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by AjaySharvesh3** [comment]
@m-murad @geekanamika @Rimjhim28 @MeepyMay Can you please give me the approval for this?

**Comment by geekanamika** [comment]
@AjaySharvesh3 It's not a bug fix. Let's discuss it in slack/open session?

**Comment by AjaySharvesh3** [comment]
@geekanamika Sure, let's discuss that.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
