### ISSUE TITLE
Change in Description of avatar in final_avatar.xml

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-android#1114]
## Description
As a user,
I need to get proper description of avatar when it is setup.In final_avatar message should be changed to 
"This is your avatar! Tap CONTINUE to start your journey." instead of This is your final avatar! Press continue to start your Journey...

## Acceptance Criteria
When the message is changed as mentioned above!

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by Rimjhim28** [comment]
@SIMRAN1 since this is not a "bug" and requires a change in ui discussing on slack first would be a better option.

**Comment by SIMRAN1** [comment]
Okk @Rimjhim28 I will discuss it on slack first!!

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
