### ISSUE TITLE
Create a Util file for reading CSV

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#1123]
## Description
As a developer,
I need a Util file which will read CSV and return corresponding List of objects,
so that I can use it during insertion of values in database.

### Update [Required]
- [ ] [CSVReader.java file]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
8 hours

**Comment by geekanamika** [comment]
@niksj @manishakeim Can you please assign this issue to me & add a gsoc label on it?

**Comment by m-murad** [comment]
@geekanamika 
when you use this file please make sure that this runs on a background thread just like the SQL queries.

**Comment by geekanamika** [comment]
I'll keep it in mind, Thank you :)
