### ISSUE TITLE
Including new scenarios

### ISSUE THREAD

**Issue by debanjanah** [systers/powerup-android#1124]
## Description
As a developer,
I need to set up the scenario map,
so that I can include new scenarios.

### Update [Required]
- [ ] scenario.csv
- [ ] question.csv
- [ ] answer.csv

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by Rimjhim28** [comment]
Solved through #1131
