### ISSUE TITLE
Show points and button to map after each scenario

### ISSUE THREAD

**Issue by AaskaShah** [systers/powerup-android#114]
As one scenario is completed, the second is started automatically without asking the user which scenario should be played next nor gives any information about the points earned in the scenario.

If this needs to be done ,Can I implement this such that at the end of the scenario,
1) A page displaying information about points opens, which has button which will lead to map.
or
2) a toast or dialog box displays points and opens map activity directly.

**Comment by chhavip** [comment]
@AaskaShah , hey, the given issue is already under implementation at #103.

**Comment by AaskaShah** [comment]
I apologize for it, should have checked before.I will surely check from next time onwards. Thanks for pointing it out.
