### ISSUE TITLE
Removal of non-functional code from StartActivity.java 

### ISSUE THREAD

**Issue by aayushinigam** [systers/powerup-android#1143]
## Description
As a developer,
my code should only contain the functional pieces
so that there are no unnecessary lines of code.

The onResume() method of StartActivity.java  contains code that would change the text of LoadGame button but it couldn't be changed since the layout has a fixed background image. 

## Mocks
![screenshot from 2018-05-21 16-57-00](https://user-images.githubusercontent.com/24635221/40305423-23409520-5d18-11e8-8425-c7fee6076706.png)
![screenshot from 2018-05-21 16-44-33](https://user-images.githubusercontent.com/24635221/40305481-58812d44-5d18-11e8-806d-9fa9577a73ec.png)
 

### Update [Required]
- [ ] Removal of lines 129-132

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 mins

**Comment by aayushinigam** [comment]
@systers/maintainers-powerup-android Could you please approve this issue?

**Comment by geekanamika** [comment]
Go ahead with it @aayushinigam :)
