### ISSUE TITLE
UI inconsistencies in Pre-Game setup, related to the PR - 1149

### ISSUE THREAD

**Issue by thisum** [systers/powerup-android#1156]
## Description
As a User,
I need to have consistent and intuitive navigation on the game UI,
so that I can navigate through the game screens easily.

## Mocks
![screenshot_2018-06-05-01-30-44](https://user-images.githubusercontent.com/1425395/40932487-1387f0b6-6861-11e8-848d-70abf19194a2.png)

### Update [Required]
- [ ] PreGameSetupInitialActivity.java
- [ ] Default selected avatar
- [ ] When taping on the same avatar twice, first change to the new avatar and green icon on the selected one, when tapping on the same avatar for the second time, either de-select and change to the default avatar or do not remove the "green icon" as the avatar is not changing

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by Rimjhim28** [comment]
The issue can be closed since the screens were updated
