### ISSUE TITLE
startActivityForResult() to startActivity()

### ISSUE THREAD

**Issue by medhach** [systers/powerup-android#117]
Why not use startActivity() instead of startActivityForResult( , ) in the .java files? According to me, it is more appropriate as we are not expecting any result back to the previous page and it is also more readable.

**Comment by imaculate** [comment]
@medhach I would like to work on this , has it been resolved.

**Comment by medhach** [comment]
@imaculate I am waiting for the mentors to let me know if I can proceed. :)
@chhavip Shall I pull a request regarding the same?

**Comment by chhavip** [comment]
@medhach Please give the exact reference where you intend to make these changes so that each can  be individually judged for need of change.

**Comment by medhach** [comment]
AvatarActivity.java - 
![selection_046](https://cloud.githubusercontent.com/assets/14357023/14314155/549bf1fe-fc13-11e5-8465-e0179a899da0.png)

AvatarRoomActivity.java - 


CompletedSceneActivity.java - 

GameActivity.java - 

MapActivity.java -

**Comment by riddhik84** [comment]
@chhavip @medhach Is this issue resolved? If not can you please assign it to me?

**Comment by chhavip** [comment]
@riddhik84 , this is not resolved, would you like to take it up?

**Comment by riddhik84** [comment]
@chhavip sure. Please assign it to me. I will fix it.

**Comment by chhavip** [comment]
@riddhik84  Sure, go ahead
