### ISSUE TITLE
Add labels to map items

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/powerup-android#118]
The map elements can have relevant labels such as School, house

![screenshot_2016-03-15-02-33-47_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13759935/a12dad42-ea56-11e5-9ae6-ba7e640e94ff.png)

![screenshot_2016-03-15-02-33-47_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13759995/e7d5673a-ea56-11e5-8690-49f1e84fc606.png)

**Comment by chhavip** [comment]
@AkankshaBodhankar A nice initiative but I find it lessens the feeling of this being a gameplay, using self explanatory images can be a better solution or making the places seem clickable/be highlighted properly

**Comment by AkankshaBodhankar** [comment]
@chhavip Yes thats a valid point. We can make them highlighted. It's just a design issue then
