### ISSUE TITLE
UI and alignment for few buttons

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/powerup-android#119]
UI for the two buttons map and store
Proper alignment for the buttons

![screenshot_2016-03-15-02-33-13_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/13760017/0ac51894-ea57-11e5-8e70-0a8f93c10395.png)

**Comment by chhavip** [comment]
@AkankshaBodhankar  Seems like a genuine issue. Needs to be fixed on all screen sizes supported.

**Comment by imaculate** [comment]
@AkankshaBodhankar @chhavip I would like to work on this.

**Comment by imaculate** [comment]
I'm thinking of aligning the text above as well as the buttons to center , Am I on the right track?

**Comment by imaculate** [comment]
It will look like this .
![centered](https://cloud.githubusercontent.com/assets/4919474/13870110/183dad1c-ece4-11e5-9cd6-3a16b2fdc237.PNG)

**Comment by AkankshaBodhankar** [comment]
@chhavip I'll make the required changes to the UI for buttons for all the screens. The design of the buttons will be similar to the buttons we already have. Aligning also will be done easily
@imaculate I have been waiting for a green flag to go ahead with this issue since a very long time.
I hope you dont mind. I would like to work on it.

**Comment by chhavip** [comment]
@AkankshaBodhankar You can go ahead, but make sure to fix this for all screen sizes in landscape and portrait mode.

**Comment by AkankshaBodhankar** [comment]
@chhavip Sure Will keep that in mind and procees

**Comment by shamathmika** [comment]
@chhavip Is this still up for grabs?
Or is there any other issue I could work on?

**Comment by chhavip** [comment]
@shamathmika , please go over the latest version of the application and check if you still feel some UI elements require alignment, if they do you can work on them and if not, you can report the same so this issue can be closed which will also be a good contribution to the project :)

**Comment by shamathmika** [comment]
@chhavip 
The activity mentioned in this issue hasn't been resolved yet. I made the changes, should I send a PR?

**Comment by chhavip** [comment]
yes, go ahead

**Comment by chhavip** [comment]
Fixed in GSoC 2016.
