### ISSUE TITLE
Add JUnit tests for end screen of mini game 2

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1195]
## Description
As a developer,
I need add initial JUnit tests for end screen of mini game 2 - Memory Match,
so that I can assure proper functionality of the same.

## Mocks
Not applicable

### Update 
- [ ] JUnit test file
- [ ] Initial java file for the activity

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by debanjanah** [comment]
PR merged
