### ISSUE TITLE
Adapt map layout buttons to tablet

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#12]
The game is currently optimized for phones. Therefore, the buttons for the different locations in the map are placed related to the phone layout.

Create a new map layout for horizontal displays (using qualifiers) so this works on tablets and phones in horizontal mode. Read more about screen qualifiers here: http://developer.android.com/intl/es/guide/practices/screens_support.html

**Comment by vasukiarunachalam** [comment]
I will take this task.

**Comment by vasukiarunachalam** [comment]
The landscape (horizontal) display of all the layouts (Map, AvatarRoom, Avatar etc ) needs to be created. The buttons on AvatarRoom are currently displayed left in landscape mode. As the issue specifies only Map, should I do only for Map or should I do it for all ?

**Comment by alma-castant** [comment]
Try to always do small tasks so it's easier to review and merge. I created a separate issue for the creator room, and I will check the rest of the screens on my tablet and create new issues if necessary. 
For now, work on the map only on one pull request, and once you are done with that you can take more similar tasks

**Comment by vasukiarunachalam** [comment]
Thank you, , sure I will finish the map layout and then work on other layouts.

**Comment by vasukiarunachalam** [comment]
I have committed the code. It involves addition of new map layout in layout-land folder in res. The button sizes was 100 dpi fixed definition, but in map the places like school, home etc is seen elongated horizontally. As of now I have let them be 100 dpi. I feel if buttons are of same size as places then there will be better User Interactivity. Please let me know your comments.

**Comment by alma-castant** [comment]
Hi @vasukiarunachalam I don't see any pull request with this task
Follow the README instructions if you are unsure about how to make a pull request ;)

**Comment by vasukiarunachalam** [comment]
5 days ago ,I followed and executed till step 9 in README. I assumed pull request should be done after review from others. Sorry about it. I have created a pull request. Please let me know if it is correct.

**Comment by vasukiarunachalam** [comment]
I have edited the layout file and committed it using "commit --amend".Please let me know if it is correct.
