### ISSUE TITLE
Improve test cases of KillTheVirusGame

### ISSUE THREAD

**Issue by thisum** [systers/powerup-android#1201]
## Description
As a tester,
I need to have test cases to check the functionality of the KillTheVirusGame,
so that I can make sure the logics are working correctly and will not fail.
Related to further developments of #1185 

### Update [Required]
- [ ] add test cases to check the functinality of the KillTheVirusGame
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by debanjanah** [comment]
PR merged
