### ISSUE TITLE
Double tap on any answer leads to end of scenario

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#1224]
## Description
As a User,
I need normal behaviour of the application in the last answer of scenario,
so that I can complete scenario with one single appropriate answer for GSoC18-infra branch.

## Mocks
https://drive.google.com/open?id=1x3ja0nCtgMZfq-Yw9LrXdqL-Nfp7owIA

## Acceptance Criteria
Reported issue is solved & *one correct* single answer completes the scenario.

### Update [Required]
- [ ] GameActivity
- [ ] ScenarioOverActivity

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
24 hours

**Comment by Rimjhim28** [comment]
Solved through #1292
