### ISSUE TITLE
Edit required images to have consistent font for all the buttons

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/powerup-android#123]
The font family of 'About' in about button is different than Start and New User 
Similarly the 'continue' button used in the app also has different font family

![screenshot_2016-03-28-00-19-45_powerup systers com powerup](https://cloud.githubusercontent.com/assets/14356938/14067147/1f027c06-f47b-11e5-8a93-5bcc151eb0ff.png)

**Comment by aanchal07** [comment]
@AkankshaBodhankar The "Start", "New User" and "About" are actually images which have been used as background for buttons in the activity_main.xml. So I would suggest we need to edit the images used on these buttons to display the same font.

**Comment by AkankshaBodhankar** [comment]
@aanchal07 Yes will do the same thanks for the suggestion! :-)

**Comment by shamathmika** [comment]
@AkankshaBodhankar is this done? Or can I work on it?

**Comment by AkankshaBodhankar** [comment]
@shamathmika Follow up with @aanchal07 and @chhavip for the same :-)

**Comment by saketkumar95** [comment]
Can i work on it?

**Comment by chhavip** [comment]
Fixed in GSoC 2016

**Comment by anubhakushwaha** [comment]
@chhavip Why was this issue closed? It' again referenced now in #258

**Comment by chhavip** [comment]
Might have missed it, or it got reverted back. Lets continue on that issue for now
