### ISSUE TITLE
Application crashes when going into the level 2

### ISSUE THREAD

**Issue by thisum** [systers/powerup-android#1256]
## Description
As a User
I need able to continue the game to the level 2,
so that I can continue to play.

## Mocks
![screenshot_2018-07-19-13-39-29](https://user-images.githubusercontent.com/1425395/42916466-75871ed4-8b59-11e8-88ff-4405c0f57848.png)

![screenshot_2018-07-19-13-39-34](https://user-images.githubusercontent.com/1425395/42916470-7a0a6c36-8b59-11e8-8d41-c1dbf3fd7c9f.png)

![screen shot 2018-07-19 at 1 36 32 pm](https://user-images.githubusercontent.com/1425395/42916471-7d40aad2-8b59-11e8-9697-e37a00966984.png)

When I'm trying to continue to the level 2 of the game after pressing "Map" button at the end of level 1, the game crashes.

## Acceptance Criteria
- [ ] when clicking the "Map" button at the end of level 1, the application should not be crashed
- [ ] "Map" button should take to the level 2

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Rimjhim28** [comment]
@thisum I am able to navigate to Level 2 successfully.

![videotogif_2018 07 19_17 16 24](https://user-images.githubusercontent.com/26908195/42940996-e456d592-8b78-11e8-833f-81c6cc1ca7e8.gif)

**Comment by thisum** [comment]
I couldn't reproduce the issue with the new updates, so closing the issue.
