### ISSUE TITLE
Replacing startActivityForResult() with startActivity()

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#127]
startActivityForResult() should be used when we are expecting some result back  as it waits for callbacks from the started activity. However, there are few places in the application where this has been used unnecessarily. I intent to replace these with a simple startActivity(). Eg
```java
private OnClickListener onClickListener = new OnClickListener() {
		@Override
		public void onClick(View v) {
			Button b = (Button) v;
			if (getmDbHandler().setSessionId(b.getText().toString())) {
				Intent myIntent = new Intent(MapActivity.this, GameActivity.class);
				startActivityForResult(myIntent, 0);
			} else {
				Intent myIntent = new Intent(MapActivity.this, CompletedSceneActivity.class);
				startActivityForResult(myIntent, 0);
			}
		}
	};
```

**Comment by medhach** [comment]
There is already an issue #117
I am working on it. :)

**Comment by yatna** [comment]
Thanks for reporting :-). Closing this issue .
