### ISSUE TITLE
Remove hardcoded integers and dimens

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#128]
Although, almost all the resources have been placed correctly in their respective places (integer.xml, dimen.xml , colors.xml) , there are few hardcoded integers and dimens still present in pgame.xml and simplerow.xml . I intend to remove these and remove the remaining hardcoding.

**Comment by chhavip** [comment]
@yatna  go ahead

**Comment by yatna** [comment]
PR sent #116

**Comment by chhavip** [comment]
@yatna I apologize but this issue will be covered under #134 and as you already have some contributions, its better that that be left as a beginner task and can be taken up by you (if you are still willing) after a considerable time has passed and no one picks it.
