### ISSUE TITLE
Add intro screens to the app

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#129]
Intro screens appear when the user installs the app and uses it for the first time. These screen guide the user through the app and give details about the features of the application. I intend to create intro screens using the PaoloRotolo AppIntro library which is a widely used library to create intro screens.

**Comment by chhavip** [comment]
@yatna Thank you for reporting but this is an ongoing issue with discussion underway to its implementation and requirements #122 . Perhaps this thread can be used to refer to the PRs made for the same.

**Comment by yatna** [comment]
@chhavip Sure, we can use #122 for Splash Screen and this one for Intro Screens discussions.

**Comment by chhavip** [comment]
@yatna As mentioned on the #122 thread itself, for now Splash Screen is not required. Introduction screens are being considered and this can be the thread for the same.

**Comment by chhavip** [comment]
As mentioned on the thread itself, splash screen is not needed for now and for introduction screens #31 will be used for discussion.
