### ISSUE TITLE
Save The Blood mini game is never marked as complete

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1295]
## Description
As a developer,
I need to handle error with the mini game - Save the blood,
so that the mini game is marked complete once it is played.
Currently, the mini-game is not marked complete. Due to this when the game is completed and another scenario is chosen, the game launches again.

## Mocks
Steps to reproduce:
1. Complete the mini game
2. Go to scenario over screen
3. Click Map to launch map for level 2
4. Click on any scenario
5. The mini game launches again though it was completed

### Update
- [ ] Mark the mini game as completed in Session Manager

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by thisum** [comment]
closed by the PR #1296
