### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#130]
This should contain a basic document containing the correct files needed in .gitignore of an AndroidStudio project. This will make it easier to avoid getting the wrong files committed to the project.

**Comment by yatna** [comment]
@chhavip PR sent #131

**Comment by aanchal07** [comment]
@chhavip : I would like to do it.

**Comment by yatna** [comment]
@chhavip Sorry, I did not notice a .gitignore was already present. I have modified the existing .gitignore file to match a standard version of .gitignore. #133
