### ISSUE TITLE
Make the app full screen.

### ISSUE THREAD

**Issue by moksh-mahajan** [systers/powerup-android#1327]
## Description
The introductory screen of the app shows the status bar as well. My idea is to make the app should be a full screen app like most of the landscape oriented games are. This will improve the UI to some extent.

## Mocks
Present state of the app
![screenshot_2019-01-25-21-44-05-960_powerup systers com powerup](https://user-images.githubusercontent.com/36201975/51758739-6d526d80-20ec-11e9-8b9e-e13ea880598d.png)

### Update [Required]
- [ ] Make the introductory screen full as well

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by honeycoder96** [comment]
can I work on this issue?

the theme attribute is actually redundant in the manifest file and can be removed and the estimated time is 2 min, not 2 hours.

**Comment by Rimjhim28** [comment]
@moksh-mahajan While the issue is valid, there are several screens that can be converted to full screen mode. Coud you please list all the screens on the issue itself first?

**Comment by Rimjhim28** [comment]
@honeycoder96 I am not sure if @moksh-mahajan would like to work on the issue itself or pass it on to some other contributor. 
@moksh-mahajan Are you fine with @honeycoder96 working on the issue and sending a pull request or would you like to fix this by yourself?

**Comment by honeycoder96** [comment]
> @moksh-mahajan While the issue is valid, there are several screens that can be converted to full screen mode. Coud you please list all the screens on the issue itself first?

I think we can configure the base theme attribute in parent **application** tag to full screen all the activities and I will wait for @moksh-mahajan before submitting a pr.

**Comment by moksh-mahajan** [comment]
@honeycoder96 sure go for it. By the way, I'm experiencing this problem on Poco F1.

**Comment by honeycoder96** [comment]
> @honeycoder96 sure go for it. By the way, I'm experiencing this problem on Poco F1.

Ok i am working on it @Rimjhim28
