### ISSUE TITLE
Update the compile and target SDK version.

### ISSUE THREAD

**Issue by moksh-mahajan** [systers/powerup-android#1335]
## Description
The compileSdkVersion and targetSdkVersion which are set to versions 27 and 27, respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features.

### Update [Required]
- [ ] Update the project level gradle file.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Rimjhim28** [comment]
@moksh-mahajan This sounds resonable.
Go ahead and send a PR. Be sure that you are not affecting the project's build.
