### ISSUE TITLE
Place `google()` repository as the first priority repository

### ISSUE THREAD

**Issue by moksh-mahajan** [systers/powerup-android#1336]
## Description
In build. gradle file jcenter() repository have first priority than google() repository. My idea is to Place google() repository as the first priority repository to avoid such errors like:
**Failed to resolve: multidex-instrumentation**
Here is a[ link](https://stackoverflow.com/questions/45608362/android-studio-3-0-beta-1-failed-to-resolve-com-android-supportmultidex1-0-2) to check to solve this error.

### Update [Required]
- [ ] Update the project level build.gradle file and place google() above jcenter().

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Rimjhim28** [comment]
@moksh-mahajan This sounds resonable.
Go ahead and send a PR. Be sure that you are not affecting the project's build.
