### ISSUE TITLE
Code CleanUp

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#134]
This includes removing unused imports, removing hard coded string and integers and adhering to Java naming conventions (if needed). A thorough review of the current code is required for this task.

**Comment by yatna** [comment]
@chhavip This is a nice initiative. It will help new contributers to get started. I will try to find more such  issues and add them under this issue.

**Comment by riddhik84** [comment]
I agree. I would like to start contributing on the beginner issues.

**Comment by riddhik84** [comment]
@chhavip @yatna as a solution of this issue, I have generated pull request and removed hard-coded dimens from layout files.

**Comment by chhavip** [comment]
Great! Will review shortly

**Comment by goti921** [comment]
Hi @chhavip 
Is it still up for grabs or has the issue been resolved ?

**Comment by chhavip** [comment]
@goti921 , this issue is still unresolved, @riddhik84 , will you be fixing the PR you sent or can @goti921 work on this?

**Comment by riddhik84** [comment]
@chhavip I will fix the PR

**Comment by goti921** [comment]
@chhavip 
Should I take that as a No ?

**Comment by chhavip** [comment]
@goti921 , for now we will wait for @riddhik84 to fix the PR, in the meantime you are welcome to look at other beginner issues I recently added to the project.

**Comment by top-gun007** [comment]
is this still an issue?

**Comment by chhavip** [comment]
Yes

**Comment by top-gun007** [comment]
can I work on it then?

**Comment by top-gun007** [comment]
@chhavip can I start working on it.
_Thank you_

**Comment by shreab373** [comment]
@chhavip i would like to work on this too

**Comment by chhavip** [comment]
@top-gun007 are you working on this?

**Comment by top-gun007** [comment]
yes I would gladly do it will send a PR soon.
One more thing I wanted to know if I have a suggestion for this project should I discuss it on slack or I can directly open an issue for it.
Thank you

**Comment by shreab373** [comment]
@chhavip i'll find another :)

**Comment by chhavip** [comment]
You can discuss on #powerup channel on slack @top-gun007

**Comment by mahikaw** [comment]
@chhavip @aanchal07 Can I send a PR with few fixes?

**Comment by aanchal07** [comment]
@mahikaw Yes go ahead.

**Comment by chhavip** [comment]
@mahikaw and @aanchal07, this was fixed for now with #240 which has been merged. We do not need to work on this for now. Closing this issue till a large amount of code needs to refractored.

**Comment by mahikaw** [comment]
@chhavip Perhaps, the earlier PR didn't clean a lot of things as there are still same drawables under diff. names, unused strings, dimensions and so on.
I would like to go ahead with a PR if that's okay as I had already cleaned up to a significant amount. :)

**Comment by chhavip** [comment]
If you wish to send the PR, please go ahead, will check the significance of it before merging.

**Comment by top-gun007** [comment]
@mahikaw sorry for replying late I didn't delete unused strings and dimensions as it is not recommended as they might be used in future especially in projects like this which is still undergoing improvements.

**Comment by mahikaw** [comment]
@top-gun007 , I think it will be impractical for any contributor to first search for strings and dimension that they want to add, if they exist.

**Comment by mahikaw** [comment]
@chhavip okay. I am sending a PR please review it. Thanks :)
