### ISSUE TITLE
Make Room Database annotations simpler.

### ISSUE THREAD

**Issue by moksh-mahajan** [systers/powerup-android#1340]
## Description
In many entity files like Answer.java, Avatar.java, Clothes.java etc., the name of the class and table name are the same, therefore, there is no need to mention the table_name attribute in the @entity Room annotation of these model classes, as Room by default, makes the SQLite table of the same name as the name of the entity class. My idea is to make these annotations simpler.

## Mocks
_Before change_: @Entity(tableName = "Answer")
                                public class Answer {...}
_After change_: @Entity
                               public class Answer {...}

### Update [Required]
- [x] Make all @entity annotations simpler, wherever possible. 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by moksh-mahajan** [comment]
@Rimjhim28 @geekanamika Can I submit a PR for the same?

**Comment by hridyakrishna** [comment]
Hello, May I work on this?

**Comment by geekanamika** [comment]
Looks like a valid issue to me. @moksh-mahajan Go ahead if you don't have any pending/claimed issue at the moment. 
@hsymphonyk Hey, Moksh claimed the issue first, so I have assigned it to him. If he doesn't respond back in the next few days, I'll assign it to you. Thanks.

**Comment by moksh-mahajan** [comment]
@geekanamika I claim working on this issue.

**Comment by moksh-mahajan** [comment]
@geekanamika Done. Please review.
