### ISSUE TITLE
Sink to Swim game ends within 5 entries of answers.

### ISSUE THREAD

**Issue by hridyakrishna** [systers/powerup-android#1341]
## Description
Sink To Swim game does not wait for the countdown to end, rather finishes the level once five choices are fed.

### Update [Required]
-Game must give chances until the countdown ends and add points accordingly.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
48 hours

**Comment by hridyakrishna** [comment]
May I please work on this issue?

**Comment by hsymphonyk** [comment]
May I please work on this issue?

**Comment by Rimjhim28** [comment]
@hsymphonyk this is only because the number of questions in the game is five. 
I am closing the issue since it is not valid.
