### ISSUE TITLE
Animation should me shown when back button is pressed in the game map screen.

### ISSUE THREAD

**Issue by moksh-mahajan** [systers/powerup-android#1348]
## Description
In the game map screen, when a building is clicked, then a nice animation effect is shown when the screen changes from map to conversation scenario. Also when the user goes back to map screen from any conversation screen using the home button (on the top right corner), then also the animation effect is shown. 
But when the **back button** is pressed, this animation effect is not shown. My idea is to add this animation effect when the back button is pressed too.
## Mocks
![20190224_172301](https://user-images.githubusercontent.com/36201975/53298919-2a55f800-385a-11e9-896a-cd67907c994c.gif)

### Update [Required]
- [x] Add the animation effect when back button is pressed.

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by moksh-mahajan** [comment]
I would like to work on this issue. @Rimjhim28 @geekanamika

**Comment by Rimjhim28** [comment]
This looks valid. 
@moksh-mahajan You can send a PR for this.

**Comment by moksh-mahajan** [comment]
@Rimjhim28 sending a PR soon.

**Comment by moksh-mahajan** [comment]
@Rimjhim28 Done. Please review.

**Comment by pknotfound** [comment]
@Rimjhim28 May I work on this issue?

**Comment by pknotfound** [comment]
@sunjunkie May I work on this issue?

**Comment by Priyansh-Kedia** [comment]
https://github.com/anitab-org/powerup-android/pull/1362#issue-380337342 
Please review this PR

**Comment by pknotfound** [comment]
@sidvenu 
May I work on this?

**Comment by sidvenu** [comment]
Hey Priyansh!
I'm not a maintainer for this project.

**Comment by pknotfound** [comment]
@sidvenu 
Could you please tell me the maintainers for the same?
Thanks.
