### ISSUE TITLE
Adding DB tests

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#135]
Currently, the application has no tests. This problem has been earlier addressed in issue #85 which led to the creation of UI tests. As mentioned in the issue itself , PRs were sent only for the UI testing of the application. Database tests are still to be created.  I intend to create these tests using JUnit.

**Comment by yatna** [comment]
@chhavip I think we can add this issue to the 'open' issue category as well. Although its not the easiest issue for beginners to start with, yet, I think someone might be interested. If not I will take up the issue later.

**Comment by riddhik84** [comment]
@chhavip @yatna I am interested to work on this task? Could you please assign it to me?

**Comment by chhavip** [comment]
@riddhik84, this is a task you can do the task but currently the database is under transition as new fields are getting added, I would advise you to please wait till that is complete.

**Comment by riddhik84** [comment]
@chhavip sure. Thanks for reply. By that time if required i can contribute to any other task.
