### ISSUE TITLE
Code Cleanup 

### ISSUE THREAD

**Issue by aanchal07** [systers/powerup-android#136]
I was going through the code and I found some changes that could be done to clean up the code. I am listing them below:

1. **CreatorRoomActivity** has never been used. It should be removed.

2. In **pgame.xml**, _scenarioNameEditText_ and  _questionView_ has ems attribute value hard coded integer.

3. In **simple.xml**, _rowTextView_ has padding attribute value hard coded integer.

4. The drawables : _buttonbg.png,  cellphone_power_up_map.png,  character_design.png,  character_design2.png, clothes.png,  clothing_room.png,  clothing_room1.png,  clothing_room2.png,  clothing_room3.png,  clothing_room4.png,  clothing_room5.png,  clothing_room6.png,  clothing_room7.png,  clothing_room_all.png,  endingscreen.png, endingscreen1.png,  endingscreen2.png,  endingscreen3.png,  endingscreen4.png,  endingscreen5.png,  endingscreen8.png,  endingscreen9.png,  hair.png,  marco_eyes_mouth.jpg,  marco_head.jpg_ are not used anywhere but are still included in the package. These should be removed as they do take up a lot of space.

**Comment by chhavip** [comment]
@aanchal07 , go ahead, but keep in mind that removing any resource does not break the compilation.
