### ISSUE TITLE
Low resolution hair

### ISSUE THREAD

**Issue by 7phalange7** [systers/powerup-android#1365]
## Description
The hairs of the Avatar Standout as they are blurred/ their image is of low resolution.

## Screenshots

![Screenshot (138)](https://user-images.githubusercontent.com/54908857/75684443-d24c9f80-5cbe-11ea-877a-e0485f5bccf6.png)
![Screenshot (139)](https://user-images.githubusercontent.com/54908857/75684469-dc6e9e00-5cbe-11ea-997b-c642015996da.png)

### Update [Required]
- [ ] Add better resolution images without increasing the file size too much.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by 7phalange7** [comment]
I would like to work on this issue

**Comment by pknotfound** [comment]
May I work on this issue?

**Comment by Mehulipal** [comment]
May I work on this issue?

**Comment by isabelcosta** [comment]
@7phalange7 consider it assigned to you.
