### ISSUE TITLE
App crashes on backpressed from MemoryMatchGameActivity

### ISSUE THREAD

**Issue by pknotfound** [systers/powerup-android#1370]
## Description
When back is pressed on MemoryMatchGame after the hospital, the app crashes.

## Mocks
![WhatsApp Video 2020-03-04 at 7 17 48 PM](https://user-images.githubusercontent.com/52661249/75887696-30f55300-5e50-11ea-9685-a12e6a8dcb1c.gif)

### Update [Required]
The app should not crash on back pressed, but should go to the previous activity.

**Comment by pknotfound** [comment]
@mayburgos May I work on this issue?

**Comment by sammy1997** [comment]
@Priyansh-Kedia Can you share the crash log? Use this https://justpaste.it/ to paste the log! I have to check if this is something device-specific or a generic error?

**Comment by pknotfound** [comment]
[5kzg2-justpasteit.pdf](https://github.com/anitab-org/powerup-android/files/4288318/5kzg2-justpasteit.pdf)

@sammy1997 Here is the crash report.

**Comment by sammy1997** [comment]
Ok. Seems like some kind of out of bound exception in MemoryMatchGameActivity. Seems like a valid issue! @Rimjhim28 @geekanamika ?

**Comment by sunjunkie** [comment]
I don't see a back button. Is that part of the Android OS? At any rate, why is there a back button on the Memory match game? Is is supposed to be a "replay" of the game?

**Comment by pknotfound** [comment]
There is no back button as such. It is when you push back from the phone swipe up.

**Comment by sunjunkie** [comment]
OK. The game shouldn't crash no matter what so this seems like a valid issue.

**Comment by pknotfound** [comment]
May I send a PR then?

**Comment by sunjunkie** [comment]
Yes, go ahead. (However, I can't review it. Someone else will have to.)

**Comment by pknotfound** [comment]
Thanks. Will send a PR soon.

**Comment by pknotfound** [comment]
This is the PR for the issue https://github.com/anitab-org/powerup-android/pull/1371#issue-383756297

Please review.
Thanks.
