### ISSUE TITLE
Add Contact section on README

### ISSUE THREAD

**Issue by isabelcosta** [systers/powerup-android#1377]
## Description

As a contributor,
I need to know where I can reach out to the community,
so that I can discuss or see discussions of this project.

I would suggest adding a section such as "Contact us" or "How to reach us" to the README.
An example is what is on [mentorship-backend README](https://github.com/anitab-org/mentorship-backend/).

### Update [Required]
- [ ] Add contact section with AnitaB.org Open Source Zulip link and #powerup stream link. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Mehulipal** [comment]
Can I work on this issue?

**Comment by 7phalange7** [comment]
I would like to work on this issue

**Comment by rohitg00** [comment]
I want to work on this issue.

**Comment by AneshkaGoyal** [comment]
Hey @isabelcosta ...I would like to work on this issue

**Comment by devanshi7799** [comment]
@isabelcosta i would like to work on this issue

**Comment by faiz276482** [comment]
@isabelcosta  please check my pull request. I have made the necessary changes as mentioned by you in the issue Description.

**Comment by isabelcosta** [comment]
@Mehulipal you can work on this :) Please send a PR for this issue.
