### ISSUE TITLE
Improve font in the about page 

### ISSUE THREAD

**Issue by HashemAlhariry** [systers/powerup-android#1384]
## Description
As a user i need a bigger font to so that i can understand what is written ,
I need to update the text style and text size,

## Mocks
![first](https://user-images.githubusercontent.com/45319166/76263448-976edc80-6267-11ea-86ba-0cdfe0f592bd.PNG)

**Comment by devanshi7799** [comment]
If approved and available i would like to work on it

**Comment by HashemAlhariry** [comment]
@devanshi7799 i'm waiting for approval to work on it
