### ISSUE TITLE
Adding option in app to rate app

### ISSUE THREAD

**Issue by aditmehta9** [systers/powerup-android#1387]
## Description
As a user, I need to rate app functionality from app, so that I can rate app.

## Mocks
![image](https://user-images.githubusercontent.com/35133994/76549605-c0d17780-64b6-11ea-9518-6a5c74c528e3.png)

### Update [Required]
- [ ] Adding option to rate app which leads to playstore

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by aditmehta9** [comment]
@sunjunkie @isabelcosta @mayburgos @Rimjhim28 Please look after the issue. Can I work on this issue?

**Comment by sammy1997** [comment]
Again, I don't think the app is on play store. So app ratings don't make sense. Closing this one for the moment!

**Comment by aditmehta9** [comment]
@sammy1997 Sir, here is the link https://play.google.com/store/apps/details?id=powerup.zealtech.com.powerup&hl=en it is in playstore maybe not officially uploaded by AnitaB.org.

**Comment by sammy1997** [comment]
Closing this, as the app isn't official
