### ISSUE TITLE
Adding option to share app download link to friends

### ISSUE THREAD

**Issue by aditmehta9** [systers/powerup-android#1388]
## Description
As a user, I need the option to share the app link through the app, so that I can share the app.

## Mocks
![image](https://user-images.githubusercontent.com/35133994/76550327-f9be1c00-64b7-11ea-8711-232e1bc70d40.png)

### Update [Required]
- [ ] Addition of option in app after splash activity to share app.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by aditmehta9** [comment]
@sunjunkie @isabelcosta @mayburgos @Rimjhim28 Please look after the issue. Can I work on this issue?

**Comment by justdvnsh** [comment]
Hi , I've created a pull request to this issue . Pull request #1412. Please look into it. Thanks.

**Comment by aditmehta9** [comment]
> 
> 
> Hi , I've created a pull request to this issue . Pull request #1412. Please look into it. Thanks.

Hey, Divyansh I have been waiting to be assigned by mentors for this issue. In many issues, students are asking to get assigned by a mentor. You have to first ask mentor to work on that issue. See in issue I have asked. Please follow the contribution guidelines.

**Comment by sammy1997** [comment]
Hey Adit. I don't think the app is there on Playstore. I am not sure how this app is distributed at the moment. What exactly do you want to share as a download link? The debug apk? I don't think that's a good idea

**Comment by aditmehta9** [comment]
> 
> 
> Hey Adit. I don't think the app is there on Playstore. I am not sure how this app is distributed at the moment. What exactly do you want to share as a download link? The debug apk? I don't think that's a good idea

Sir. I wanted to share the link of the PlayStore of this app to download Here is the link https://play.google.com/store/apps/details?id=powerup.zealtech.com.powerup&hl=en it is in playstore maybe not officially uploaded by AnitaB.org. So maybe this issue can be kept for later when it officially uploaded.

**Comment by sammy1997** [comment]
Closing this. App not official
