### ISSUE TITLE
Enhancement of Library Scene

### ISSUE THREAD

**Issue by Mehulipal** [systers/powerup-android#1396]
## Description
As a user,
I need to have:
1. 'LIBRARY' written clearly in the library scenario game
2. The 'avatar to the right' should be placed properly 'behind the table'
so that I can have better experience of library scenario game.

## Mocks
![library](https://user-images.githubusercontent.com/54908756/76699681-f2745980-66d5-11ea-9ec8-eb9242d9eb05.jpg)

### Update [Required]
- [ ] 'LIBRARY' text should be made properly visible
- [ ] The 'avatar to the right' should be placed properly 'behind the table'

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 2 hours

**Comment by Mehulipal** [comment]
@isabelcosta @sunjunkie @mayburgos May I work on this issue?

**Comment by nandini45** [comment]
can i work on this issue?

**Comment by Mehulipal** [comment]
@nandini45 I am already waiting for approval.

**Comment by Mehulipal** [comment]
@sammy1997 May I work on this issue?

**Comment by sammy1997** [comment]
Closing this as there is a similar issue assigned to @aditmehta9
