### ISSUE TITLE
Adding button press effect to Replay Button

### ISSUE THREAD

**Issue by Mehulipal** [systers/powerup-android#1397]
## Description
As a user,
I need to have the button press effect on pressing the replay button,
so that I can have better experience of using the application.

## Mocks

![Replay](https://user-images.githubusercontent.com/54908756/76700580-efca3200-66de-11ea-8540-a5e41c619153.gif)

### Update [Required]
- [ ] Add button press effect to Replay Button

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Mehulipal** [comment]
@isabelcosta @sunjunkie @mayburgos May I work on this issue?

**Comment by Mehulipal** [comment]
@sammy1997 May I work on this issue?

**Comment by sammy1997** [comment]
Please add this to #1392 as it is quite similar. Don't need a separate issue for this. Closing this
