### ISSUE TITLE
Adding button press effect to Map Button

### ISSUE THREAD

**Issue by Mehulipal** [systers/powerup-android#1398]
## Description
As a user,
I need to have the button press effect on pressing the map button,
so that I can have better experience of using the application.

## Mocks

![Map](https://user-images.githubusercontent.com/54908756/76700671-d4abf200-66df-11ea-8376-51a015f322ef.gif)

### Update [Required]
- [ ] Add button press effect to Map Button

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Mehulipal** [comment]
@isabelcosta @sunjunkie @mayburgos May I work on this issue?

**Comment by Mehulipal** [comment]
@sammy1997 May I work on this issue?

**Comment by sammy1997** [comment]
Please merge this with #1392 . You can rename that issue as "Adding button click effects on buttons of Home Scenario ending"

**Comment by sammy1997** [comment]
Closing this
