### ISSUE TITLE
Remove references to Systers on generate-apks.sh script

### ISSUE THREAD

**Issue by isabelcosta** [systers/powerup-android#1399]
## Description

apk is not being generated for the app. I suspect this is because the travis slug has not changed to anitab.org yet on `generate-apks.sh` script.

With so many commits to `develop` branch in the past months, I found it strange that the last apk was generated 13 months ago.

Not sure if this would fix it, but it still has to be changed.

### Update [Required]
- [ ] Change references to systers on script to generate APKs

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by Mehulipal** [comment]
@isabelcosta May I work on this issue?

**Comment by therealsanjeev** [comment]
@isabelcosta ma'am could do this issue, I'm very excited about my first contribution in open source.
if want this would be my first contribution ma'am :)

**Comment by isabelcosta** [comment]
@Mehulipal I see you committed before to this repository and this issue is for first timers contributors to it. So could you please select other issue?

**Comment by 7phalange7** [comment]
@isabelcosta  May I work on this issue?

**Comment by Mehulipal** [comment]
Sure, Ma'am. Thank you so much for your response.

**Comment by Mehulipal** [comment]
@isabelcosta @sunjunkie 
I have commented on many open issues with no PRs to them. Could you please check and give me a response in them. Thanks.

**Comment by isabelcosta** [comment]
@7phalange7 sure :) I will assign this to you.

**Comment by isabelcosta** [comment]
@Mehulipal this GSoC season everyone is commenting everywhere, so it is a bit hard keeping up with everything. So we may take some time to respond to everyone.
I think you are interested in applying to GSoC, right? If thats the case, can you please focus on your proposal? We do not require you to submit PRs and solve issues as part of your application. So if you could focus on that instead of the issues that would be a gerat thing to do for you, and thus giving us some time to respond to you once we have time :)

**Comment by Mehulipal** [comment]
@isabelcosta  Thank you so much for your response. I will keep your words in mind and will certainly follow them. Thanks again :)
