### ISSUE TITLE
Add an "About" screen

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#14]
Add an "About" screen with information about the game, its goal, its creators and how it was implemented (as a Systers' Open Source project) along with other information you think is useful.

The screen could be implemented as an Activity or as a dialog.
You can check PowerUp Handout for reference: https://github.com/systers/powerup-android/blob/master/PowerUp%20Handout.pdf

**Comment by medhach** [comment]
I will work on this.

**Comment by alma-castant** [comment]
@medhach will you work on this issue? This is different from the welcome screen you have been implementing

**Comment by medhach** [comment]
I am working on it. Will pull a request soon.

**Comment by rohansood42** [comment]
@chhavip Could i work on this if it has not been completed?

**Comment by MKDEVELOPEMENT** [comment]
can I get this please

**Comment by abs51295** [comment]
@chhavip I would like to work on this issue! Thanks!

**Comment by codingblazer** [comment]
Hey @abs51295 , this issue has already been solved. The about was implemented by a gci student and intro screens by me. :-)

**Comment by abs51295** [comment]
Thank you @codingblazer. I would look for some issues. Are there any specific issues you would like to point?
