### ISSUE TITLE
Adding Counting Animation to final Score of game

### ISSUE THREAD

**Issue by Mehulipal** [systers/powerup-android#1403]
## Description
As a user,
I need to see animation while viewing my final score,
so that I can have better experience of visualizing game end results.

### Before
![someb](https://user-images.githubusercontent.com/54908756/76712566-25ebce00-6740-11ea-8913-e450fc26bcef.gif)

### After
![somea](https://user-images.githubusercontent.com/54908756/76712585-49167d80-6740-11ea-878d-d30b0994434b.gif)

### Update [Required]
- [ ] Counting Animation to be added to final score of game 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Mehulipal** [comment]
@isabelcosta @sunjunkie @mayburgos @Rimjhim28 May I work on this issue?

**Comment by Mehulipal** [comment]
@sammy1997 May I work on this issue?

**Comment by sammy1997** [comment]
I don't see the necessity of this. Don't think this is a valid issue or enhancement closing this. You need to be able to see the score, just adding animation doesn't make it better UX. If you can show me some UX research, I may reopen this
