### ISSUE TITLE
Enhancement of Hospital Scene in Level 2

### ISSUE THREAD

**Issue by aditmehta9** [systers/powerup-android#1407]
## Description
As a user, I need The 'avatar to the right' should be placed properly 'on the floor' so that I can have a better experience of hospital scenario game,
so that I can experience good UI.

## Mocks
![image](https://user-images.githubusercontent.com/35133994/76728625-44bc8580-677d-11ea-905e-b1e504d640aa.png)

### Update [Required]
- [ ] The 'avatar to the right' should be placed properly 'on the floor'.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by aditmehta9** [comment]
@isabelcosta @sunjunkie @mayburgos May I work on this issue?

**Comment by sammy1997** [comment]
I am closing this issue. Please edit #1406 and add this change to it as these changes are mostly similar!!

**Comment by aditmehta9** [comment]
Ok sir.
