### ISSUE TITLE
Bug in using accessories after purchasing

### ISSUE THREAD

**Issue by aditmehta9** [systers/powerup-android#1408]
## Description
As a user,
I need to see the accessories while playing scenario so that I can experience good UI and have to purpose for purchasing accessories.

## Mocks
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/35133994/76728908-eb088b00-677d-11ea-80f8-4ed24afb539c.gif)

### Update [Required]
- [ ] Update in the character UI while playing scenarios so that purchased items can be used in playing scenarios.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by aditmehta9** [comment]
@isabelcosta @sunjunkie @mayburgos May I work on this issue?

**Comment by sammy1997** [comment]
Approving this and making this available

**Comment by HaripriyaB** [comment]
Can I work on this?Coz I m not assigned any yet! @sammy1997  @mayburgos @sunjunkie

**Comment by sammy1997** [comment]
Yeah, go ahead @HaripriyaB . Assigning this to you
