### ISSUE TITLE
Add image resources in standard Android sizes

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#141]
This would include including resources in mdpi, ldpi, xdpi, xxdpi and whatever are suitable.

**Comment by riddhik84** [comment]
Since all the images in drawable folder with only one size is available.  @chhavip You mean to make copies of those image files for mdpi, ldpi, xdpi, xxdpi folders correct?

**Comment by chhavip** [comment]
Not only make copies, but make resized copies, there are tools available for that online. Go ahead if you want to take up the task.

**Comment by riddhik84** [comment]
@chhavip yes exactly that is what I mean. I am taking up this task.

**Comment by chhavip** [comment]
Closing for now as requires further discussion.
