### ISSUE TITLE
Enhancing User Experience in AvatarRoomActivity

### ISSUE THREAD

**Issue by pknotfound** [systers/powerup-android#1413]
## Description
The current avatar room does not show button clicks.
This would be helpful in enhancing user experience.

## Before
![WhatsApp Video 2020-03-24 at 4 21 51 PM](https://user-images.githubusercontent.com/52661249/77417957-31985e00-6dec-11ea-8c0b-0a723a6e468c.gif)

## After
![WhatsApp Video 2020-03-24 at 4 19 00 PM](https://user-images.githubusercontent.com/52661249/77417730-cd759a00-6deb-11ea-91c0-cc8591359355.gif)

**Comment by pknotfound** [comment]
@m-murad @mayburgos 
May I work on this issue?

**Comment by devanshi7799** [comment]
I would also like to work on this if approved

**Comment by pknotfound** [comment]
Hey @devanshi7799 
I am actually waiting for approval on this issue.

**Comment by sammy1997** [comment]
It looks like a good enhancement. Approving and assigning it to you @Priyansh-Kedia
