### ISSUE TITLE
Consistency of Wiki Sidebar across Android and iOS repositories

### ISSUE THREAD

**Issue by sidvenu** [systers/powerup-android#1415]
## Description
As a contributor,
I need a consistent wiki sidebar across Android and iOS repositories
so that I can get acquainted with the project easily.

## Acceptance Criteria
Update the Android wiki sidebar to a commonly agreed layout

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by pknotfound** [comment]
@sidvenu 
Will you be working on this issue for Android?

**Comment by sidvenu** [comment]
Priyansh, before that maintainers will need to approve this issue, and we will need to discuss about a common layout on Zulip before anyone starts to make changes.

**Comment by pknotfound** [comment]
@sidvenu 
Yes, I am aware about that.
I would also work on this with you as I think that it is a necessary thing to be done.
Thanks

**Comment by sidvenu** [comment]
Awesome! Let's have the discussion in Zulip.

**Comment by sidvenu** [comment]
Closing this issue as sidebar already follows [this](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit) template.
