### ISSUE TITLE
Error in Create table query for Point and Avatar tables

### ISSUE THREAD

**Issue by riddhik84** [systers/powerup-android#157]
In AbstractDbAdapter.java file, there are errors in Create table query for Point and Avatar tables.
The tables are therefor not created with all required columns.

**Comment by chhavip** [comment]
Hey, nice catch! But this was a known issue and our Gsoc student was working on it which should be fixed after the latest merge. But I really appreciate you going through the investigation of finding this. To save you the effort of writing code and not having it merged from next time, I advise you to propose an issue and wait for a sign off from one of the mentors to go ahead with the coding. Good work!

**Comment by riddhik84** [comment]
@chhavip No problem. Thanks for info!
