### ISSUE TITLE
Move initialisation of Power Bars to Util Class

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#159]
Currently the power bars being displayed at the bottom of the screen are initialized in every screen they are required, leading to repetitive code. This can be moved to a Util class which uses resources from individual activity

**Comment by aanchal07** [comment]
@chhavip I would like to work on it.

**Comment by chhavip** [comment]
@aanchal07 , go ahead!

**Comment by top-gun007** [comment]
I am interested in correcting this can I proceed if no one is working on it.
Thank you

**Comment by aanchal07** [comment]
@top-gun007 you can work on it if you still intend to.
Sorry for the late reply.

**Comment by aanchal07** [comment]
The work for this can be included in #263
