### ISSUE TITLE
Add New User Functionality

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#160]
Currently on selecting the "New User" option does not create a new user if one already exists for the game and continues the game from the same point. Modify this to restart game on a new user selection.

**Comment by goti921** [comment]
@chhavip 
I would like to pick it up.

**Comment by chhavip** [comment]
@goti921 go ahead!

**Comment by anubhakushwaha** [comment]
@goti921 Still working on it?

**Comment by chhavip** [comment]
A response or a PR should be submitted within a week of claiming an issue. @goti921, please clarify your status.

**Comment by goti921** [comment]
@chhavip 
I am working on it. But having trouble running the application in the emulator.
Any help on this is appreciated.

**Comment by anubhakushwaha** [comment]
@goti921 Can you please specify your problem so that anyone can help you,what is exactly happening when you are trying to build the project and run it on an emulator/device?

**Comment by chhavip** [comment]
Sure @goti921, ask away

**Comment by anubhakushwaha** [comment]
@chhavip Please review #162 and let me know if it's okay.

**Comment by ZBDeveloper** [comment]
hi, where is your project?

**Comment by mahikawason** [comment]
Is someone working on it? @chhavip

**Comment by chhavip** [comment]
This has been handled. Should close the issue, thank for pointing out @mahikawason
