### ISSUE TITLE
More info on how to play the game.

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#163]
Currently the user is unaware of how to play the the game for instance he is unaware that leaving a game in between in an ongoing scenario leads to deduction in karma points. While configuring the app locally I faced these problems of how are these points calculated, so I think a quick guide would do good.

**Comment by chhavip** [comment]
@anubhakushwaha I am pretty sure leaving a scenario in between should not lead to deduction of points. If that is an issue you feel is genuine, please open an issue and be free to work on it!

**Comment by pandilladivya** [comment]
@chhavip  Can I work on Intro Screens which should be played the first time the app is open, and should explain what the user has to do in the game?!

**Comment by anubhakushwaha** [comment]
Closing because of irrelevant issue reported.
