### ISSUE TITLE
UserPoints in PointsEntry table is never updated.

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#164]
Apologies if it's a future task deliberately left.

**Comment by aanchal07** [comment]
The points are currently updated in totalPoints in SessionHistory.

**Comment by anubhakushwaha** [comment]
@aanchal07 So can I update it in the PointsEntry table as well?

**Comment by aanchal07** [comment]
@anubhakushwaha Yes you can but there is no use of this table entry as of now.

**Comment by anubhakushwaha** [comment]
Closing as it's not an issue as of now.
