### ISSUE TITLE
Add support for app Accessibility

### ISSUE THREAD

**Issue by riddhik84** [systers/powerup-android#166]
Provide android:contentDescription to user interface controls.

**Comment by riddhik84** [comment]
If approved, I can implement this.

**Comment by chhavip** [comment]
This is a very good suggestion! Please check using TalkBack as well that they are spoken correctly. You can go ahead with the task

**Comment by riddhik84** [comment]
Thanks! I will start working on it.

**Comment by MKDEVELOPEMENT** [comment]
is this still available ?

**Comment by chhavip** [comment]
@riddhik84 are you working on this? or else this can be taken up by @MKDEVELOPEMENT

**Comment by riddhik84** [comment]
@chhavip I had started working on this task but then I have created a GCI task which is mapped to this issue.

**Comment by chhavip** [comment]
Ok! @MKDEVELOPEMENT if you wish to you can claim that task and start working on this issue.
