### ISSUE TITLE
Implementing the Replay button 

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#167]
The replay button can be implemented in the ScenarioOverActivity so that the user can play the same scenario as many times as he/she wants. @chhavip Can I work upon this? It would reset the karma points gained due to the particular scenario.

**Comment by jacqueline8711** [comment]
I'm now working on this and claimed the GCI task for it

**Comment by chhavip** [comment]
@jacqueline8711 Will check, thanks!

**Comment by top-gun007** [comment]
@chhavip currently the replay button is non-responsive. Is it being corrected by someone?

**Comment by chhavip** [comment]
We are in the process of checking the PR submitted during GCI and determining if it can be merged.

**Comment by chhavip** [comment]
Closing the issue as it has been fixed #186 .
