### ISSUE TITLE
Provide Labels to Buildings in Map

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#169]

**Comment by MKDEVELOPEMENT** [comment]
can I get this please

**Comment by MKDEVELOPEMENT** [comment]
if I'm correct, I just have to say like "school", "home" over the location on map?

**Comment by MKDEVELOPEMENT** [comment]
if I'm correct, I just have to say like "school", "home" over the location on map? @chhavip

**Comment by chhavip** [comment]
You can come up with any alternative that suits. Can either make the buildings blink once when the app starts or add labels.  My only concern with labels is ruining the look of the scenario so if you can make it still look pretty, go ahead :)

**Comment by chhavip** [comment]
You can come up with any alternative that suits. Can either make the buildings blink once when the app starts or add labels.  My only concern with labels is ruining the look of the scenario so if you can make it still look pretty, go ahead :)

**Comment by MKDEVELOPEMENT** [comment]
cool, ill see which one works best for me

**Comment by mahikaw** [comment]
@aanchal07 @chhavip is someone working on this? Else, I would love implementing it. Please let me know. :smile:

**Comment by aanchal07** [comment]
Since we will be designing new map screen this gsoc, closing it.
