### ISSUE TITLE
Develop clothes and accessories for avatars using Adobe Photoshop and/or Illustrator

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#17]
Currently, there is a limited set of clothes in the app. You can create more by modifying the current ones using Photoshop or Illustrator. These can then be added to the changing room.

**Comment by AkankshaBodhankar** [comment]
I changed the color of hair
Now there are five hair colors
Please do let me know if I can include it in the app and make a PR
Also, if any other ones like eyes, new clothes must be made I would love to work on it
This is just a sample 

![hair3](https://cloud.githubusercontent.com/assets/14356938/13074414/71a7308a-d4ca-11e5-800c-82eef0e494f8.png)
![hair4](https://cloud.githubusercontent.com/assets/14356938/13074415/71a99f82-d4ca-11e5-9d60-71cdc6ee25d0.png)
![hair5](https://cloud.githubusercontent.com/assets/14356938/13074416/71aa3b0e-d4ca-11e5-90f7-1226a1c84f3e.png)
![hair 2](https://cloud.githubusercontent.com/assets/14356938/13074417/71af058a-d4ca-11e5-87a4-87fab711a315.png)

**Comment by alma-castant** [comment]
Looks great @AkankshaBodhankar ! Feel free to create a PR including these in the app (make a static list with the resources for each part: hair, clothes, eyes, etc so it can be easily tested). Also feel free to create other elements

**Comment by AkankshaBodhankar** [comment]
I'll work on it and make a PR

**Comment by AkankshaBodhankar** [comment]
Made a PR :-)

**Comment by chhavip** [comment]
Fixed during GSoC 2016. Closing.
