### ISSUE TITLE
Create a screen for "Not Enough Points" condition

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#170]

**Comment by MKDEVELOPEMENT** [comment]
what exactly is the aim of this ? @chhavip  what are the requirements

**Comment by chhavip** [comment]
Currently if the user wants to buy an item and does not have enough points for the same, the game lets the user buy and just displays a toast in the end saying there were not enough points. It would be better that a purchase of such an item is not possible and the message is displayed in starting either on a separate screen or as a snackbar.

**Comment by MKDEVELOPEMENT** [comment]
![screenshot_2016-12-02-20-40-59 1](https://cloud.githubusercontent.com/assets/24259630/20845936/003851d2-b8d0-11e6-8979-ced10a35a351.png)
so currently it allows you click the continue button which takes you to this activity : 
![screenshot_2016-12-02-20-41-05 1](https://cloud.githubusercontent.com/assets/24259630/20845986/349e1434-b8d0-11e6-8069-46aaf6dc72c7.png)
so if I'm correct, you want this button to be disabled if there are not enough points, and to display a snackbar. ?

**Comment by chhavip** [comment]
Quite correct, yes. But that should happen only when you don't have enough points and not till you can buy items.

**Comment by InfernoCoder** [comment]
@chhavip I would like to claim this issue

**Comment by InfernoCoder** [comment]
@chhavip  I have created the PR [here](https://github.com/systers/powerup-android/pull/189/commits).
**Please ignore the last 2 commits BEFORE the latest as they were made by accident.**
**This PR also contains [this issue](https://github.com/systers/powerup-android/issues/172).**

**Comment by InfernoCoder** [comment]
@chhavip  Here is [the PR](https://github.com/systers/powerup-android/pull/193).
