### ISSUE TITLE
Complete the  avatar in all the activities.

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#171]
Few of the parameters have not been taken care of like hat,bag,glasses and necklace in some other activities which display the avatar.Even after buying those accessories they are not displayed whenever the avatar is displayed in activities other than Avatar Activity.

The Avatar Activity also shows the wrong avatar due to wrong col_id accessed by the methods in Database Handler like getAvatarHat(),getAvatarGlasses(),getAvatarBag()

**Comment by chhavip** [comment]
Sounds good, can go ahead with this if you wish to.

**Comment by anubhakushwaha** [comment]
@chhavip Sure,thanks :)

**Comment by anubhakushwaha** [comment]
@chhavip Done. #173 Please review and let me know if any changes need are to be done.
