### ISSUE TITLE
Display alert message when user clicks an unappropriate option.

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#172]
Warn the user if he/she chooses an option which should not be opted.Can be easily implemented by answers.get(position).getPoints() equals zero.An alert dialog can pop up asking the user to rethink about it. @chhavip @MeepyMay Let me know if I can go ahead.

**Comment by chhavip** [comment]
As discussed, this can be a GCI task for now and up for attempt by pre-university students.

**Comment by eviltak** [comment]
I'd like to claim this issue for GCI.

**Comment by anubhakushwaha** [comment]
@eviltak You can submit a link to your PR and screen shot containing the required changes in the comments section on your gci instance of the task, that will help the mentors to provide live suggestions and comments and easier for you to make the changes accordingly.

**Comment by eviltak** [comment]
I won't be able to work on the task for now, so I'm unclaiming the issue for now so that others can still claim it.

**Comment by MKDEVELOPEMENT** [comment]
can this message be in the form of a dialog or snackbar (optional)?

**Comment by anubhakushwaha** [comment]
@MKDEVELOPEMENT Please the claim the task and ask your queries in the comment section there and we will redirect you from there accordingly :)

**Comment by InfernoCoder** [comment]
I'd like to claim this for Google Code-In. BTW, should I display a Toast, Alert, or a Snackbar?

**Comment by InfernoCoder** [comment]
@anubhakushwaha  I have created a PR for this issue [here](https://github.com/systers/powerup-android/pull/189).

**Comment by anubhakushwaha** [comment]
@InfernoCoder There are some more changes to be done in your code. Please follow-up with the suggestions provided in the GCI website comments section.

**Comment by InfernoCoder** [comment]
I didn't understand the comment in GCI, so it means that I have to return to Map, if a button called 'No' is pressed, and continue if a button called 'Yes' is pressed?

**Comment by anubhakushwaha** [comment]
@InfernoCoder Please ask your queries in the comments section at GCI web app.

**Comment by InfernoCoder** [comment]
I have already asked it there but got no response

**Comment by anubhakushwaha** [comment]
@InfernoCoder Apologies,please check now.

**Comment by InfernoCoder** [comment]
@anubhakushwaha  All problems fixed, and PR is [here](https://github.com/systers/powerup-android/pull/189).
