### ISSUE TITLE
The scenario's should be played in order

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#174]
The current version allows the user to operate at any level without following the sequence designed to be followed.This feature would require database change as an addition of a new column storing the previous scenarioID will solve this problem. @chhavip Can I start working on this?

**Comment by InfernoCoder** [comment]
@anubhakushwaha Is this one still available?

**Comment by chhavip** [comment]
@anubhakushwaha @InfernoCoder , this is a good issue that can be worked upon. Let us keep this in mind for after GCI.

**Comment by InfernoCoder** [comment]
Ok

**Comment by codingblazer** [comment]
@anubhakushwaha @chhavip @aanchal07 
Can i work on this ?

**Comment by codeb1ooded** [comment]
@anubhakushwaha Can you elaborate more on the sequence you are referring to or the link where I can find more about it.

**Comment by aanchal07** [comment]
Currently there is no sequence to be followed in the scenarios, once such game mechanics is decided upon, the issue can be reopened.
