### ISSUE TITLE
Static avatar face in power status bar

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#175]
The current version of the app shows a fixed image irrespective of the avatar of the player.
![screenshot from 2016-11-27 19-37-32](https://cloud.githubusercontent.com/assets/12814245/20648940/c5e87ce0-b4d9-11e6-9518-dd106736cc1c.png)
@chhavip @alma-castant What I wanted to suggest is to instead include a set of imageviews that would include just-face,eye,hair,hat and glasses. With just this one image the user will not be able to relate with the game. Do let me know if this issue I can go ahead with.With your approval I can start and henceforth attach the screenshots.

**Comment by chhavip** [comment]
@anubhakushwaha Sounds like a valid issue that needs to be worked upon.

**Comment by anubhakushwaha** [comment]
@chhavip So can I start working on this and inform about the changes built by posting the screenshots alongside?

**Comment by chhavip** [comment]
I am assuming you are planning to create images for each set of possible combinations that the user can pick?

**Comment by jacqueline8711** [comment]
Wouldn't it be better to just not display any image of the character in the status bar (the character is standing directly above it anyway and the user knows that it's her character) and use the space to add labels to the different health & power bars?

**Comment by anubhakushwaha** [comment]
@chhavip No,as we are generating the avatar dynamically in every screen using the database values stored in Avatar table in exactly the same manner just the face.

**Comment by chhavip** [comment]
I actually like @jacqueline8711's suggestion too. Lets put this up for discussion on the slack channel and see what the best outcome is.

**Comment by mahikawason** [comment]
HI, @chhavip i was looking to work on this issue. Could you please add me to the slack group. My e-mail id is mahika16241@iiitd.ac.in thanks :)

**Comment by anubhakushwaha** [comment]
@mahikawason http://systers.io/slack-systers-opensource/ Welcome to systers

**Comment by mahikawason** [comment]
@anubhakushwaha thankyou :smile:

**Comment by mahikaw** [comment]
@chhavip @aanchal07 is this issue still up and intended?
If it is, I would love to work on this.

**Comment by aanchal07** [comment]
I think this is just a pictorial representation for the main avatar and need not change every time.
@MeepyMay What do you say?

**Comment by aanchal07** [comment]
Closing this as redesigning work will be carried out in gsoc 2017.
