### ISSUE TITLE
Multiple instances of startActivity

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#176]
In map Activity , if we use home button to go back to startActivity , multiple instances of start Activity are created as shown below -

![example](https://cloud.githubusercontent.com/assets/13872065/20656257/cbd0defa-b550-11e6-8ac3-f1dc638d2b66.gif)

Should I send PR for this ?

**Comment by chhavip** [comment]
Please analyse the problem area and suggest how would you be fixing it.

**Comment by codingblazer** [comment]
@chhavip 
Well the problem is - 
`homeButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
                startActivity(new Intent(MapActivity.this, StartActivity.class));
            }
        });`
Here finish() is enough to reach StartActivity as it will be already in backstack. **startActivity(new Intent(MapActivity.this, StartActivity.class));** is creating another instance unnecessarily. Removing this line will solve the problem.
Can i make a PR ?

**Comment by chhavip** [comment]
Hmm, from what I remember that line of code was for the purpose of not losing user data. If you think this will not make the game inconsistent at any point and will adhere every scenario, you can go ahead.

**Comment by chhavip** [comment]
Solved with #187
