### ISSUE TITLE
Implementing About Button

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#177]
Following  #122 
The "About" button or Intro slides are not implemented in app which makes it difficult for even developers to understand the app and its purpose for the first time. I suggest the following -

1. Implementing intro slides for first time and using the same for the **"About"** button. As for PR #122 , the PR used library to implement the same while it can be done without library using the Viewpager (with dot indicators). Also PR doesn't follow good coding guidelines as pointed by @chhavip.

2. Implementing the splash screen - I know the splash makes user wait unnecessarily but we can show splash for time same as app's initialization time (time for which empty grey/white screen appears) which is recommended by google and used in apps like youtube. This can be done by overriding the theme behavior of app.

@chhavip I will like to work on this if this is a intended enhancement. Thanks :)

**Comment by chhavip** [comment]
The issue mentioned in part 1 is genuine and needs to be addressed, but the need of a splash screen is still not justified. You are welcome to create a new issue with just the first point to be implemented if you wish to. Closing this issue as it may be misleading.
