### ISSUE TITLE
Show health and power values in the game UI

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#18]
In the current UI, health and power are static values shown as an image. This task consists of changing this so the actual values are shown in the lower part of the game

**Comment by chhavip** [comment]
I started researching on the best ways to achieve the UI look for this and maintain functionality and came across many libraries but this one seemed best to me:  https://github.com/akexorcist/Android-RoundCornerProgressBar
Let me know if it meets the mark and I can start studying the implementation.

**Comment by alma-castant** [comment]
The library seems good, but a few bugs are also reported. Check whether those are going to affect what you need to develop. You can also trade a little bit of the look and feel and use Android progress bars if this is the case. 

Any thoughts on how much the original image can be modified @iogburu ?

**Comment by chhavip** [comment]
I have implemented the above library and I am attaching a screenshot of the device with the same. All the progress bars can now be customized for color
, size and progress dynamically. Didnt face any major or minor issue. Also we can change the radius of the bars if required.

![screenshot_20151118-012235](https://cloud.githubusercontent.com/assets/7212638/11222955/51b3c532-8d93-11e5-8568-d351e77f5fb4.png)

**Comment by alma-castant** [comment]
Looks good to me. I would probably reduce the internal padding in the bars a little bit if possible, but other than that it looks good

**Comment by chhavip** [comment]
@alma-castant  I have reduced the padding and was getting started on formatting the code properly for submission, just wanted to know if each bar represents some specific power/value for naming purposes or should I leave the naming for future?

**Comment by alma-castant** [comment]
Each bar does represent a different power and you are right on that a design reflecting that is needed. You can work without naming now and I can create a task for designing such a UI. 
@iogburu let me know if you have any ideas

**Comment by chhavip** [comment]
@alma-castant , I have fixed the issues with the PR and now it is working fine, please review and merge it before any other PR as due to an internal error I have lost the code and won't be able to fix any merge conflicts if they occur, I apologize for the inconvenience.

**Comment by alma-castant** [comment]
I have left a few comments in the code. You can retrieve your own code to make the changes by doing:
```
git checkout -b chhavip-power_bar_ui master
git pull git://github.com/chhavip/powerup-android.git power_bar_ui
```

The main issue is that I can't run the code as the external library doesn't seem to be correctly included
