### ISSUE TITLE
Propose possible mini-games

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#19]
This task is very open. The game will have minigames where players can earn more points. These games are not defined, but you can suggest new minigames to the PM team

**Comment by chhavip** [comment]
I was thinking apart from the main story there could be mini games related to healthy eating habits and importance of physical activities in daily life. Also the present storyline can be expanded on various levels, including body image issues for example.

**Comment by alma-castant** [comment]
@iogburu

**Comment by AkankshaBodhankar** [comment]
The mini-games can be expanded to add new scenarios.
The scenarios can be provided for each item on the map, they can be used like levels
On completion of one scenario other can be started
[Scenarios_for_PowerUp.PDF](https://github.com/systers/powerup-android/files/132266/Scenarios_for_PowerUp.PDF)

**Comment by yatna** [comment]
Possible minigame :

A ' **Match the column** ' type minigame where the user will have some questions related to reproductive health and its corresponding answers. 
To make this game interactive, I intend to implement a  **Drag and Drop feature** . The answers will be presented to the user in the form of stickers and the user can drag the answers and paste it over the appropriate question. 

![capture2](https://cloud.githubusercontent.com/assets/8321130/13215872/80f98e80-d97e-11e5-9eed-c99e2888a2df.PNG)

If the answer is correct, the color of the question will change indicating that a correct match has been placed. 

![capture](https://cloud.githubusercontent.com/assets/8321130/13215948/e942fe7c-d97e-11e5-8eb6-71fba450f6ab.PNG)

Every correct answer will fetch some positive points depending on the difficulty of the question.

**Comment by alma-castant** [comment]
@iogburu

**Comment by AaskaShah** [comment]
Mini game:
A quiz game with different sub topics like 
- Health
- Puberty
- Sex
- Diseases
- Relationships
- Friendships
- Family , etc.

Options could be given for each question or it could also be of True/ False type . On clicking any option some explanation would show up below it and a button to next question. Correct answers would give them points.
Please let me know if I could implement it.

**Comment by aanchal07** [comment]
I would like to suggest a few mini games that could be related to reproductive health and general awareness related to sexual activity. A few could be : 

1. Quiz related to STIs, healthy practices, relationships, etc which would indirectly address key information surrounding reproductive health. 

 2. Also a rapid fire question answer round can be included which tests the briskness, alertness and decisiveness. 

3 A card game where a user has to choose if the statement is a fact or myth related to sexual health. A card appears with a statement and user can swipe it right for a fact and left for  myth. 

UI mock up:
![myth1](https://cloud.githubusercontent.com/assets/13906284/14059428/628adbf0-f366-11e5-921e-f3a8cb1dc654.png)

**Comment by iogburu** [comment]
Aanchal, I really like your mini game. We want to stir away from giving
quizes as mini games as typically they are not seen as fun. One mini game
idea that was fully blown out is a bubble game that demonstrates the
probability of a person getting an STI if they don't protect themselves. -
iogburu

**Comment by aanchal07** [comment]
@iogburu Thank you!
