### ISSUE TITLE
Improve the conversation boxes UI

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#20]
Currently, during conversations, the text is shown in boxes that don't always fit the text that is inside. This task consists on improving this UI by making the boxes fit the text that is inside.

**Comment by AaskaShah** [comment]
I will work on this.

**Comment by medhach** [comment]
@alma-castant  In landscape mode, the conversation options are not able to scroll. Is this included in the same issue?

**Comment by AaskaShah** [comment]
I have done that for portrait mode and changes needs to be done in my code for landscape mode, so i will do the same for landscape mode too. :)
