### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#202]
As of now, the app doesn't seem to be very intuitive and hence not very usable. I would like to add the following to improve it. Please guide me through it.
- [ ] Adding Demo Screen using Showcase view library.

- [ ] Materialise the app.

- [ ] Highlighting the buttons of home,library,store etc.

- [ ] Add better toolbar.

**Comment by heysadboy** [comment]
Hi @mahikaw! I love your app's concept. I am a 3rd year engineering student into development and UX/UI designing and would want to work on the app's UI. I think I would be able to work on it. Please do tell me if how can I contribute.

**Comment by chhavip** [comment]
I would suggest to make each of the suggestions as a separate issue. But for discussion, we are not looking to materialise the app as it is a gaming application with a theme of its own. What does adding a better toolbar indicate as there is no toolbar as of now? The demo issue is already open and so is the issue about highlighting labels on buildings.
