### ISSUE TITLE
Add a timestamp to each scenario

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#204]
PowerUp is an educational game where the teenagers have to respond to certain situations by answering certain questions.A time bound would make the game more interesting where in limited amount of time they need to respond in each scenario.The time in which they complete would directly update their points accordingly and if the time is over they wouldn't earn any point.@chhavip @MeepyMay Please review this implementation idea and let me know.

**Comment by chhavip** [comment]
@anubhakushwaha , the questions asked in the scenarios aren't really difficult that would require computations or take time to answer. We do encourage the users to actually think before answering. However this can be useful mini-games that we plan to implement. So lets keep this in mind and look for incorporating the mini-games in the application.

**Comment by anubhakushwaha** [comment]
@chhavip Sure,thanks.
