### ISSUE TITLE
Adding a new user screen

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#215]
I think we could add a new user screen to the app which appears after the "new user" button is pressed. This screen could have add-ons like prompting a name from the user apart from avatar selection. 
This would in-turn enhance the user interaction.
@chhavip , please let me know if this is an intended feature. I would love to work on it. Thanks :smile:

**Comment by chhavip** [comment]
There is already a new user screen and so far a fixed name is used for the avatar. How will the entered name be used?

**Comment by mahikawason** [comment]
The username can be used in the power status bar and other places ( new scenarios added, new games if, added), we could also incorporate a "hi, <name>" at the start. The basic aim is to make it more personalised so as to make it easier for the user to connect with the app.

**Comment by mahikaw** [comment]
@chhavip is this not intended?

**Comment by chhavip** [comment]
For now, this is not intended. Closing till further requirement.
