### ISSUE TITLE
Update README with contributing guidelines

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#219]
Our project needs to update it's README ,I have shared this doc , @chhavip Please review the same regarding the contribution guidelines.I will update the doc as per your say and add other things as well.Let me know if I can work on the same.
https://docs.google.com/document/d/1Eu3cNQ3N7URBW-DB4ryeS9gYBd6T_bL_-Gz64n-Vvt0/edit?usp=sharing

**Comment by chhavip** [comment]
Hey, the guide looks good! But I wouldnt suggest including it in the README as it will make it endless. Include it in the wiki if you wish to. We can link the wiki page in the README

**Comment by anubhakushwaha** [comment]
@chhavip Yeah I agree,will follow as per your say.

**Comment by chhavip** [comment]
This has been taken care of so closing as of now.
