### ISSUE TITLE
Test for bugs

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#22]
Everyone can work on this task. If you find bugs in the application, you can create a new Issue specifying what the issue is

**Comment by chhavip** [comment]
I suppose there should be an option to restart the game if the user has gone through all the scenarios.
Let me know if it should be made an Issue.

**Comment by alma-castant** [comment]
You can create an issue with this, but I don't find it a priority as it is a new feature. There are issues of the current functionality that still need to be fixed

**Comment by chhavip** [comment]
Okay, will create issue after current issues are resolved
