### ISSUE TITLE
Make all the activities uniform

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#220]
It would be a good idea to make the GameOverActivity uniform with the rest of the app, and remove the action bar which shows the app name. Instead the screen should just show the activity with no action bar. @chhavip Please review and if suitable label it as free/beginner so that it can be taken up.Thanks!

**Comment by mahikawason** [comment]
The same is true for completed scene activity.
There is inconsistency in the way different activities look.

**Comment by chhavip** [comment]
Yes, this can be taken up. Attach screenshots of the activities you intend to correct before sendong a PR.

**Comment by mahikawason** [comment]
![device-2016-12-20-125914](https://cloud.githubusercontent.com/assets/21010060/21341790/53ea32f4-c6b4-11e6-8bad-54d87f21afab.png)

This is what I was talking about.

**Comment by mahikawason** [comment]
![device-2016-12-20-131244](https://cloud.githubusercontent.com/assets/21010060/21342130/51f40afe-c6b6-11e6-87be-fe2d2b7b8a46.png)

![device-2016-12-20-131321](https://cloud.githubusercontent.com/assets/21010060/21342145/61bc7c5a-c6b6-11e6-8d4a-a49ecdaa0d7b.png)

This one has been taken care of in PR #214 created by me. Please review and merge it. :smile:

**Comment by anubhakushwaha** [comment]
@mahikaw As it is merged,please close the issue.

**Comment by anubhakushwaha** [comment]
Fixed via #237
