### ISSUE TITLE
Slight error in the house activity

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#222]
1. The question displays a "3" instead of a question.. A very trivial issue..
This screenshot depict it.
![device-2016-12-19-231107](https://cloud.githubusercontent.com/assets/21010060/21327063/5a79ac50-c653-11e6-8514-bd716a8f05ca.png)

2. Also, some of the questions/answers are displayed in quotes, which is unnecessary and not required.
![device-2016-12-20-012129](https://cloud.githubusercontent.com/assets/21010060/21327332/98913aca-c654-11e6-9f5f-19fc4e9ede49.png)

@chhavip I will create a PR rectifying this obvious issue (point # 1) soon. However, please tell if point # 2 also, needs to taken care of. :smile:

**Comment by chhavip** [comment]
Closing as has been fixed via #2364
