### ISSUE TITLE
Alignment problem of text in completed game

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#227]
Text at the complete game activity is a bit misaligned. I'll create a PR fixing this ASAP if that's okay. @chhavip 

![device-2016-12-20-192705](https://cloud.githubusercontent.com/assets/21010060/21354929/00cc2800-c6f2-11e6-99cc-fa78c746897d.png)

**Comment by chhavip** [comment]
Closing as it has been fixed via #238
