### ISSUE TITLE
New user account.

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#230]
Every time the game is completed and the user presses the power up logo to reach the home screen and start the game again, shouldn't it get refreshed/updated? As of now, the game scenario remains the same.
A fix to this could be intimating the user in some way to click on the "new user" button if she wants to play the game from the start or what's better I think is that we could implement a new "replay game" button at the home screen which resets the game but doesn't lead to the new avatar activity.
@chhavip it would be great if you could review it and suggest what can be done for it. I will be willing to work on it.

**Comment by chhavip** [comment]
I did not get what you are trying to explain in this issue. Please list down the different scenarios you envision having.

**Comment by mahikaw** [comment]
After playing a few scenarios and returning to map, if the user wants to start a new game without changing the avatar(or selecting the new user option), there is no provision for that. @chhavip i was wondering if we could implement another button at the start activity to reply the entire game(it would reset the  game except the avatar and other user details, which we might want to incorporate in future)

**Comment by mahikaw** [comment]
@chhavip @aanchal07 
I propose that we 

- add another "resume" button, if the user wants to resume the game(which have functionality of same as the current "start" button".

- change the functionality of start button, so as to restart the game without actually going through the "new user" process involving new avatar selection.
