### ISSUE TITLE
inconsistent layout on different devices

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#232]
I was testing the app on a nexus 5x and a few other phones and found some issues with the layout on it. The questions and the answers list views are merging into the template border as can be seen in the following screenshots.
Please approve this as a genuine issue so that it can be taken up for fixing. Thanks. :)

![device-2016-12-21-125615](https://cloud.githubusercontent.com/assets/21010060/21380819/bf19a86a-c77d-11e6-8786-75a7d6b96d10.png)

![device-2016-12-21-125718](https://cloud.githubusercontent.com/assets/21010060/21380833/d83223f4-c77d-11e6-840b-f305ecd21df0.png)

**Comment by chhavip** [comment]
What would be your approach to fixing it?

**Comment by mahikaw** [comment]
I did some research on this issue and found out that using "sp" instead of "dp" as size units can help solve this problem. I did that on my local repo and tested it on different devices once again. It seemed to solve the issue. @chhavip can I go ahead and create a PR to fix this?

**Comment by chhavip** [comment]
Please attach the screenshots of your local repo with the modifications.

**Comment by mahikaw** [comment]
![screenshot_1482390016](https://cloud.githubusercontent.com/assets/21010060/21417745/b56aa3da-c842-11e6-887b-e0668b505eb8.png)
![screenshot from 2016-12-22 12-34-16](https://cloud.githubusercontent.com/assets/21010060/21417828/3024fd00-c843-11e6-9b54-b408fa844df7.png)
![screenshot from 2016-12-22 12-35-29](https://cloud.githubusercontent.com/assets/21010060/21417829/302a3e28-c843-11e6-8313-18089d7c80a4.png)

**Comment by chhavip** [comment]
Go ahead and send a PR.

**Comment by chhavip** [comment]
Fixed via #252
