### ISSUE TITLE
Unwanted scenario names following school scenario

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#239]
After the school scenario is played, some unwanted scenarios with scenario names like "sex" and "love" follow. The following depicts it.
![device-2016-12-22-015635](https://cloud.githubusercontent.com/assets/21010060/21405073/5c660e9e-c7ea-11e6-9ca7-76a822525454.gif)

@chhavip , It would be great if you could review and suggest if this is intended or a valid issue.

**Comment by chhavip** [comment]
For now this is not a valid issue. We will be revamping the entire database in the future where it will be taken care of together.

**Comment by mahikaw** [comment]
Oh, okay. Sounds good.
