### ISSUE TITLE
Same questions in each scenario

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/powerup-android#243]
The purpose of bringing the concept of different scenario's was to make the user more alert to different situations at different places.Providing the users the same set of questions is not so user interactive. @chhavip If you agree I could prepare questions and corresponding answers and share with you so that we can resolve this issue in case it is one.Thanks!

**Comment by top-gun007** [comment]
hi @anubhakushwaha @chhavip if this issue is going to be implemented wouldn't it be better if the questions can be fetched dynamically(using volley, retrofit etc.) this would enable us to update new scenarios as and when we want.
If yes, I would be happy to help with it.
_Thank you_

**Comment by chhavip** [comment]
@anubhakushwaha @top-gun007 , this is a valid issue but will require a good amount of time and effort which cannot be undertaken right now. Can be considered in the next development cycle.
