### ISSUE TITLE
karma points are lost once the app stopped working

### ISSUE THREAD

**Issue by arpnakumari** [systers/powerup-android#253]
Once the app stops working the karma points are lost and can't be gained again.

**Steps to reproduce:**

1. Complete the game or earn karma points.
2. When the game completes ->store
3. store-> clothes -> click left or right button 
4. Error flashes powerup has stopped working
5. As soon as the app again starts working the karma points is displayed 0.

![screenshot_2016-12-31-02-12-53](https://cloud.githubusercontent.com/assets/24493281/21572655/9cb0ad6a-cf01-11e6-9d5b-fb657a9788a9.png)
you can see the karma point here is 22 and app has stopped working.

![screenshot_2016-12-31-02-13-04](https://cloud.githubusercontent.com/assets/24493281/21572685/e1f1096a-cf01-11e6-941f-4a9ddcd1b60e.png)
When it again starts working karma points becomes 0 and user can't buy anything.
![screenshot_2016-12-31-02-13-49](https://cloud.githubusercontent.com/assets/24493281/21572692/065897b4-cf02-11e6-839c-5dedefe8c067.png)

We can improve working behaviour of app by fixing this.

**Comment by mahikaw** [comment]
hi @arpnakumari!  By"when the game completes" in point 1 in your steps to reproduce, do you mean the following screen? 

![device-2016-12-31-103920](https://cloud.githubusercontent.com/assets/21010060/21575947/b020fea6-cf45-11e6-942a-2c1f6fb51d13.png)

Is this the screen where you are telling to go to store to reproduce the error?

**Comment by arpnakumari** [comment]
By game completes means to earn some karma points or complete all scene in total.

**Comment by chhavip** [comment]
Can you come up with the cause of the crash? Is it across all devices or specific to your settings of the same?

**Comment by chhavip** [comment]
The application does not seem to crash on my device (Xperia Z3 with Android Marshmallow) after completion. Please provide a probable cause for the same on yours.

**Comment by arpnakumari** [comment]
I don't know the cause of the crash :(
I don't even have another phone to test it. And my system is too old to run any emulator.
I tried it and i'm still getting it on Yu Yureka Plus (android 5.1.1 with cyanogen 12.1)

**Comment by arpnakumari** [comment]
@chhavip sorry, Ichecked on other phone it worked fine.

**Comment by chhavip** [comment]
Its fine :)
