### ISSUE TITLE
Found some disordering in activities

### ISSUE THREAD

**Issue by codeb1ooded** [systers/powerup-android#254]
I found out that in some activities if we open an activity and then click back on that activity, it should not go to previous activity that was opened.

1: When I first installed the app and played the game. After the ScenarioOverActivity, if I click home button then it opens up the MainActivity. On the MainActivity, if I clicked back I am again taken to GameActivity. Similarly, on clicking back GameActivity I am taken to MapActivity and then to MainActivity again. But I guess after clicking continue on MainActivity, I should not be allowed to go back on GameActivity.

2: After completing the game, I again opened the app and on click I see the CompletedSceneActivity. 
After this activity if I move like  
CompletedSceneActivity (Chosen Store) -> DressingRoomActivity (Choose clothes) -> SelectFeaturesActivity (Click Continue) -> AvatarActivity (press continue) -> MapActivity
On this MapActivity, if I click back I am taken to CompletedSceneActivity. Instead, app should be taken MainActivity.

If you allow, I would like to work on this issue.

**Comment by chhavip** [comment]
Good catch. Can work on this. Please illustrate what steps will you take to fix the same.

**Comment by codeb1ooded** [comment]
For 1st case, since it's the main activity of app and no other activity should be in backStack below it, I guess it should be declared as `android:noHistory="true"` in manifest.

For 2nd case, `android:noHistory="true"` doesn't apply as MapActivity has MainActivity below it. In the app, I found that instance of every activity is maintained and previous activities were finished in some cases using these instances. Hence, I was thinking to extend this and see which instances are live (which are live only in some cases) and should be removed from backStack. Hence, I was thinking to do something like this as in Avatar Activity to remove CompletedSceneActivity,

```
// Previous code 1
DressingRoomActivity.dressingRoomInstance.finish();
SelectFeaturesActivity.selectFeatureInstance.finish();
// added code sample
if( CompletedSceneActivity.completedSceneActivityInstance != null){
             completedSceneActivityInstance.finish();
}
// Previous code 2
finish();
startActivityForResult(new Intent(AvatarActivity.this, MapActivity.class), 0);
```
or use shared preferences if they are required to keep note of what all activities have user passed through.

**Comment by codeb1ooded** [comment]
@chhavip should I work on the issue?

**Comment by codeb1ooded** [comment]
@anubhakushwaha @aanchal07 Can I work on the issue?
