### ISSUE TITLE
non-uniform button appearance at the starting page

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#258]
The text of "start" and "new user" activity are in bold while that of "about" is not. This doesn't give a very nice appearance to the app. 
However, I noticed that these are images in the drawable and the text isn't written in android studio. 
Maybe, we could replace the images. 
@chhavip I would like to work on this. Could you please approve. Thanks.

![photo785144477708822642](https://cloud.githubusercontent.com/assets/21010060/21731831/5ec344f6-d47c-11e6-8ade-14b41227b67d.jpg)

**Comment by chhavip** [comment]
@mahikaw, yes, this is a valid issue, go ahead.

**Comment by mahikaw** [comment]
Okay. However, @chhavip since the text is with the  button background, will it be okay to change all 3 buttons so as to make them uniform?

**Comment by chhavip** [comment]
What is the need to change the other buttons? Cannot a new About button be created similar to existing buttons?

**Comment by mahikaw** [comment]
I'll need that exact same brown background image which isn't available. I'll try modifying the image to remove the text, nevertheless. :smile:

**Comment by chhavip** [comment]
You can color pick the brown color and paint over the existing text to get the background.

**Comment by mahikaw** [comment]
okay sure I'll do that and create a PR asap :)

**Comment by anubhakushwaha** [comment]
@mahikaw Please close this issue as it's fixed via #271

**Comment by mahikaw** [comment]
closing.
