### ISSUE TITLE
The power status bar "current emotion" field

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#259]
The current emotion field remains "happy" all the time. I don't exactly get it's utility. Shall we make it dynamic, based on the answers of the users? 
Also, there was a previous issue regarding the static avatar face on the bar. Did we come to any conclusion and is someone working on that?
@chhavip , please review. thanks :)

**Comment by chhavip** [comment]
Yes, the current emotion needs to be changed dynamically but there is no direct correlation between the answers and the emotions as of now. This needs to be resolved, perhaps in the next development cycle of GSoC 2017. This is a valid issue but with no clear path for resolution, if you have suggestions, please add them. 

As for reference to the other issue, please comment on the respective thread for continuous discussion.

**Comment by mahikaw** [comment]
I think we could add conditions like if a specific answer is chosen, the emotion field changes to a corresponding mood entry. Is that what we are looking for?

**Comment by chhavip** [comment]
This is intended but currently no discussion can be undertaken as to what answers refer to which emotions. So this issue will be put on hold till next development cycle.

**Comment by mahikaw** [comment]
Great thanks. :)

**Comment by aanchal07** [comment]
Refer to #366
