### ISSUE TITLE
Labelling the characters

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#260]
As of now, the game activity gives no indication as to who the two figures in it are. For first timers, it could get a bit confusing as to who is asking the questions etc. We could label the two figures as being "you/<name_of_user>" and "boyfriend".
Doing this would enhance the interactivity of the app.
@chhavip please review. :)

![photo785144477708822643](https://cloud.githubusercontent.com/assets/21010060/21732372/2d859472-d47f-11e6-8179-92e298053d90.jpg)

**Comment by chhavip** [comment]
@mahikaw , no we are not looking to label the characters as of now, probably include it in the introduction or about of the application which is already an open issue. Perhaps labeling will be required when there are more characters but for now not really. Thank you for pointing this out! Closing for now.

**Comment by mahikaw** [comment]
Okay, so if we do it in the introduction, could we add like an intro screen where the 2 present characters meet and say hi and thus, introduce themselves?
