### ISSUE TITLE
Unnecessary imageview in store activity

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#261]
There is this unnecessary image showing age as 12 in the store activity. We could specify this age limit at the starting of the app or in the about/introductory pages. 
@chhavip please review. Thanks :)

![photo785144477708822644](https://cloud.githubusercontent.com/assets/21010060/21732357/1308f31e-d47f-11e6-97f1-dd9be589f1b1.jpg)

**Comment by mahikaw** [comment]
@chhavip @aanchal07 please let me know if this is intended. :)

**Comment by chhavip** [comment]
This is not intended right now, no need to modify the look of the store. Closing.

**Comment by mahikaw** [comment]
okay :)
