### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#264]
We could add the .apk of this app in the README for easy accessibility and building the app for contributors as well as others.
@chhavip @aanchal07 should I go ahead and submit a PR for this?

**Comment by chhavip** [comment]
@mahikaw We are not looking to add a static apk as it wont get automatically updated with each PR making the work unnecessarily manual. But continuous integration is something that can be a desired addition. Let me know if that is something you are familiar with doing.

**Comment by mahikaw** [comment]
yes, @chhavip, I can go ahead with dynamic updation. This would mean that the apk will get updated everytime a PR is merged to the main branch "develop". 
Can I start working on this?

**Comment by aanchal07** [comment]
@mahikaw yes go ahead and work on it. It would be a great if we can have the current apk file immediately.

**Comment by mahikaw** [comment]
Hi, I was working on it. I will be needing access to this repo so as to enable Travis @chhavip @aanchal07 .
Please see what can be done. Thanks :)

**Comment by chhavip** [comment]
@mahikaw, write access to repo cannot be granted without a necessary reason, if it is not possible to integrate Travis without it, one of the existing owners will undertake the task.

**Comment by chhavip** [comment]
Lets close this issue for now as it does not even reflect the actual task, this can be taken up during the next development cycle.

**Comment by mahikaw** [comment]
@chhavip no problem. :)
maybe we could put it on hold, instead of closing it. You could guide on that.
