### ISSUE TITLE
Reducing the size of APK 

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#265]
We could decrease APK size which would enable easy download and better performance.
@chhavip @aanchal07 can I go ahead and make a PR for this?

**Comment by chhavip** [comment]
How are you planning to achieve this? Also indicate the current size and the amount of reduction you plan to achieve before making a PR.

**Comment by mahikaw** [comment]
I was thinking of using scalable drawable resources in place of image files and enabling shrinkResources apart from other things. 
@chhavip , sure will do indicate that after I'm done, then you  and @aanchal07  could decide if it is intended. :)

**Comment by chhavip** [comment]
Sure, go ahead

**Comment by anubhakushwaha** [comment]
@mahikaw Updates?

**Comment by mahikaw** [comment]
I couldn't reduce it by a significant amount. We could put it on hold or close it for now. @anubhakushwaha

**Comment by codingblazer** [comment]
@anubhakushwaha Can I work on this ?
I will use vector drawables for sharp images. For drawables that are not sharp/scalable can be optimised by tools like pngcrush (Suggested by AndroidDev Docs). Other than this there some more techniques to further reduce apk.

**Comment by anubhakushwaha** [comment]
@codingblazer You can go ahead and report us the amount by which you could reduce it.

**Comment by codingblazer** [comment]
@anubhakushwaha Yeah sure
