### ISSUE TITLE
Extra White space and Scroll bars in the Game_Activity screen

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#268]
![bug1](https://cloud.githubusercontent.com/assets/22029744/21755266/350d2f70-d637-11e6-97df-0c93f236c52c.png)
![bug1 1](https://cloud.githubusercontent.com/assets/22029744/21755284/8724002c-d637-11e6-94f0-1799e439d8da.png)

There is Extra White Space in some of the screens and a scroll bar in others. We can have a common placeholder which instead of having a fixed size has the height as wrap-content and adjusts accordingly.
@chhavip @aanchal07  Can I make a PR for the same?

**Comment by mahikaw** [comment]
@Baanileen , This has been already taken care of and is on it's way to getting merged. :)

**Comment by BaaniLeen** [comment]
@mahikaw Okay. That's great :)
Can you plz mention the issue number?

**Comment by mahikaw** [comment]
#232

**Comment by BaaniLeen** [comment]
Thank u @mahikaw  :)

**Comment by chhavip** [comment]
Closing as taken care of.
