### ISSUE TITLE
Position of ImageButtons for the hair, clothes, accesories in the Store

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#269]
![suggestion1](https://cloud.githubusercontent.com/assets/22029744/21755407/62cfc524-d639-11e6-95b7-09a195702b0f.png)
The clickable ImageButtons in the Store should be aligned along the left and right sides of the parent container and should be center-aligned vertically allowing the user a wider clickable region to move back or forth easily.
@chhavip Shall I make a PR for the same? :)

**Comment by chhavip** [comment]
Please point out the current configurations of the buttons and what all changes you intend to make. As it is a feature who's importance can only be judged after testing, you are welcome to make a PR but whether it'll be merged will depend on the amount of improvement it brings.

**Comment by BaaniLeen** [comment]
@chhavip Yeah! Np :) Thanks for the advice. I will send a PR soon regarding the same :)
