### ISSUE TITLE
Change of Name and the Player icon needed in the store

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#270]
![bug2](https://cloud.githubusercontent.com/assets/22029744/21756749/4c5ddc24-d64b-11e6-843c-035e241dc55b.png)

The name "Rosey" can be user customised and also the Player Icon placed just above the name "Rosey" should be in sych with the player avatar.
@chhavip @aanchal07 Can I make a PR regarding the same?

**Comment by mahikaw** [comment]
@BaaniLeen this is same as  #215 #175 . :)

**Comment by BaaniLeen** [comment]
Okay thanks @mahikaw :)
@chhavip @aanchal07 Are any of the issues still open? If so, I would to contribute to them too :)

**Comment by chhavip** [comment]
Closing as already exists. Continue discussion on those issues.
