### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#273]
The code of this app has a significant amount of redundancies like same images stored under diff. names, unused strings, various typos in code as well as comments, unused drawables, deprecated elements,unused method parameters, unused declarations and various other things.

@chhavip @aanchal07 can I make a PR after cleaning up the code?

**Comment by aanchal07** [comment]
@mahikaw There is already an open issue for code cleanup. Please continue discussion here.  #134

**Comment by chhavip** [comment]
Closing this. In future please go through the existing list of issues before opening one @mahikaw

**Comment by mahikaw** [comment]
oh, I missed it. Will keep it in mind.
