### ISSUE TITLE
Landscape UI problems

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#275]
In landscape mode, 

1. The final avatar shown is not proper as shown below -

![whatsapp image 2017-01-12 at 19 41 05](https://cloud.githubusercontent.com/assets/13872065/21893022/56ebc21c-d8ff-11e6-9aa2-8f3f8e8bd709.jpeg)

2. In any scenario, there is a unnecessary white box below conversation as shown -

![whatsapp image 2017-01-12 at 19 41 05 1](https://cloud.githubusercontent.com/assets/13872065/21893030/5f01189e-d8ff-11e6-9af6-f8470ba98955.jpeg)

3. Replay and Continue button are not properly placed as shown -

![whatsapp image 2017-01-12 at 19 41 05 2](https://cloud.githubusercontent.com/assets/13872065/21893038/67002f30-d8ff-11e6-9c0a-e496d011e810.jpeg)

@chhavip Can i send PR for this ? Thanks :-)

**Comment by chhavip** [comment]
This looks like a good catch. Can work on theses issues. Also please test for landscape modes of different dpi devices. Plus make sure that the screens have scrollview as some content seems to run off and isnt available.

**Comment by codingblazer** [comment]
@chhavip Yeah, will look all landscape related issues.

**Comment by Pankaj-Baranwal** [comment]
If no one is working on this, I can contribute and solve this issue.

**Comment by codingblazer** [comment]
@Pankaj-Baranwal This is issue is already solved via PR #280 .

**Comment by Pankaj-Baranwal** [comment]
Is the develop branch up to date or should I checkout to master to view the changes?

**Comment by codingblazer** [comment]
@Pankaj-Baranwal Yes, develop branch is active branch and updated one.
