### ISSUE TITLE
Changes in avatar gets lost when orientation is changed.

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#278]
**Summary**
If a user create a new avatar in new user section and meanwhile if he/she rotates the screen the changes gets lost.

**Expected Output**
The changes in avatar should remain unchanged even when orientation is changed.

**Screenshots**
![image](https://cloud.githubusercontent.com/assets/15179401/21993407/b170d58a-dc40-11e6-984b-bbc84975dc37.png)
![image](https://cloud.githubusercontent.com/assets/15179401/21993600/abfd8a02-dc41-11e6-9319-daf6bbbc8b9b.png)

**Comment by top-gun007** [comment]
Can I start working on it @chhavip 
_thank you_

**Comment by chhavip** [comment]
@top-gun007 Can start working on this
