### ISSUE TITLE
Enhancement: When game is in progress.

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#279]
**Summary**
Just like all popular games if a game is in progress the following things should be taken care of:

- If the game is in progress the _start_ button should be changed to _Resume_.

- If during this time the user clicks on new user and creates a new avatar he should firstly be warned and weather he/she wants to overwrite it or not.

- If a scenario is complete then that particular scenario should be coloured differently(dimmed) then the rest of the scenarios.

**Comment by chhavip** [comment]
These seem like valid issues, but it would be better to to work on them separately rather than combine them together.  For now, you can work on the issue of changing _start_  to _Resume_ and on the issue of warning a user before they create a new user. Send them as separate PRs.

**Comment by top-gun007** [comment]
Will send PR's soon.
_Thank you_

**Comment by mahikaw** [comment]
I think this is same as #230

**Comment by mahikaw** [comment]
@chhavip please review.

**Comment by top-gun007** [comment]
hi @mahikaw in reference to your issue #230. It was related to starting a new game and the same can be accomplished through new user and the game would be restarted.

**Comment by mahikaw** [comment]
My point is that why should the user be made to select an avatar every time she wants to play the game again. There is no way the user can play the game from the start without re-selecting the avatar

**Comment by chhavip** [comment]
Closing as it fixed through #284

**Comment by top-gun007** [comment]
@chhavip only one of the three issues is complete. Please open it.
_Thank you_

**Comment by top-gun007** [comment]
@chhavip since I have sent PR's for the first two can I send the PR for 3rd one.
I am planning to use ColorFilterAttribute of android for it.
_Thank you_

**Comment by chhavip** [comment]
Do not work on the third issue for now as the requirement for the enhancement is not final. Thank you for working on other issues!
