### ISSUE TITLE
Bugs in Karma Points

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#281]
1. After making selections and continuing, we get our final avatar. Now if we press back, the screen doesn't show updated points (points are still 26). One can change orientation (to recreate activity) and see the original points it should have shown.

<img src="https://cloud.githubusercontent.com/assets/13872065/22085174/f30d78a4-ddf8-11e6-95dc-48162deebab3.gif" height="400" width="200">

2. Also on pressing back in Final Avatar Screen, we can go back to selection Screen but it should take to main screen.

3. Also we can see above, though user selected hair worth 5 points , the points deducted were 10. Similar is the problem with -
Hair
Glasses
Bag
Necklace

4. While testing, i came across a case when points become negative. On selecting Hair when points are less than 10. As shown below -

<img src="https://cloud.githubusercontent.com/assets/13872065/22616368/c38be4e0-ead1-11e6-9de4-d9569bcfa6cc.jpeg" height="400" width="200">

@chhavip Can I start working on this ?

**Comment by anubhakushwaha** [comment]
@codingblazer Yes a valid issue,can go ahead.

**Comment by codingblazer** [comment]
@anubhakushwaha @chhavip Will be sending PR soon.

**Comment by anubhakushwaha** [comment]
@codingblazer Any update?

**Comment by codingblazer** [comment]
@anubhakushwaha I will send a PR soon for all pending issues. I was busy due to travelling.
