### ISSUE TITLE
Issues with Orientation Change

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#282]
There are following issues with orientation change -
1. In About Screen, if any item is expanded (For ex - Why this App is needed) and orientation is changed, it becomes collapsed.
2. On changing orientation is any scenario, scenario starts from beginning again.
3. Any selection made for avatar in Store goes away on changing the orientation.

@chhavip Should I send PR for this ?

**Comment by top-gun007** [comment]
@codingblazer I reported orientation change issue here #278

**Comment by codingblazer** [comment]
@top-gun007 You have not listed any of these issues in your #278 and neither asked for all other orientation issues. Sorry but I have started working on this already as these seem very valid.
( the 3rd issue in this list is also different as you have reported it in New User Screen while I have reported it in Store in which there are more screens like Accessories etc)

**Comment by top-gun007** [comment]
@codingblazer according to wiki it is advised that you should first get conformation from mentors before working on any issue.

**Comment by codingblazer** [comment]
@top-gun007 I have analysed the problem and its location and have a fix for it which mentors do ask as in issue #176 .This is what I mean by work. 
As for this issue, I have read your #278 and there is nowhere a mention of these issues. Also you have nowhere mentioned in #278 that you were going to find more such issues.

**Comment by codingblazer** [comment]
@top-gun007 As for wiki, wiki advised to not make PR before approval (which I haven't done). Also wiki suggests to first claim the issue. Have you claimed these issues anywhere ?

**Comment by top-gun007** [comment]
Please don't get me wrong but what I am trying to say is that I founded the orientation related issues first and isn't it obvious that their would be other activities having similar issues as well and planning to report others as well once someone had approved them so what I propose is let's just share the work load as their are quite some of them.

**Comment by codingblazer** [comment]
@top-gun007 I am not getting you wrong :-) We are just conversing :-)
Its just that I have done some work (identified the fix) on these issues. It won't be productive for you to invest your time again on the same thing. You can work on #278 and solve any more orientation bugs you may find.
And as for your point, I don't agree with it :-) In past, on malaria project, many different contributors reported "Landscape related issues", a part of which was first reported by me. 
I hope you understand. Lets close this conversation here and let mentors decide on it. :-)

**Comment by top-gun007** [comment]
ok cool :+1:

**Comment by chhavip** [comment]
@codingblazer , you can work on the first and second point of your issue mentioned, the third can be taken care of issue by @top-gun007

**Comment by top-gun007** [comment]
thank you @chhavip

**Comment by codingblazer** [comment]
@chhavip Yeah sure :-)
