### ISSUE TITLE
Adding Unselect Option in Store

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#283]
While selecting anything in store (Clothes/Hair/Accessories), if user has selected anything , he/she has no option to unselect any item. 
We can implement a clear button for each item through which user can unselect any selection as shown below - 

<img src="https://cloud.githubusercontent.com/assets/13872065/22086528/15e44fd2-ddff-11e6-8fba-23adb6ad79e6.png" height="500" width="250">

The unselection button(cross) for any item will only come when user will make any selection (UI will not be effected otherwise).
@chhavip Should I send PR for this ?

**Comment by aanchal07** [comment]
@codingblazer I think this is a good idea and a workable one. 
@chhavip @anubhakushwaha What do you think?

**Comment by anubhakushwaha** [comment]
@codingblazer Yeah the idea is good but could you possibly think of any other way to do it(unselect) because addition of another imagebutton to existing image buttons thereby reducing their respective weights will not render a good user experience.Incase we don't come up with any better solution we can reconsider the original idea you proposed.

**Comment by codingblazer** [comment]
@anubhakushwaha We can show the cross button on the top instead i.e cross button will be on the right of "**BAG**".

**Comment by aanchal07** [comment]
@codingblazer If a user does not want to purchase an item she can rather press the back button and not buy anything or use the next/previous buttons on bottom of each image to choose the other option. Why need a clear button?

**Comment by codingblazer** [comment]
![whatsapp image 2017-02-01 at 7 33 16 am](https://cloud.githubusercontent.com/assets/13872065/22492657/ece8a676-e850-11e6-8200-b829a390923e.jpeg)

**Comment by codingblazer** [comment]
@aanchal07 @anubhakushwaha @chhavip 
Can I start working on this

**Comment by codingblazer** [comment]
@aanchal07 Gentle Reminder :-)

**Comment by aanchal07** [comment]
@codingblazer This involves adding a new functionality to the game which needs to be discussed. This can be included in the next iteration after getting approval from team. What do you say @chhavip ?

**Comment by codingblazer** [comment]
@aanchal07 Yeah sure. In case it look intended enhancement to team, please let me know. I will be more than happy to implement it in next development cycle :-)

**Comment by aanchal07** [comment]
@codingblazer Yes definitely!
