### ISSUE TITLE
updating README 

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#285]
I came across certain instructions in the README file which, I feel should be updated.

@chhavip @aanchal07  Can I go ahead with a PR so that you could review if the changes are valid?

**Comment by chhavip** [comment]
Please indicate which instructions are you referring to before sending a PR @mahikaw

**Comment by mahikaw** [comment]
I found the following things:-

- Under **"configure remotes/To update your local copy with remote changes, run the following:"**, 
Firstly the command should be "git merge upstream/develop". Also, I think using "git pull --rebase" would be better as that wouldn't create extra merge commits.

- Also, now that the gitignore is working, we should encourage using "git add ." when all the files are to be committed as it will save manual efforts.(referring to pt.6 of "Contributing and developing a feature").

- I think we could add instructions about how to squash commits as it is a common problem faced by new contributors.

- It is often seen that contributors isolate a resource( like a drawable or a string), in that case we should encourage them to delete the unused resources as well in the same PR. This practice can be mentioned under "coding guidelines" section of the README.

@chhavip should I go ahead and incorporate these changes?

**Comment by mahikaw** [comment]
@chhavip is this intended?

**Comment by chhavip** [comment]
Hello! The git commands that a person wishes to use can vary depending on personal preferences, the Read Me is intended to provide a basic direction and people can have their own  style. I believe only generic statements and those applicable in any situation should be included in the ReadMe as otherwise it might confuse the beginners. Opinion @aanchal07?
