### ISSUE TITLE
when orientation is changed, colour is non consistent

### ISSUE THREAD

**Issue by himani777** [systers/powerup-android#287]
default green colour is set as background in landscape orientation for all options in store.

![screenshot_2017-01-27-14-52-14](https://cloud.githubusercontent.com/assets/13470007/22366413/91e65ebe-e4a2-11e6-9f92-47a18b6353ce.png)
![screenshot_2017-01-27-14-52-22](https://cloud.githubusercontent.com/assets/13470007/22366419/9a715c32-e4a2-11e6-8fd6-28bf0e432820.png)
![screenshot_2017-01-27-14-58-03](https://cloud.githubusercontent.com/assets/13470007/22366421/9eb23fb4-e4a2-11e6-9521-bbc55a8e4349.png)
![screenshot_2017-01-27-14-58-09](https://cloud.githubusercontent.com/assets/13470007/22366423/a06ab73c-e4a2-11e6-85b2-4c13359b94b5.png)

**Comment by anubhakushwaha** [comment]
@chhavip I think it's a workable issue.

**Comment by chhavip** [comment]
@himani777 Sounds good, can send a PR

**Comment by harshitagupta30** [comment]
@anubhakushwaha @chhavip @aanchal07 Since no progress has been made can I work on this issue?

**Comment by anubhakushwaha** [comment]
@harshitagupta30 #292 has done the above task and is yet to be merged.
