### ISSUE TITLE
Go to the map activity after finishing in the change room

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#29]
Currently, after clicking continue in the change room, the user is redirected to the conversation activity. Instead, change it to redirect to the map activity

**Comment by chhavip** [comment]
I will work on this.

**Comment by rosariorobinson** [comment]
@alma-castant @chhavip these are native dev so please be sure that you are documenting this work and work with the iOS team to incorporate all of these changes.

**Comment by jenpaff** [comment]
I am travelling atm, but I can follow up with all the dev changes made in
the Android app and post it as a task for iOS on Github.

**Comment by chhavip** [comment]
https://github.com/systers/powerup-android/wiki/Change-Documentation
I have made the above wiki page for all changes made in Android code which I will try and maintain and can be referred to follow up in iOS version

**Comment by jenpaff** [comment]
Perfect, thanks so much. I can post them on the iOS git repo so the tasks
are easily accessible for people who want to contribute.

https://github.com/systers/powerup-android/wiki/Change-Documentation
I have made the above wiki page for all changes made in Android code which
I will try and maintain and can be referred to follow up in iOS version

—
Reply to this email directly or view it on GitHub
<https://github.com/systers/powerup-android/issues/29#issuecomment-156012644>
.

**Comment by jenpaff** [comment]
Have you documented the features in more detail anywhere? Would like to
refer to it when posting them on Github.

**Comment by alma-castant** [comment]
Each feature should be briefly explained in the corresponding issue. All issues resolved are under closed issues

**Comment by jenpaff** [comment]
Ok thanks, I will update them for iOS.

**Comment by alma-castant** [comment]
Let me know if you have any questions about any of them ;)
