### ISSUE TITLE
Tapping issue in MapActivity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#290]
**Current Behaviour**
GameActivity  corresponding to Hospital and Boyfriend  is opening only when the user taps at a particular area because **HospitalButton** and  **BoyfriendButton** in gamemap.xml doesn't cover the entire view area (Background Buildings).

**Expected Behaviour**
The above mentioned  buttons should cover the background buildings  properly (just like in House and School buildings in gamemap.xml) so that user can be  prompted to  next activity after  tapping on the entire buildings.

**Fix**
width and height of the above mentioned button needs to be changed.

@chhavip @anubhakushwaha If this is a valid issue can I send PR ?

**Comment by aanchal07** [comment]
Closing this as redesigning work will be carried out in gsoc 2017.
