### ISSUE TITLE
Replay and Continue button disappears on orientation change

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#291]
**Current Behaviour**
replay and continue buttons in ScneraioOverActivity disappears on changing the device orientation.

![ezgif com-optimize 6](https://cloud.githubusercontent.com/assets/18090596/22402966/58710330-e62f-11e6-8cac-120aaee28861.gif)

**Expected Behaviour**
State of the buttons must me preserved on orientation change.

@chhavip @yatna @anubhakushwaha can I send PR for the same?

**Comment by aanchal07** [comment]
@HimanshuS01 The buttons are appearing in my genymotion device(although the positioning is all wrong). Can you please check again?

@chhavip @anubhakushwaha Can you guys also check once?
![image](https://cloud.githubusercontent.com/assets/13906284/22418401/e635e7ce-e6fe-11e6-89cf-35fa3e667ddb.png)

**Comment by HimanshuS01** [comment]
yeah @aanchal07 .I have checked it again.It is still happening in the latest fetched code from develop branch.

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yeah go ahead,further try to fix the relative alignment of the buttons along with their sizes as well.

**Comment by HimanshuS01** [comment]
Sure @anubhakushwaha . Thanks
