### ISSUE TITLE
On changing the orientation of screen the quiz restarts again.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#295]
![videotogif_2017 01 29_20 53 16](https://cloud.githubusercontent.com/assets/12701036/22405226/5836fb64-e665-11e6-8129-1cd378803f9d.gif)

@chhavip @anubhakushwaha Please review. Can I send the PR resolving this issue?

**Comment by HimanshuS01** [comment]
Hey @harshitagupta30 This issue is already been reported in #282 in point number 2.

**Comment by harshitagupta30** [comment]
@HimanshuS01 my bad! thanks for letting know :+1:

**Comment by HimanshuS01** [comment]
@harshitagupta30 No problem.You can close this issue.Thanks :)
