### ISSUE TITLE
ScenarioNames issue in GameActivity in landscape mode

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#296]
ScenarioNames TextView  in  GameActivity is not displaying properly in landscape mode and the text is cutting with the background layout.

**Screen Shots**
![whatsapp image 2017-01-30 at 1 04 18 pm 1](https://cloud.githubusercontent.com/assets/18090596/22415393/126f9f0e-e6ed-11e6-8296-8e82f621d960.jpeg)
![whatsapp image 2017-01-30 at 1 04 18 pm 2](https://cloud.githubusercontent.com/assets/18090596/22415394/128391a8-e6ed-11e6-86ef-45d406051669.jpeg)
![whatsapp image 2017-01-30 at 1 04 18 pm 3](https://cloud.githubusercontent.com/assets/18090596/22415395/12864d26-e6ed-11e6-8885-aadb52149d20.jpeg)
![whatsapp image 2017-01-30 at 1 04 18 pm](https://cloud.githubusercontent.com/assets/18090596/22415396/12890b88-e6ed-11e6-8965-e68d0309da2b.jpeg)

@chhavip @yatna @anubhakushwaha If this is a valid issue can I work on this and send the PR for the same?

**Comment by anubhakushwaha** [comment]
@HimanshuS01 How are you planning to implement it?

**Comment by HimanshuS01** [comment]
I am thinking to align the scenarioNameEditText to extreme left and just give a small left margin thereby maintaining the UI. 
@anubhakushwaha what are your views regarding this ?

**Comment by aanchal07** [comment]
@HimanshuS01 Please send a screenshot of the screen once you edit the UI so that we can approve.

**Comment by HimanshuS01** [comment]
@aanchal07 sure. Thanks :)

**Comment by HimanshuS01** [comment]
**ScreenShots of change**
![device-2017-02-04-011804](https://cloud.githubusercontent.com/assets/18090596/22606260/424dd7e2-ea79-11e6-936c-4bd65e4b03a2.png)
![device-2017-02-04-011614](https://cloud.githubusercontent.com/assets/18090596/22606261/425aac10-ea79-11e6-936e-0a2f8527e372.png)
![device-2017-02-04-011702](https://cloud.githubusercontent.com/assets/18090596/22606262/42672dc8-ea79-11e6-830c-0ce986212b47.png)
![device-2017-02-04-011736](https://cloud.githubusercontent.com/assets/18090596/22606265/42fc801c-ea79-11e6-957f-1e0b10c460f9.png)

@anubhakushwaha @aanchal07 @chhavip @yatna Please review the above screenshots. 
I will send the PR after approval. Thanks :)

**Comment by aanchal07** [comment]
@HimanshuS01 Now in the conversation _"Let's go back to my place"_, **Let's go** is getting cut by the background.
@chhavip  @anubhakushwaha What do you say?

**Comment by HimanshuS01** [comment]
Yeah @aanchal07.Sorry for that. I miss that part to correct. Thanks for reviewing . I Will soon update with the correct UI.

**Comment by HimanshuS01** [comment]
**Screen Shot**
![device-2017-02-04-023729](https://cloud.githubusercontent.com/assets/18090596/22608466/fcb537e8-ea82-11e6-9a17-2fcfbfb65156.png)

@aanchal07 Please review .Thanks :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yes it's good,you can send a PR
