### ISSUE TITLE
UI Enhancement in completed_scene.xml

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#299]
**Suggestion**
Aligning the text content to the center and changing the background of **map** and **store** button(brown_button_background.png) will give the activity more cleaner look .
 
**Before**
![whatsapp image 2017-02-01 at 1 15 19 am](https://cloud.githubusercontent.com/assets/18090596/22481701/306d2f82-e81c-11e6-9941-2f88a5d8863f.jpeg)

**After**
![device-2017-02-01-011447](https://cloud.githubusercontent.com/assets/18090596/22481711/3cc3e4d8-e81c-11e6-950f-396ef122615b.png)

@anubhakushwaha @aanchal07 @chhavip @yatna If this is an intended enhancement and if the UI looks good can I send the PR for this?Thanks :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yeah go ahead.
