### ISSUE TITLE
UI related issues in many activities

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#306]
These are some UI related issue in many places in this application:

1)ListView in **GameActivity** is overlapping with the background image .Proper right_margin should be given in order to make UI more cleaner and clutter free

2)White background should not be present just behind the **replay** and **home** icon in GameActivity. Icon's background must be transparent. 
![whatsapp image 2017-02-04 at 2 14 14 pm 2](https://cloud.githubusercontent.com/assets/18090596/22617564/5eab9f80-eaee-11e6-86b7-fc386a1a6950.jpeg)

@anubhakushwaha @chhavip @aanchal07  if this is a valid UI related issues can I start working on this?
Thanks :)

**Comment by chhavip** [comment]
Its not possible to work on all thesse under one issue, please break down and create separate issues. Also check if some of the work has already been covered in other issues.

**Comment by HimanshuS01** [comment]
@chhavip I would like to ask one thing,
Instead of breaking and creating another issues, can I commit  separately for all the mentioned UI problem(that has not been covered in oher issues) in the same PR itself?
Thanks :)

**Comment by HimanshuS01** [comment]
@chhavip @anubhakushwaha @aanchal07 I have edited the above issue and created the separate issues #332 #333 respectively. Will soon send the PR.
_Thank you_

**Comment by chhavip** [comment]
Closing this issue.

**Comment by HimanshuS01** [comment]
@chhavip out of the three I have mentioned in the above issue, I have separated only the two one #332 and #333.
One is still pending on the above issue.
Please reopen the issue.
Thank you :)
