### ISSUE TITLE
Home Button goes away in Game Activity

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#309]
Home button and Replay button both goes away in Game Activity after first use. 
Though the replay button must be intentional but Home button should not go away as User can anyway go back by pressing the back key.

@chhavip @anubhakushwaha @aanchal07 Should I send PR for this ?

**Comment by anubhakushwaha** [comment]
@codingblazer So what do you propose as a solution to it?

**Comment by codingblazer** [comment]
@anubhakushwaha I think Home button should not go away. It will remain and work even if used more than once.
 Currently, it is being set to hide after first use.

**Comment by codingblazer** [comment]
@anubhakushwaha Should i proceed with this. Thanks

**Comment by codingblazer** [comment]
@chhavip @anubhakushwaha @aanchal07 Should I proceed with this ? Thanks. :-)

**Comment by aanchal07** [comment]
Closing this as redesigning work will be carried out in gsoc 2017.
