### ISSUE TITLE
Opening of PowerUpDemoContent

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#310]
I found that after following some patterns user can encounter PowerUpDemoContent which should not be shown.
**How to Regenerate** - After finishing the school scenario, Press Home button and the Press back.

<img src="https://cloud.githubusercontent.com/assets/13872065/22661069/f3c6222a-ecc9-11e6-9cd6-90e87579a46e.gif" height="400" width="200">

@chhavip @anubhakushwaha @aanchal07 Can i send PR for this so user can't see this?

**Comment by chhavip** [comment]
The entire database and the flow of scenarios needs to be fixed which will be done during the next development cycle, this will be handled then.
