### ISSUE TITLE
Multiple bugs in DressingRoomActivity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#311]
Following are some irregularities in DressingRoomActivity:-

1)After selecting the clothes in DressingRoomActivity , user presses the continue button to change the avatar. Now if we press **"back"**  button (two times) to return to the DressingRoomActivity ,avatar shown is not updated. We have to change our device orientation in order to see the updated avatar.

2)Similar problem arises as of above, after selecting the **hairs** from the DressingRoomActivity.

**GIF image for the above two cases**
![ezgif com-optimize 7](https://cloud.githubusercontent.com/assets/18090596/22704085/7816a15e-ed8c-11e6-86b3-37049d0aff5f.gif)

3)In Accessories in DressingRoomActivity , changes to avatar are not made according to the user's choice i.e.  if we pick **bag** and then press continue **glasses** are displaying instead of **bag**.
Similarly,if we select **glasses** and continue, **hat** is displaying instead of **glasses**
![ezgif com-optimize 6](https://cloud.githubusercontent.com/assets/18090596/22704052/5adf00c2-ed8c-11e6-9be7-9203843aef31.gif)

@chhavip @aanchal07 @anubhakushwaha can I work on this issue? Thanks :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 You can go ahead with the first two and infact it happens in case the user selects accessories as well, further the third point was covered during GCI and it would be merged soon.

**Comment by HimanshuS01** [comment]
sure @anubhakushwaha . I will handle that part too. Thanks :)
