### ISSUE TITLE
Overdraw in many activities in an application

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#312]
There is an overdraw in many activities in application that  causes performance and battery issues
Overdraw basically means that  system is drawing a pixel on the screen multiple times in a single frame of rendering.
Following are some activities  having an overdraw problem:-

```
1. StartActivity.java
2. AvatarActivity.java
3. AvatarRoomActivity.java
4. GameOverActivity.java
5. CompletedSceneAcivity.java
6. MapAcivity.java
7. SelectFeaturesAcivity.java
8. DressingRoomAcivity.java
9. AboutAcivity.java
10. ScenarioOverActivity.java
11. GameActivity.java
```

**Fix**
Removing unneeded backgrounds in different layouts(portrait & landscape) in the  activities mentioned above  as suggested in this [Google Developers](https://developer.android.com/topic/performance/rendering/overdraw.html) article.

@anubhakushwaha @chhavip @aanchal07 if this is an intended issue can I start working on this?Thanks :)

**Comment by HimanshuS01** [comment]
@anubhakushwaha @chhavip @aanchal07 can I work on this issue ?
_Thank you_  :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yes go ahead.

**Comment by HimanshuS01** [comment]
sure @anubhakushwaha . Will soon send the PR.
_Thank You_ :)

**Comment by aanchal07** [comment]
How has this improved performance/battery issues?

**Comment by aanchal07** [comment]
Closing this as there is no response as of now.
