### ISSUE TITLE
Progress is not saved

### ISSUE THREAD

**Issue by codeb1ooded** [systers/powerup-android#316]
If a user plays a game in some Scenario the progress is not saved for the game if user stops the game before finishing it.

Fix: 
Progress can be stored in database corresponding to each Scenario.

Also, I guess this can be combined with issue #315 so that database also keeps track of if scenario is over.

@anubhakushwaha @chhavip Can I work on this issue?

**Comment by chhavip** [comment]
This is a good suggestion but will be undertaken during the next development cycle and not currently.
