### ISSUE TITLE
Replay Button not works

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#317]
Replay button in following screen doesn't work.
![whatsapp image 2017-02-08 at 8 59 32 pm](https://cloud.githubusercontent.com/assets/13872065/22743887/9615942a-ee41-11e6-9cb5-ac9992b05c93.jpeg)

Fix : Currently, onClick of this button is not implemented and hence nothing happens. Will implement the onClick() which will replay the scenario from the begining.

@chhavip @anubhakushwaha Should I send PR for this ?

**Comment by jacqueline8711** [comment]
@codingblazer An issue for this already exists (#167) and I have already submitted a PR for this (#186).
 It has been approved but hasn't been merged yet.

**Comment by codingblazer** [comment]
@jacqueline8711 Sorry about that.

**Comment by jacqueline8711** [comment]
@codingblazer no problem :)
