### ISSUE TITLE
Scenarios starts playing again after School scenario

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#318]
Mutiple Bugs -

1. After playing last Scenario (the School Scenario), if we press continue, the Home scenario starts again though it was already visited. Demo is shown below -

<img src="https://cloud.githubusercontent.com/assets/13872065/22745097/61d1a79a-ee45-11e6-9281-a769ed785dad.gif" height="400" width="200">

Fix - The game completed screen ( " Wait till we upload more scenario" which is already present in project) should be shown after finishing School and Sex Scenario.

2. After visiting Hospital Scenario, the game completed screen appears though more scenarios are still pending.

Fix - Game Complete Screen should not be shown and scenario should play as usual. 

@chhavip @anubhakushwaha @aanchal07 Should I send PR for this ?

**Comment by anubhakushwaha** [comment]
@codingblazer The game was designed keeping in mind a certain sequence of scenarios,these bugs will be automatically resolved once #174 is implemented.You can close this issue.

**Comment by codingblazer** [comment]
@anubhakushwaha Can i solve #174 then ?

**Comment by chhavip** [comment]
Closing this issue.
