### ISSUE TITLE
Improper flow after the CompletedSceneActivity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#320]
In the **CompletedSceneActivity** if the user presses the store button -->then after buying anything from clothes, hair & accessories-->then after pressing the  **"continue"** button user is directed to the MapActivity.Now in MapActivity, after pressing the **home button** user is redirected again to the **CompletedSceneActivity** instead of **MainActivity**  .

![ezgif com-optimize 6](https://cloud.githubusercontent.com/assets/18090596/22749046/04d1f614-ee52-11e6-808b-506a58f97aa7.gif)

@anubhakushwaha @aanchal07 @chhavip Should I send PR for this?

**Comment by chhavip** [comment]
What is the proposed fix for this?

**Comment by HimanshuS01** [comment]
@chhavip right now on clicking the **home** button in **MapActivity** the following code is executing:-
```
homeButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();  
            }
        });
```
finish() method destroying the activity instance and is redirecting the user to the previous state.

**Fix**
This can be solved by launching an intent to **StartActivity** class like this:
```
homeButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent=new Intent(MapActivity.this,StartActivity.class);
                startActivity(intent);
            }
        });
```
This fix  has solved the issue. Can I send PR for the same ?

**Comment by HimanshuS01** [comment]
@chhavip @anubhakushwaha @aanchal07 can I send the Pr for the above fix?
_Thank You_

**Comment by aanchal07** [comment]
@HimanshuS01 Does this error still persist?

**Comment by aanchal07** [comment]
I tested the same and I am unable to produce the same bug. It works just fine.
