### ISSUE TITLE
UI Issues in small screens

### ISSUE THREAD

**Issue by Pankaj-Baranwal** [systers/powerup-android#325]
These are the screenshots taken on my test phone:
![landscape](https://cloud.githubusercontent.com/assets/16305338/22937909/1096290e-f300-11e6-89e5-dc96cfd1386f.png)
![portrait](https://cloud.githubusercontent.com/assets/16305338/22937910/10b7c082-f300-11e6-9d67-23e2284626a5.png)

The buttons for changing eyes and hair are not visible while the text on continue button and the clothes section disappears completely in landscape mode.

**Comment by Pankaj-Baranwal** [comment]
I can solve this issue by adding a ScrollView as the parent of the 4 sections.
And the text on buttons issue seems to have been solved by harshitagupta30 but it is still present in developer branch.

**Comment by chhavip** [comment]
@Pankaj-Baranwal , there is already ongoing work on the issue of text not being visible in landscape mode, please do not fix that in this issue as well. You are welcome to fix the issue of small screens, also send your PR against the develop branch itself.

**Comment by anubhakushwaha** [comment]
@Pankaj-Baranwal .Further attach screenshots in your PR once done.

**Comment by harshitagupta30** [comment]
@anubhakushwaha @chhavip Can I work on this issue? :)

**Comment by anubhakushwaha** [comment]
@Pankaj-Baranwal Any updates?

**Comment by Pankaj-Baranwal** [comment]
Issue has been resolved. Will send a pull request day after tomorrow.

**Comment by aanchal07** [comment]
Is anyone working on this issue?
