### ISSUE TITLE
Selection Buttons not visible in Accessories

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#326]
When i tested the app on Nexus One in portrait mode, the selection buttons in Accessories for Necklace and Glasses are not visible as shown below -

![screenshot_1487131613](https://cloud.githubusercontent.com/assets/13872065/22960605/19421f94-f365-11e6-8f03-2f6e70cc27eb.png)

Fix - The linear layout for these selection button (grey < > buttons) is not fitting in the screen and is overlapping with the left. Hence, its not discoverable. I have checked this fix by properly accommodating all UI elements and its working.
@chhavip @anubhakushwaha @aanchal07 Can i send PR for this ?

**Comment by anubhakushwaha** [comment]
@codingblazer Yeah you can proceed,further try testing throughout the app for Nexus One as there are many UI issues for this configuration.Further attach screenshots in your PR once done.

**Comment by codingblazer** [comment]
Hey, @anubhakushwaha I received your comment on this issue on my mailer but can't find it here. Should I proceed with this. Thanks.

**Comment by codingblazer** [comment]
Also, as you asked for other problems in small devices, I have created #328 #327 which covers the remaining issues with this configuration. Should I send a single PR for this, #328 ,#327 OR separate ones. 
 Thanks.

**Comment by codingblazer** [comment]
@anubhakushwaha Please review :-)

**Comment by aanchal07** [comment]
@codingblazer Separate PRs for different issues.

**Comment by codingblazer** [comment]
@aanchal07 Yeah sure. Will send a PR soon :-)
