### ISSUE TITLE
Supporting Different Screen Sizes in Store

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#327]
Following screens have a improper UI when tested on different screen sizes in Store Activity-

1. In Hair Screen, the Hair box and button are overlapping as shown below (same with clothes) -

![screenshot_1487131683](https://cloud.githubusercontent.com/assets/13872065/22961112/8840cf0e-f369-11e6-88ee-b657d2ca870b.png)

2. In Final Avatar Screen, the continue button is going out of bottom screen as shown -
![screenshot_1487131649](https://cloud.githubusercontent.com/assets/13872065/22961117/93dc591e-f369-11e6-8c40-dcfb1724fee8.png)

Fix - I will handle them by changing the dimensions in these screens for 4 size buckets as suggested in Android Docs - small, normal, large, x-large. 
@chhavip @anubhakushwaha @aanchal07 Can i please send PR for this :-)

**Comment by anubhakushwaha** [comment]
@codingblazer Yeah go ahead and attach screenshots of implemented work in your PR along with the device configuration you tested on.

**Comment by codingblazer** [comment]
@anubhakushwaha Yeah sure. Thanks
