### ISSUE TITLE
Enhancement: Justify text inside app

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#330]
**Summary**
The text inside app would be more appealing if is justified. 

**Observed Output**
![image](https://cloud.githubusercontent.com/assets/15179401/23025686/c74b23ae-f484-11e6-8291-18d6204c25fd.png)

**Desired Output**
![image](https://cloud.githubusercontent.com/assets/15179401/23025712/d7fab4ee-f484-11e6-9019-0b010a305d6b.png)

**Cons:**
Since this would require using a library the size of the apk would increase by 100 kb (i.e. from 2.18 mb to   2.28 mb)

**Comment by anubhakushwaha** [comment]
@top-gun007 I don't think it is such an important add-on w.r.t the appeal ,further adding another library for it is not desired as of now.I guess you can close this issue for now.

**Comment by top-gun007** [comment]
Closing it @anubhakushwaha and thanks for reviewing this issue.
