### ISSUE TITLE
HomeButton in ScneraioOverActivity is not aligned properly

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#332]
HomeButton in ScneraioOverActivity (left in the below image)should be aligned properly(i.e. at the extreme top right) as like in the GameMap activity(right)
![2e970f58-eaeb-11e6-88d1-8c81a39cac02](https://cloud.githubusercontent.com/assets/18090596/23039269/03d92afe-f4b3-11e6-9e19-5674dbc40021.png)

@chhavip @anubhakushwaha @aanchal07 (with reference to issue no #306) I will send the PR soon.
_Thank You_

**Comment by aanchal07** [comment]
@HimanshuS01 Please do not send PRs without approval.

**Comment by HimanshuS01** [comment]
sure @aanchal07 .I Will take care in mind and never do it again :)
_Thank You_

**Comment by aanchal07** [comment]
@HimanshuS01 Thank you. :)
