### ISSUE TITLE
White and bluish background in clothes ,hair and accessories png image

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#333]
There is a  slightly white and blue background present just at the edges of **clothes ,hair and accessories'' png in dressing_room.xml. This can be removed by using some image editor tool like photoshop etc. thereby giving the app more cleaner and clutter free look.

![0dc7461c-eaf0-11e6-8384-7cdfbe381de8](https://cloud.githubusercontent.com/assets/18090596/23039694/796b460c-f4b4-11e6-8be8-db001161ea93.jpeg)

@chhavip @anubhakushwaha @aanchal07 (with reference to issue no #306)I will soon send the PR.
_Thank you_

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yeah go ahead.

**Comment by HimanshuS01** [comment]
sure @anubhakushwaha . Will soon send the PR.
_Thank you_
