### ISSUE TITLE
UI issue in GameActivity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/powerup-android#335]
1)ListView in **GameActivity** is overlapping with the background image .Proper right_margin should be given in order to make UI more cleaner and clutter free

2)White background should not be present just behind the **replay** and **home** icon in GameActivity. Icon's background must be transparent. 
![whatsapp image 2017-02-04 at 2 14 14 pm 2](https://cloud.githubusercontent.com/assets/18090596/22617564/5eab9f80-eaee-11e6-86b7-fc386a1a6950.jpeg)

This issue is one of the part of #306 as suggested by  @chhavip to create the separate issue.
@anubhakushwaha @chhavip @aanchal07 If this a valid UI related issues can I start working on this?
Thanks :)

**Comment by HimanshuS01** [comment]
I proposed a fix for the above issue something like this:-
**Screenshot**

![device-2017-02-20-200642](https://cloud.githubusercontent.com/assets/18090596/23130045/fa10e69c-f7aa-11e6-97d7-08e9ae943096.png)

@chhavip @anubhakushwaha @aanchal07 If this seems to be good can I send PR for the same?

**Comment by HimanshuS01** [comment]
@anubhakushwaha @chhavip @aanchal07 Please have a look. :)
_Thank you_

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yes,go ahead.

**Comment by HimanshuS01** [comment]
Sure.  I will send the PR soon 
Thank you  :)
