### ISSUE TITLE
Enhancement: Easy access to store.

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#338]
**Summary**
When player needs to buy something from the store he/she has to first go to the completed scenarios and then go to store or from map.

**So just like all popular games user is allowed to buy things for the home screen as well as during game play therefore I propose store access be given in the following two screens as well** 

1.Here, when the user had just completed the scenario so he can directly go to the store screen instead of pressing back and again clicking on the store.
![image](https://cloud.githubusercontent.com/assets/15179401/23096373/1ce261e8-f641-11e6-8338-151a1929fc45.png)

2. In the start screen.
![image](https://cloud.githubusercontent.com/assets/15179401/23096378/416e6e76-f641-11e6-84d1-3e6274fd2a22.png)

**Comment by codingblazer** [comment]
@top-gun007 User can go to store through Map Activity :-)

**Comment by top-gun007** [comment]
Hi @codingblazer can you post a snap of which activity you are referring to.
_Thanks_

**Comment by codingblazer** [comment]
![s2](https://cloud.githubusercontent.com/assets/13872065/22857960/b9d0cadc-f0d6-11e6-8f86-57f6008d81af.jpeg)

**Comment by top-gun007** [comment]
Oh yeah that I know I thought you were referring to something else. 
_Thank you for being so responsive_

**Comment by codingblazer** [comment]
@top-gun007 Sure :-) Updated issue looks better now.

**Comment by top-gun007** [comment]
please review this issue @anubhakushwaha @chhavip @aanchal07 .
_Thank you_

**Comment by aanchal07** [comment]
@top-gun007 How do you suggest we add the access to store from these activities?

**Comment by top-gun007** [comment]
We can implement them in our app through:
1-Add store button for the app startup.
2-And add store button along side reply button and continue

**Comment by aanchal07** [comment]
@top-gun007 The store can be easily accessed from the map activity which can be accessed from the home screen on pressing the start button. I don't think adding extra buttons is required right now.
