### ISSUE TITLE
Bug: Power level meters vary on new game. 

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#339]
**Summary**
When the user starts a new game on some instances the power levels are not default. 
_like for eg in this case:_
![image](https://cloud.githubusercontent.com/assets/15179401/23096756/17fc3e1c-f649-11e6-8cce-bcaec4f23175.png)

**Comment by anubhakushwaha** [comment]
@top-gun007 What do you mean when you mention "default" value.

**Comment by top-gun007** [comment]
I mean the power meter should remain the same but in some instances of new game it is not.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Feb 23, 2017 at 6:10 PM +0530, "Anubha Kushwaha" <notifications@github.com<mailto:notifications@github.com>> wrote:


@top-gun007<https://github.com/top-gun007> What do you mean when you mention "default" value.

**Comment by anubhakushwaha** [comment]
@top-gun007 For now, they are just getting random values as of now, we will most probably have it's proper functioning in the next development cycle.You can close this for now.
