### ISSUE TITLE
Improvement in UI of Game Activity

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#344]
**Current Behaviour**

![screenshot from 2017-03-05 12 10 54](https://cloud.githubusercontent.com/assets/12701036/23585173/ef3a7016-019c-11e7-8f30-8ec85eefa05a.png)

![screenshot from 2017-03-05 12 11 37](https://cloud.githubusercontent.com/assets/12701036/23585174/ef3bb0f2-019c-11e7-8487-c4973aa2f149.png)

**Expected Behaviour**

![screenshot from 2017-03-05 12 00 30](https://cloud.githubusercontent.com/assets/12701036/23585145/fb4ca424-019b-11e7-9791-0428a8c94c78.png)

![screenshot from 2017-03-05 12 03 37](https://cloud.githubusercontent.com/assets/12701036/23585146/fba855d0-019b-11e7-9ddc-928fc68306d8.png)

@chhavip @anubhakushwaha @aanchal07 Can I send the PR for this? :+1:

**Comment by aanchal07** [comment]
@harshitagupta30 When you make the answer list the same color of the background, it does not give the impression of the scrollview.
