### ISSUE TITLE
UI Bugs in DressingRoomActivity in Landscape mode 

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#346]
1. Button text "continue" is not visible. 

![screenshot from 2017-03-06 00 58 51](https://cloud.githubusercontent.com/assets/12701036/23617416/11c655e8-02b3-11e7-9a24-7d5fcbe669fe.png)

2. The avatar appears distorted.

![screenshot from 2017-03-06 00 59 09](https://cloud.githubusercontent.com/assets/12701036/23617501/4f9e2dc8-02b3-11e7-940e-7249f8aeadf3.png)

@anubhakushwaha @chhavip Can you please review? :+1:

**Comment by codingblazer** [comment]
Hey @harshitagupta30 These issues already exist and PR for these are already sent.

**Comment by harshitagupta30** [comment]
You've not mentioned about the first point in that I suppose! :+1:

**Comment by codingblazer** [comment]
Hey #289 reported by you also contains the same bug in Avatar Selection but this is in Store Avatar Selection. I got mixed up :-) +1

**Comment by mahikaw** [comment]
@harshitagupta30 , is this issue still up?
