### ISSUE TITLE
Improvement in DressingRoomActivity.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#347]
**Current Behaviour**
Currently, if someone doesn't have enough points even then they can select the items and after clicking continue a toast appears `Not enough points`. 
![screenshot from 2017-03-06 00 59 26](https://cloud.githubusercontent.com/assets/12701036/23617753/2034fe26-02b4-11e7-816f-888a9434a4f0.png)

**Expected Behaviour**
Instead of this if someone has fewer points then while selecting item we can display same toast for user awareness. 
@anubhakushwaha @chhavip What's your thoughts on this? :)

**Comment by codingblazer** [comment]
Hey this issue is also duplicate and PR is already sent.

**Comment by harshitagupta30** [comment]
@codingblazer Can you please refer the issue number/ PR number?

**Comment by codingblazer** [comment]
@harshitagupta30  #170 #192 #319 
Though your solution is different but it won't be needed after this PR #192 gets merged :-)

**Comment by harshitagupta30** [comment]
@codingblazer Thanks :)
