### ISSUE TITLE
Reflecting power status and karma points in 'Current Emotion'

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#349]
'Current Emotion' attribute conveys  the abstract health of the player and hence is very useful. Currently the power_status_bar uses a static png image to show the 'Current Emotion' and nothing is reflected through it. Suggested behaviour - Change in Emotion if 'Health and power' and karma points drops beyond a threshold.
Current Emotion can include 'sad' ,  'anxious' , 'cheerful' e.t.c.
@chhavip @aanchal07  What do you think ?

**Comment by HimanshuS01** [comment]
hey @sashafierce This is a valid issue but it's a duplicate of #259 and #175 .
This needs to be resolved in the next development cycle of GSOC 2017.
kindly close this issue :)

**Comment by sashafierce** [comment]
Alright! :)
