### ISSUE TITLE
Adapt creator room to landscape mode

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#35]
The game is currently optimized for phones. 

Create a new creator room layout for horizontal displays (using qualifiers) so this works on tablets and phones in horizontal mode. Read more about screen qualifiers here: http://developer.android.com/intl/es/guide/practices/screens_support.html

**Comment by vasukiarunachalam** [comment]
I will work on this. In landscape mode, the images may have to be laid next to each other in one single line with left and right buttons below them. Shall I define screen qualifiers based on this ?

**Comment by alma-castant** [comment]
Place the different elements in the way you think best suits the horizontal format. Doesn't have to be the same way as the vertical one (and will probably not be). Define a layout using the qualifier for the horizontal display so this layout is automatically used when the phone is displayed this way

**Comment by vasukiarunachalam** [comment]
The layout for landscape mode needs the avatar buttons appear next to each other. So I created a layout-land/avatar_room.xml. And for 7" and 10" Tablets the button and margin sizes will increase , so defined respective sizes in values/dimens/xml, values-sw-600dp/dimens.xml etc.,

 While defining the buttons in avatar_room.xml, I noticed there is a id "eyeright" arrow button named as "newUserButton"  and also used in "AvatarRoom.java" . Should I leave it as it is or change it to "eyeRight" ? If yes then I need to edit "AvatarRoom.java" also. I am not sure if it was for some purpose or a typo ? Please let me know.

**Comment by alma-castant** [comment]
I need to look into this more carefully as soon as I have time. If you have any suggestions for it, feel free to explain them and create a PR ;)

**Comment by vasukiarunachalam** [comment]
It is just the naming convention. All buttons are named appropriately except "eyeRight" We can leave it as it is or change it, if we are strictly following naming conventions.

 It is named as "newUserButton" and also referenced in AvatarRoom.java in just one place. As I am making lot of changes in avatar_room.xml , I can include this change too. Please let m know.

**Comment by vasukiarunachalam** [comment]
Please confirm if the display is fine for vertical and horizontal as in following -

![avatar_room](https://cloud.githubusercontent.com/assets/14137360/11795547/dd18108a-a27c-11e5-8440-982b8ec31609.png)

![2015-12-14_1633](https://cloud.githubusercontent.com/assets/14137360/11796167/7834e00e-a280-11e5-981f-f22b2070c36f.png)

**Comment by alma-castant** [comment]
I would try to fit the content inside the brown box for a better look and feel. Do you have experience with Photoshop or similar tools? If you do, you could cut the sides of the image so the margins around the brown box are smallet and all the content fits inside ;)

**Comment by vasukiarunachalam** [comment]
I changed the background using photoshop. Please let me know if we can proceed with following layout -

![avatar_room](https://cloud.githubusercontent.com/assets/14137360/11861277/49e22494-a444-11e5-8974-f3a12520fcbd.png)
![2015-12-14_1633](https://cloud.githubusercontent.com/assets/14137360/11861279/4df1116c-a444-11e5-858d-a7b6a0ac0085.png)

**Comment by alma-castant** [comment]
Looks good (maybe in the horizontal one it could be slightly smaller so it doesn't overlap at all, but it's generally good :) )

**Comment by vasukiarunachalam** [comment]
I have submitted a Pull Request for this issue.

**Comment by vasukiarunachalam** [comment]
I was trying to squash all commits. There is a problem with untracked files (.dimen.xml.swp) . Can you guide me on this?

**Comment by vasukiarunachalam** [comment]
I solved the problem and submitted a new pull request for this issue.

**Comment by vasukiarunachalam** [comment]
I resolved the merge conflicts and committed again.
