### ISSUE TITLE
'Current Scene' text view in ScenerioOverActivity misleading

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#350]
Currently 'Current Scene: x' shows the completed scenario 'x' and clicking ' continue' button leads to next scenario (say 'y') which seems confusing.
One of these slight modifications in ScenerioOverActivity.java  can be done : 
- Changing 'Current Scene: x' to 'Completed scene: x' 
- Changing 'Current Scene: x' to 'Current/Next scene: y'

**Comment by aanchal07** [comment]
@sashafierce Since its the concluding screen after each scenario, it depicts the point for that particular scenario, hence the name current scene.

**Comment by sashafierce** [comment]
@aanchal07  And after that the next scenario abruptly appears , I think it would be better to have an info dialogue before every scenario or the 'current scenario' can be converted

**Comment by aanchal07** [comment]
@sashafierce The next scenario appears only when you click on continue button and not abruptly. Would you like to brief on exactly why the name "current scenario" is confusing. Thank you.

**Comment by sashafierce** [comment]
@aanchal07 Okay I'll try to make some mocks to clarify.

**Comment by aanchal07** [comment]
@sashafierce Great!
