### ISSUE TITLE
Changing button color when pressed.

### ISSUE THREAD

**Issue by shreyans29** [systers/powerup-android#353]
I think the app would have a better feel to it if we can change the button color when it is pressed by a very little shade.  

The buttons to be changed include 
Resume 
New User 
About
Replay 
Continue
![17357396_1382353265160891_991215051_o](https://cloud.githubusercontent.com/assets/8592568/24036835/709c8904-0b21-11e7-9c05-6652c8e32bbb.png)

**Comment by shreyans29** [comment]
Can I submit a PR for this ?

**Comment by aanchal07** [comment]
@shreyans29 Can you send screenshot of what the screen would look like when button will be pressed, ie how will the change of color look/ show up.
