### ISSUE TITLE
Convert activities to fragments

### ISSUE THREAD

**Issue by Siddiq200** [systers/powerup-android#354]
Every screen is a single activity which makes our app slower, it won't be good user experience. 

If we use fragments instead of activities it will be faster than that which will make our app faster than the first one.

If this is a valid issue can I send PR ?

**Comment by aanchal07** [comment]
@Siddiq200 Since converting all activities to fragments is a huge work, we will need to discuss it thoroughly and this could be taken up in GSoC.

**Comment by aanchal07** [comment]
@codingblazer Do you want to take this up?

**Comment by codingblazer** [comment]
@aanchal07 I have some doubts on whether this should be taken or not. I will proceed on this after discussing it with you in this week's meet.

**Comment by codingblazer** [comment]
Closing after discussing with the team. Not required for our project as each activity contains too many drawables.
