### ISSUE TITLE
first Question answer screen shows At end before result screen 

### ISSUE THREAD

**Issue by Siddiq200** [systers/powerup-android#356]
first Question answer screen showsUp 
for a moment At the end, before result screen.

let say on this screen I click "Let's head inside"

##Screen1
![sex](https://cloud.githubusercontent.com/assets/26488668/24079555/909e1916-0cac-11e7-9c07-6680e6cc1c30.JPG)

this screen shows up for a moment
##Screen2
![fst](https://cloud.githubusercontent.com/assets/26488668/24079575/e067e59e-0cac-11e7-8a1c-d48d335e81d8.JPG)

before this

##Screen3
![result](https://cloud.githubusercontent.com/assets/26488668/24079580/efc68c48-0cac-11e7-83ad-7609cb62ff4e.JPG)

But ##Screen2 should not shown

**Comment by mahikaw** [comment]
@Siddiq200 This issue has been reported earlier by #239 . Also it will be better if you look into all the previous issues before reporting one. :smile:

**Comment by aanchal07** [comment]
Closing this as redesigning work will be carried out in gsoc 2017.
