### ISSUE TITLE
Landscape UI Problems (tablets or large screens)

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#357]
1) The buttons for choosing the new avatar(avatarroom.xml) are not there. The text on the Continue button is missing,
The alignment of the page is improper as shown below :
![avatarroom_l](https://cloud.githubusercontent.com/assets/22029744/24083600/0f433910-0d00-11e7-937c-b6bdbc4008de.png)
 
2) The activity for selection of features(activity_select_features.xml) does not appear properly as shown below :
![activityselectfeature_l](https://cloud.githubusercontent.com/assets/22029744/24083593/f1187f40-0cff-11e7-8204-1d97ea1a4fea.png)

@aanchal07 @dhara04 @chhavip Can I start working on this issue?

**Comment by codingblazer** [comment]
Hey @BaaniLeen, almost all of these issues are reported in past and have their PR's unmerged. Those PR's are general solution i.e they will solve these issues for all screen sizes.
Please have a look at them to avoid doing the same work again :-) :-)

**Comment by BaaniLeen** [comment]
Hey @codingblazer , I have had a look at all the past issues but not at the unmerged PRs.....Point taken...!
Yet, I cannot find an open issue or a PR corresponding to the first two points - changes in avatar_room.xml and activity_select_features.xml (Issue #55 has been resolved by PR #71, yet the problem persists on tablets).
@aanchal07 @dhara04 Kindly approve the issue so that I can start working on the same. :-)
Thanks!

**Comment by mahikaw** [comment]
@BaaniLeen It will be great if could you  edit the issue and remove the redundant ones.

**Comment by BaaniLeen** [comment]
@mahikaw Sure..! :)

**Comment by BaaniLeen** [comment]
@mahikaw Sure..! Done :)
