### ISSUE TITLE
Potrait UI Problems (Tablets or large screens)

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#358]
1) ![avatarroom_p](https://cloud.githubusercontent.com/assets/22029744/24127426/8fe838fe-0dfa-11e7-9e7c-9844cd2cbe18.png)
In the avatarroom.xml, the navigation buttons to choose between the various features do not appear. Also the orientation of the various elements across the page is not proper.

2) ![activity](https://cloud.githubusercontent.com/assets/22029744/24127635/3de0d474-0dfc-11e7-9c48-a1e2662ac74d.png)
The Continue and resume button, rather than appearing ta the bottom, appear above the character.

3) ![gameactivity_p](https://cloud.githubusercontent.com/assets/22029744/24127469/db6a5f8c-0dfa-11e7-807c-6f45b843ab12.png)\
The Characters along with the dialogue box do not appear in the middle of the screen. Also, the text is not aligned properly and is thus, not visible.

4) ![activityselectfeatures](https://cloud.githubusercontent.com/assets/22029744/24127596/d502d39e-0dfb-11e7-806a-f87614b78da0.png)
The four selection boxes are clustered to the top. They should be centrally aligned and evenly spaced.

5) ![avatar_p](https://cloud.githubusercontent.com/assets/22029744/24127663/81bab0f2-0dfc-11e7-9ee3-726f44754daf.png)
)
The entire content should be placed at the center of the screen (centrally aligned) rather than being aligned to the top of the page.

@aanchal07 @dhara04 @chhavip Can I work on this and make a PR for the same?

**Comment by aanchal07** [comment]
@BaaniLeen How do you plan to solve this? Did you test on any other device too?

**Comment by BaaniLeen** [comment]
@aanchal07 I have tested the app on multiple devices of various sizes. It works well on all devices tested uptil Nexus 6 (5.96") .The app faces these issues for 7'' devices or devices with greater size (tablets).
We can use configuration qualifiers like layout-xlarge and layout-xlarge-land for the making a design which effectively utilises the screen space we have on the tablet (Or we can enable the screen compatibility mode, but that might lead to pixelation and blurring and is generally not recommended.)
Kindly give in your suggestions and approval so that I can start working on the same.. :)
Thanks!

**Comment by aanchal07** [comment]
@BaaniLeen Would you like to carry out this issue and #357 together?

**Comment by BaaniLeen** [comment]
@aanchal07 As you suggest maam :)
