### ISSUE TITLE
Inconsistency in font types and button dimensions at various places

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#360]
The screenshots below portray the inconsistency:- 

![device-2017-03-21-124701](https://cloud.githubusercontent.com/assets/21010060/24136440/d75b83fa-0e34-11e7-99e8-9154b802c5c6.png)

![device-2017-03-21-124803](https://cloud.githubusercontent.com/assets/21010060/24136455/dd19f33a-0e34-11e7-8f94-f03abc4a5be6.png)

@aanchal07 @chhavip can I go ahead and fix this?

**Comment by mahikaw** [comment]
A gentle reminder.

**Comment by aanchal07** [comment]
@mahikaw Go ahead. Also attach the screenshots of changed UI in the PR.

**Comment by mahikaw** [comment]
I am GSoC aspirant.

**Comment by aanchal07** [comment]
@mahikaw Please send an updated PR.
