### ISSUE TITLE
Avatar not updated after shopping at store in Game Activity 

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#361]
The avatar doesn't get updated after buying in the store.

before buying:-
![device-2017-03-21-205218](https://cloud.githubusercontent.com/assets/21010060/24156051/7d99eca2-0e7b-11e7-88e2-fd824112bac3.png)

After buying:-
![device-2017-03-21-205350](https://cloud.githubusercontent.com/assets/21010060/24156156/c74938b2-0e7b-11e7-936c-3bd59b758741.png)

![device-2017-03-21-210619](https://cloud.githubusercontent.com/assets/21010060/24156225/08ed489e-0e7c-11e7-9194-cad422c993a7.png)

@aanchal07 @chhavip Can I go ahead with a PR?

**Comment by aanchal07** [comment]
@mahikaw You are right, the avatar has not been updated yet in the game_activity. We are gonna take it up in GSoC.

**Comment by mahikaw** [comment]
Oh. Okay. That's great, you could put it on hold maybe. :)

**Comment by Michellurito** [comment]
Could I help with this issue? I am also a GSoC aspirant.

**Comment by codingblazer** [comment]
Fixed via #379
