### ISSUE TITLE
[Enhancement]  Store items replace the previous items

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#369]
Once the user purchases something new using karma points the previous items get lost. To regain the previous items they need to be re-purchased. (eg Suppose I buy green clothes and then next time red clothes, now if I want my avatar to have green clothes, I’ll have to re-buy them)
This is incorrect, as the user should be able to use all the items which he/she has purchased anytime irrespective of whether they have purchased something new or not. 
I think we can add something like a 'Bag' where the user can view and switch between all what he/she has purchased.

**Comment by mahikaw** [comment]
This is similar to #361All related issues are to be taken up in the upcoming GSoC cycle :smile:

**Comment by codingblazer** [comment]
@mahikaw  It's not even a valid issue. We have a "Paid" Text shown for already purchased items. 
@yatna Is it happening for some specific case ?

**Comment by yatna** [comment]
@mahikaw No this one is different. #361 is a bug , where the avatar is not being updated, this is more of a enhancement to the feature

**Comment by mahikaw** [comment]
@yatna I understand it is an enchancement, however I am unable to see how it can be worked upon before fixing that bug #361, which will be done only during GSoC as stated by @aanchal07

**Comment by codingblazer** [comment]
@mahikaw This is completely different from #361 
@yatna This is already included feature in current codebase as shown below - 

<img src="https://cloud.githubusercontent.com/assets/18090596/25250087/ea831974-2631-11e7-96f6-a1a5afb76936.jpeg" height="400" width="200">

**Comment by mahikaw** [comment]
@codingblazer what @yatna meant to say here was that if the user want to change the clothes of the avatar to a previous one that the user had bought, it is not possible as of now.
All this can be incorporated only when the user avatar gets updated permanently or there exists a closet which contains all the items bought.
For this we need to wait for the GSOC period to start.

**Comment by codingblazer** [comment]
@mahikaw We don't need to wait for it. It's already there as shown below :-))

**Comment by yatna** [comment]
@mahikaw Thanks for explaining :-) also I just opened this issue because I feel that this feature should be incorporated. I understand that this can be implemented only after fixing #361. I just wanted to put the feature in the issue list

**Comment by mahikaw** [comment]
That's thoughtful of you. Thanks for going through the app in such great detail. I'm sure @aanchal07 will go through this as soon as she can.

**Comment by codingblazer** [comment]
@yatna Can you explain why this feature is different from the "Paid" text feature we are already having. We can select the "Paid" item and continue. It won't deduct any point.

**Comment by yatna** [comment]
@codingblazer A Paid label for purchased items is there, its fine. But still we are not being able to switch to those without karma points.

**Comment by codingblazer** [comment]
@yatna Your issue was however about adding this existing feature. That's why I corrected you :-)

The bug you mentioned is valid but it will be solved with #361 because the check condition for points will be corrected in that issue which will correct this bug automatically.
Thanks :-)

**Comment by yatna** [comment]
@codingblazer Its fine. :-) Even I did not thought that the paid feature can be an alternative for the 'closet' feature. 
However , I feel that having a 'Bag'/'Closet' where the user can see and switch between all what he/she has purchased will be a better alternative. The user will be able to go the 'Bag' whenever he/she wishes, as currently we can go to the store only upon completion of a scene etc So, I will remain this issue open.

**Comment by codingblazer** [comment]
@yatna Yeah sure :-)

**Comment by Divya063** [comment]
Hi, I would like to work on this.

**Comment by codingblazer** [comment]
Hi @Divya063, this issue is not required anymore. New Designs were developed which have this feature already. Please pick some other issue.

**Comment by Divya063** [comment]
@codingblazer Thanks for the response, can you recommend some good first bugs to start with?

**Comment by codingblazer** [comment]
@Divya063 You can pick #462 if you want. If you are looking for more beginner issue, you can create any **lint** based issue yourself.

**Comment by Divya063** [comment]
@codingblazer Thanks, I would work on this issue #462

**Comment by codingblazer** [comment]
@Divya063 Please comment the same in issue #462 to claim it.
