### ISSUE TITLE
[Enhancement] Automatic document generation

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#370]
Integration of 3rd party libraries like doxygen will let us automatically generate neat and detailed documentation of the entire application. Also any new functions added will automatically be documented which will save developer's time in writing documentation.

**Comment by mahikaw** [comment]
Sounds like a great idea. @aanchal07 What do you think?

**Comment by codingblazer** [comment]
@yatna Good suggestion. But don't you think other options like JavaDocs will be better considering it is inbuilt in Android Studio and won't require any 3rd party dependency. (Leaving aside diagrams and stuff, it can do most of the things as Doxygen). What do you suggest?

**Comment by aanchal07** [comment]
I think a personally written documentation by the developer would include more a lot information regarding what all issues he faced and how to overcome the same, etc.
