### ISSUE TITLE
[Bug] Avatar's initial possesstions not being marked as 'Paid'

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#371]
The items (Clothes, Hair, Accessories)chosen by the avatar during new user creation are not being marked as 'Paid' in the store. This means that they can be re-purchased, which is a bit incorrect since the avatar already possesses them

**Comment by aanchal07** [comment]
@yatna Would you like to work on this?

**Comment by aanchal07** [comment]
@codingblazer As @yatna isn't replying, you will have to take this up

**Comment by codingblazer** [comment]
Sure, I am on it !!
