### ISSUE TITLE
Abrupt message view after scenario completionn

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#372]
![device-2017-04-21-015730](https://cloud.githubusercontent.com/assets/21010060/25251878/8c9a6f22-2638-11e7-9d9d-de5efa6b3d0b.png)
This shows up after the scenarios gets over, leaving the user confused about what to do next.
@aanchal07  we could add the power up button or buttons for the map and store activity, just like everywhere else so as to build context.
I am willing to work on it. Please tell me if this is intended.

**Comment by BaaniLeen** [comment]
@mahikaw When a scene gets over, the user gets an option to go back to the map and move to another scene, while when a scenario gets over, the user is asked to wait until new questions are put up as the game is over now. The UI for the scenes seems consistent with the aim of each scene :)

**Comment by mahikaw** [comment]
@baaniLeen
Generally the completed scenario comes up even when some scenarios are left. In that case the user has to go back and play them.
Also, even if the game is completed, it shouldn't lead to an end. There can always be options like start a new game, replay and shop at the store, in this activity. This will help enhance the app's context and user-friendliness.

**Comment by BaaniLeen** [comment]
@mahikaw The issue of the wrong screen coming up at the wrong time has been already addressed in issue #315 ... Please have a look at it..!
Agreed on the second point :)

**Comment by mahikaw** [comment]
@BaaniLeen the first point that I mentioned above was just to take care of the bug in the app in it's current, however eventually a major change in the database and scenarios needs to be taken up in the upcoming GSoC cycle :smile:

**Comment by codingblazer** [comment]
@mahikaw @BaaniLeen I think we can add a button to New level or button to mini games in this scene (yes, in upcoming GSOC cycle). What do you suggest?

**Comment by BaaniLeen** [comment]
@codingblazer Seems like a great idea...! We can surely do that...! 🙂

**Comment by codingblazer** [comment]
@BaaniLeen Yeah, in addition to that !!

**Comment by mahikaw** [comment]
Sounds great. @codingblazer @BaaniLeen , thanks for your inputs! :smile:

**Comment by aanchal07** [comment]
We can carry this out right now and add a button to direct to map screen. Would anyone like to work on it?

**Comment by codingblazer** [comment]
Fixed
