### ISSUE TITLE
Hiding resume button on first time opening the app

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#373]
**Actual Behaviour**
Currently, when user first time installs the app and opens it then along with new user button, resume button is also visible. 

![screenshot from 2017-04-23 16 41 40](https://cloud.githubusercontent.com/assets/12701036/25313003/cb764736-2843-11e7-8956-dc889270c188.png)

**Expected Behaviour**
In my opinion, we can hide the resume button if the app is opened for the first time.

**Steps to reproduce it** 
Fresh installation of the app.

**Ways to resolve it**
We can use shared preferences to check if the application is the first time launched and if the condition is true we can hide the resume button and if the user opens it again it will be made visible.

@anubhakushwaha @chhavip @aanchal07 What your thoughts on this?

**Comment by top-gun007** [comment]
@harshitagupta30 can you post a screenshot of that.
Because in mine it shows start game instead of resume.

**Comment by harshitagupta30** [comment]
@top-gun007 Sorry my bad! on re-running it showed me resume due to which I got confuse. Thanks for letting know! :+1: Closing issue :+1:
