### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by kimhwins** [systers/powerup-android#374]
The current UI for scenarios could be updated to be cleaner and more space efficient (for example, there's the sprite talking and then a static image in the footer, and the footer itself takes up space that could be used to space out the dialogue more).

I've attached a draft of what I envisioned for a UI update--I sketched this very quickly in my proposal :) Karma is visually represented as stars, and pressing the arrow below the Karma counter would show the player's points in their abilities. Any conversation dialogue would occur in the textbox, which is semi-transparent, with the name changing according to speaker. There's a headshot of the player that changes expressions based on dialogue and/or the emotion (just like there was emotion in the footer). Other people in the conversation have full body sprites in the background. Please excuse my placeholder stick figures for the sprites!

![gui draft 1](https://cloud.githubusercontent.com/assets/22511190/25317729/2420b06c-284c-11e7-8f07-74a46f2b89da.png)

**Comment by codingblazer** [comment]
@kimhwins Hey, it looks good. Can you tell what you mean by this -
> Other people in the conversation have full body sprites in the background. 

 I used the piggy bank to show karma points in my proposal. :-)

**Comment by kimhwins** [comment]
@codingblazer hey, thanks! I meant like, if there are other characters in the scenario who are also talking, they'll have full body sprites (sort of like the full body stick figure I showed behind the options boxes?), if that makes sense, as opposed to the headshot the player's avatar has. 

A piggy bank works too!! I think any visual interpretation of karma is a good change :)

**Comment by kimhwins** [comment]
Added a sketch of a redesign of Marco that I included in my proposal into the UI screenshot so you can see the transparency :) 
![gui draft 2](https://cloud.githubusercontent.com/assets/22511190/25325843/7b3adc70-289b-11e7-8d4d-461c4467702f.png)

**Comment by codingblazer** [comment]
@kimhwins That's awesome. Whoever works this GSOC, I would love to see this type of thing.

**Comment by top-gun007** [comment]
Yeah agree with @codingblazer here enhancement work should be done during GSOC timeline.

**Comment by aanchal07** [comment]
@kimhwins This looks great! We can discuss the same with @MeepyMay and @codingblazer and go ahead with it.
