### ISSUE TITLE
Back Functionality not working properly

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#375]
Currently, the user can go back to previous question in the game and change its answer. 
To be precise, the user can keep on pressing back button and go back to already visited scenario as well.

This bug is happening after some recent code changes in the codebase. @aanchal07 Can I work on this?

**Comment by aanchal07** [comment]
@codingblazer Does this error still persist?

**Comment by codingblazer** [comment]
Yes, it does !! I will look at this soon after exams.

**Comment by codingblazer** [comment]
**Issue #375  Back Functionality error** - Since issue wasn't present earlier, I rollbacked PRs one by one to identify the faulty one #331

**Comment by Divya10** [comment]
can i work on this issue,

**Comment by MKDEVELOPEMENT** [comment]
can i work on this

**Comment by akshaynexus** [comment]
i have fixed the issue https://github.com/systers/powerup-android/pull/955

**Comment by geekanamika** [comment]
I am closing it as Issue has been resolved through PR #719
