### ISSUE TITLE
User completes the Home Scenario.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#382]
## Description
As an player, 
I want to complete the "Home" scenario, 
so that I can earn karma points and buy new things!

## Mocks
TBD

## Acceptance Criteria
- User interacts with an NPC.
- Once conversation is finished, user is notified with the # of karma points earned.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

## Estimation
- 2 Hours

**Comment by codingblazer** [comment]
Done via #389
