### ISSUE TITLE
Mentors create issues for all stages' scenarios.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#383]
## Description
As an Student,
I want to view all the work I need to do,
so that I can manage my time and program with weekly reports on time.

## Mocks
N/A

## Acceptance Criteria
- Student can view all user stories in the issues list.
- User stories follow this format.
- Includes labels, assignees, and added to the "Student Tasks" Project board.

## Definition of Done
- All 5 scenarios are covered for each stage (Library, Store, Hospital, School, and Home). 
- There are 2 scenarios for Home (1 - party scene, 1 - sexual assault scene).

## Estimation
- 1 Hour

**Comment by codingblazer** [comment]
@dhara04 @aanchal07 Should we close this now ?
