### ISSUE TITLE
Mentors perform a code review on the 1st week's PR. (May 30 - June 05)

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#384]
## Description
As an Student, 
I want to see where I can improve in my code, 
so that I can manage grow my technical strengths.

## Mocks
N/A

## Acceptance Criteria
- Checklist below is complete and included in a comment on this issue. (Will transfer to Wiki later.)
- Feedback is given to the developer. (Comment on the PR.)

## Definition of Done
	 Complete this Code Review Checklist (Adapt as Needed).

### General
- Does the code work? Does it perform its intended function, the logic is correct etc.
- Is all the code easily understood?
- Does it conform to your agreed coding conventions? These will usually cover location of braces, variable and function names, line length, indentations, formatting, and comments.
- Is there any redundant or duplicate code?
- Is the code as modular as possible?
- Can any global variables be replaced?
- Is there any commented out code?
- Do loops have a set length and correct termination conditions?
- Can any of the code be replaced with library functions?
- Can any logging or debugging code be removed?

### Security
- Are all data inputs checked (for the correct type, length, format, and range) and encoded?
- Where third-party utilities are used, are returning errors being caught?
- Are output values checked and encoded?
- Are invalid parameter values handled?

### Documentation
- Do comments exist and describe the intent of the code?
- Are all functions commented?
- Is any unusual behavior or edge-case handling described?
- Is the use and function of third-party libraries documented?
- Are data structures and units of measurement explained?
- Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’?

### Testing
- Is the code easily testable? i.e. don’t add too many or hide dependencies, unable to initialize objects, test frameworks can use methods etc.
- Do tests exist and are they comprehensive? i.e. has at least your agreed on code coverage.
- Do unit tests actually test that the code is performing the intended functionality?
- Are arrays checked for ‘out-of-bound’ errors?
- Could any test code be replaced with the use of an existing API?

## Estimation
- 1.5 Hours

**Comment by aanchal07** [comment]
Done.
