### ISSUE TITLE
User completes the Hospital Scenario

### ISSUE THREAD

**Issue by dhara04** [systers/powerup-android#385]
**Description**
***
As a player,
I want to complete the "Hospital" scenario,
so that I can earn karma points and buy new things!

**Mocks**
***
![image](https://user-images.githubusercontent.com/1497011/26889895-47581076-4bcd-11e7-9803-e8fa09f03409.png)

**Acceptance Criteria**
***
User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**
***
Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
***
2 Hours

**Comment by codingblazer** [comment]
Done via #389
