### ISSUE TITLE
User completes the Library scenario

### ISSUE THREAD

**Issue by dhara04** [systers/powerup-android#386]
**Description**
***
As a player,
I want to complete the "Library" scenario,
so that I can earn karma points and buy new things!

**Mocks**
***
![image](https://user-images.githubusercontent.com/1497011/26890310-c5a37bf4-4bce-11e7-9143-9633f5db1151.png)
Puberty Research

**Acceptance Criteria**
***
User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**
***
Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
***
2 Hours

**Comment by codingblazer** [comment]
Done via #389
