### ISSUE TITLE
User completes School scenario

### ISSUE THREAD

**Issue by dhara04** [systers/powerup-android#387]
**Description**
***
As a player,
I want to complete the "School" scenario,
so that I can earn karma points and buy new things!

**Mocks**
***
![image](https://user-images.githubusercontent.com/1497011/26890588-acf44344-4bcf-11e7-8d9a-4b629774d576.png)
Sex scene

**Acceptance Criteria**
***
User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**
***
Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
***
2 Hours

**Comment by codingblazer** [comment]
Done via #389
