### ISSUE TITLE
User completes Store scenario

### ISSUE THREAD

**Issue by dhara04** [systers/powerup-android#388]
**Description**
***
As a player,
I want to complete the "Store" scenario,
so that I can earn karma points and buy new things!

**Mocks**
***
Borrow the Phone
![phone-borrow](https://user-images.githubusercontent.com/2440938/26978912-1a50b3ce-4cfb-11e7-92c9-38096c9e86ca.png)

**Acceptance Criteria**
***
User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**
***
Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
***
2 Hours

**Comment by codingblazer** [comment]
@dhara04 @aanchal07 This sounds confusing to me. Isn't Store for buying items? How are we planning to add "Borrowing phone" scenario to that? :-)

**Comment by Dilu9218** [comment]
This should be closed right?

**Comment by codingblazer** [comment]
@Dilu9218 Yes :-)
