### ISSUE TITLE
User completes the Home Scenario -2

### ISSUE THREAD

**Issue by aanchal07** [systers/powerup-android#399]
**Description**
***
As a player,
I want to complete the "Home" scenario-2,
so that I can earn karma points and buy new things!
This scenario is to be completed after the first five stages.

**Mocks**
***
![image](https://user-images.githubusercontent.com/13906284/27000437-9c508f96-4dcf-11e7-8a3b-6864afafcca9.png)

**Acceptance Criteria**
***
Also add a warning dialogue before the scenario since it addresses a sensitive issue.
User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**
***
Passes all regression tests.
Passes testing per acceptance criteria items.
Able to show feature in demo.

**Estimation**
***
2 Hours

**Comment by codingblazer** [comment]
Done via #389
