### ISSUE TITLE
Wrong functionality of Home button in Map screen

### ISSUE THREAD

**Issue by aanchal07** [systers/powerup-android#402]
## Description
As an player, 
On clicking the home button in the map screen, I want to go to the home screen.

## Mocks
NA

## Acceptance Criteria
On clicking home button icon, user goes to home screen.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by android team.
- Able to show feature in demo.

## Estimation
- 2 Hours

**Comment by aanchal07** [comment]
#404 Merged

**Comment by codingblazer** [comment]
@kimhwins @aanchal07  There is no Home button in the new Map UI. Should we remove home button?

**Comment by aanchal07** [comment]
@kimhwins Can you add the home button to the Map Screen?

**Comment by kimhwins** [comment]
@aanchal07  @codingblazer yes! would it be more convenient to have the home button on the same file as the map or as a separate asset?

**Comment by codingblazer** [comment]
@kimhwins As a separate asset will work :-)

**Comment by Dilu9218** [comment]
@codingblazer Agreed.

**Comment by kimhwins** [comment]
@codingblazer for now you can use this temporary home button--it's the original one, I just made it a lighter color for visibility on the map. I'll design a new home button when I design the title screen so they have some consistency :) 

![home button temp](https://user-images.githubusercontent.com/22511190/27876297-8d9f4e10-6184-11e7-95eb-5e810c06a878.png)

**Comment by codingblazer** [comment]
@kimhwins Great !! Try keeping the dimensions same as this 😃
