### ISSUE TITLE
Developer needs UI elements for the Home Scenario -1

### ISSUE THREAD

**Issue by Dilu9218** [systers/powerup-android#407]
## Description
As a developer,
I want to see the UIs of home party scene,
so that I can code the stage Home Scenario- 1.

## Mocks
N/A

## Acceptance Criteria
-Background

## Definition of Done
-Passes user testing per acceptance criteria items.
-Featured in design meeting.
-Approved by UI team. (Dil & May)

**Comment by kimhwins** [comment]
@MeepyMay are we proceeding with this? iirc you mentioned how it didn't seem very plausible for a young girl to throw a house party?
