### ISSUE TITLE
Developer needs UI elements for the  School scenario

### ISSUE THREAD

**Issue by Dilu9218** [systers/powerup-android#409]
## Description
As a developer,
I want to see the UIs of  School scenario,
so that I can code the stage  School scenario.

## Mocks
N/A

## Acceptance Criteria
-Background
-Redesign existing UI elements for avatar and Marcello.
-Redesign UI element for School

## Definition of Done
-Passes user testing per acceptance criteria items.
-Featured in design meeting.
-Approved by UI team. (Dil & May)

**Comment by kimhwins** [comment]
I completed the background and UI for the school a couple weeks ago :) just have to finalize the avatar/marco sprites
![gui 3 cg marco 2](https://user-images.githubusercontent.com/22511190/27344936-10da0930-55b6-11e7-905a-f66760a55ac7.png)

**Comment by codingblazer** [comment]
@kimhwins That looks so nice. Great work!!

**Comment by codingblazer** [comment]
@kimhwins When you are designing the conversation boxes, make them a nine-patch image. Since the amount of conversation will be different, nine patch will be best to use.

**Comment by kimhwins** [comment]
@codingblazer  thank you!! I'll send over a nine-patch version by next week :)
