### ISSUE TITLE
Setup Codacy Bot

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#412]
Codacy Bot helps in reviewing the codebase. It will reduce work for mentors as well as be helpful for developers to learn best practices. It won't have any effect on the code.

**Comment by aanchal07** [comment]
Go ahead. Do you need any help from my side?

**Comment by codingblazer** [comment]
@aanchal07 I have not yet deployed codacy bot yet. I am waiting for approval from @MeepyMay. I will get back to you after approval :-)

**Comment by MeepyMay** [comment]
@codingblazer @aanchal07 It's been approved.

**Comment by codingblazer** [comment]
@MeepyMay Sure, i will look into this :-)
