### ISSUE TITLE
Remove portrait screen layout

### ISSUE THREAD

**Issue by aanchal07** [systers/powerup-android#413]
## Description
As an player, 
I want to see only the landscape mode of the application.

## Mocks
NA

## Acceptance Criteria
The application operates in landscape mode only.

## Definition of Done
- No portrait layout remains.
- Passes testing per acceptance criteria items.
- Approved by android team.
- Able to show feature in demo.

## Estimation
- 1/2 days

**Comment by codingblazer** [comment]
Merged via #414
