### ISSUE TITLE
Avatar not properly shown in Final Avatar Screen

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#440]
I tested app on multiple devices and avatar is 
1) Not scaling properly on large screen sizes.
2) There is no proper alignment of avatar components in some screens.

![whatsapp image 2017-07-04 at 20 07 06](https://user-images.githubusercontent.com/13872065/27834563-093b8e8e-60f5-11e7-85af-ffdac4034534.jpeg)

@aanchal07 Should we wait for new avatar UI or should i fix this ?

**Comment by aanchal07** [comment]
@kimhwins How long would it take you to design the new avatar? If not long then we can wait for the new designs else you can work on it now.

**Comment by kimhwins** [comment]
@aanchal07 May and I are still figuring out the best way to test different styles, so I think it will be a few weeks before the new avatar is finished!

**Comment by codingblazer** [comment]
@kimhwins Sure, I will fix this in next week then !!

**Comment by codingblazer** [comment]
The issue has been fixed and new Pull request #471 is sent with new designs.

**Comment by geekanamika** [comment]
@codingblazer This issue can be closed (Since, code in PR has been merged already), right ?

**Comment by MeepyMay** [comment]
Yes @geekanamika 👍
