### ISSUE TITLE
Game Activity Listview has extra white space 

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#441]
There is unnecessary extra white space in listview which shows answers to user as shown below - 

![whatsapp image 2017-07-04 at 20 09 58](https://user-images.githubusercontent.com/13872065/27834623-4ae1efa4-60f5-11e7-846b-4c1322ac6820.jpeg)
 
@kimhwins  I see you are learning Android. Feel free to assign yourself if you want to give this a try.

**Comment by Dilu9218** [comment]
@codingblazer  thanks I will assign her for this.
