### ISSUE TITLE
Remove hardcoded Strings and Resources across the project

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#459]
# **Description**

As a developer, I want to remove all the hard coded resources. We have to replace their resource reference and add them to respective resource directory - strings.xml, integers.xml and final constants for hard codes in java code.

# **Mocks**

Not Applicable

# **Acceptance Criteria**

All the replaced hard codes must follow Android conventions -
- Using Camelcase for Java variables, classes, etc.
- Using underscore naming for XML resources, strings, etc. Ex - avatar_text_width
- Using capital underscore naming for final constants. Ex - ACTIVITY_EXTRAS

# **Definition of Done**

Approval by mentors. 

# **Estimation**

4 hour

**Comment by yashasingh** [comment]
Can I work on this issue ?

**Comment by yashasingh** [comment]
@chhavip @aanchal07 I want to work on this issue. Can I be assigned for this ?

**Comment by luckyman000786** [comment]
@chhavip @codingblazer @aanchal07  I want to work on this issue. Can I ?

**Comment by codingblazer** [comment]
@yashasingh Yes, this is a pending issue. You can work on it if you want.
@luckyman000786 Please pick some other issue :-)

**Comment by yashasingh** [comment]
@codingblazer Alright I'll work on it.

**Comment by ManognaMutyala** [comment]
Even I am interested in working on this .Can I work on this too?

**Comment by yashasingh** [comment]
@ManognaMutyala I am working on this , I'll submit my PR soon.

**Comment by geekanamika** [comment]
Is this issue been resolved already ? If not, can I go ahead @codingblazer @yashasingh ?

**Comment by Rimjhim28** [comment]
@yashasingh Are you working on it? If not, I would like to work on this @codingblazer @MeepyMay

**Comment by Rimjhim28** [comment]
@codingblazer Can I work on this?

**Comment by TheCraftKid** [comment]
Hey, I'm going to tackle [this issue](https://codein.withgoogle.com/dashboard/task-instances/4780260874780672/) for Google Code-In.

From my search, it appears only one Activity has a hardcoded string that shouldn't be so: ScenarioOverActivity. on line 114, string concatenation is used instead of a formatted string, so I'll fix this later today.

**Comment by OliveUzoma** [comment]
the files with hardcoded Strings are
ScenarioOverActivity.java
SelectFeaturesActivity.java

**Comment by pavi2410** [comment]
Can I work on this? I'm participating in GCI

**Comment by Rimjhim28** [comment]
@pavi2410 You can surely proceed if you have claimed it on GCI portal.

**Comment by ada-vu** [comment]
the files that have hardcoded strings are listed:

activity_minesweeper_game.xml 
activity_scenario_over.xml
activity_sink_to_swim_end.xml
activity_sink_to_swim_game.xml
activity_store.xml
activity_vocab_match_end.xml
activity_vocab_match_game.xml
avatar_room.xml
minesweeper_pros_cons.xml
store_selection_view.xml


https://github.com/systers/powerup-android/pull/780

**Comment by ada-vu** [comment]
removed the hardcoded strings and replaced them with their resource name following naming conventions.

the files with hardcoded strings are:
activity_minesweeper_game.xml
activity_scenario_over.xml
activity_sink_to_swim_end.xml
activity_sink_to_swim_game.xml
activity_store.xml
activity_vocab_match_end.xml
activity_vocab_match_game.xml
avatar_room.xml
minesweeper_pros_cons.xml
store_selection_view.xml

here is the commit with the relevant changes:
https://github.com/systers/powerup-android/pull/786

**Comment by aviral2004** [comment]
Files with hardcoded strings:

1. AbstractDbAdapter.java
2. DatabaseHandler.java
3. MinesweeperGameActivity
4. sinkToSwimGame.java
5. MapActivity.java
6. StartActivity
7. activity_main.xml
8. activity_minesweeper_game.xml
9. activity_store.xml
10. activity_vocab_match_game.xml
11. minesweeper_pros_cons.xml
12. store_selection_view.xml

**Comment by aviral2004** [comment]
Project GCI: 
this is the link to my pull request: https://github.com/systers/powerup-android/pull/812

**Comment by geekanamika** [comment]
#827 solves this issue but doesn't refers to it. Closing it.
