### ISSUE TITLE
Scenario Desciption not shown after Mini Game Ends

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#460]
# **Description**

As a player, I should see the scenario description after completing the scenario. Currently, scenario description is not shown if the user has played a mini-game in that scenario.

# **Mocks**

Reference File: activity_scenario_over.xml
<img src="https://user-images.githubusercontent.com/13872065/29420602-13d07ebe-8390-11e7-898c-5d98c686bbf3.jpeg" height="200" width="400">

# **Acceptance Criteria**

The scenario name should be shown under Scenario Description for all the three scenarios having mini-game

-School
-Hospital
-Library

# **Definition of Done**

Approval by mentors. 

# **Estimation**

1 hour

**Comment by Masquerade0097** [comment]
@codingblazer @aanchal07 Can i work on this issue?

**Comment by Mandeepsinghchadha** [comment]
@codingblazer  Exactly what do you expect in the description after completion of that event

**Comment by geekanamika** [comment]
@codingblazer This has been resolved already in one the commits (I couldn't find the source ) , This issue can be closed, right ?
