### ISSUE TITLE
Status Bar color not uniform

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#461]
In many activities, the color of the status bar is gray in color. We want it to be black in color.

**Ref :** 

<img src="https://user-images.githubusercontent.com/13872065/29420602-13d07ebe-8390-11e7-898c-5d98c686bbf3.jpeg" height="200" width="400">

**Note:** Above is just one example of a gray status bar. There are many other screens with gray status bar. The task is to find them all and change the color to black.

**Comment by MeepyMay** [comment]
@Dilu9218 @codingblazer Whose decision was to make the status bar black?

**Comment by MeepyMay** [comment]
Add to the #374 

But don't make UI decisions without the designers.
