### ISSUE TITLE
Add score of the mini games to Karma Points

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#462]
# **Description**

Currently, the score gained by the user in any minigame is not added to the karma points (total points in PowerUp game). 

# **Mocks**

Not Applicable

# **Acceptance Criteria**

Score gets added to the main score for all three mini-games -

- Minesweeper Game
- Swim to Swink Game
- Vocab Match Game

Updated score should be shown in Store and Scenarios. 
 
# **Definition of Done**

- Approval by @aanchal07 and @dhara04 for proposed changes.

# **Estimation**

2 hours

**Comment by Divya063** [comment]
I would like to work on this

**Comment by codingblazer** [comment]
@Divya063 Sure !!

**Comment by Rimjhim28** [comment]
@Divya063 Are you still working on this? If no I would like to work on this.

**Comment by Rimjhim28** [comment]
@codingblazer Can I work on this?

**Comment by vatsalkul** [comment]
I have added mini score Gokarna points. https://github.com/systers/powerup-android/pull/718
