### ISSUE TITLE
Redundant Model Class Codes

### ISSUE THREAD

**Issue by piyush6348** [systers/powerup-android#466]
The entire Code of 
-> Answer.java
-> Avatar.java
-> Question.java
-> Scenario.java
-> Score.java
of thousands of lines can be converted to merely 10 lines in Kotlin.

![image](https://user-images.githubusercontent.com/16835832/29477970-3f4539ba-8488-11e7-9651-5a17c0c96a27.png)

This is an example for Answer.java

I would like to work on this issue

**Comment by geekanamika** [comment]
@piyush6348 Can you elaborate your issue ? I don't think , project is ready to get converted into a kotlin code base.
