### ISSUE TITLE
Modify the design of the lower bar to show the names of the different powers

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#47]
This is a design task, no coding!
The current lower bar on the conversation screen shows bars for the values of the different powers, but doesn't state what each of those values are. Design a UI and/or an interaction to show this. Several approaches could be valid like showing the name in a suitable place on the bar area or showing this information on a dialog on touch.
You should use Illustrator, Photoshop or similar tools for this task. You can also use a prototyping tool like Invision if you want to show the interaction

**Comment by vasukiarunachalam** [comment]
I will work on this.

**Comment by AkankshaBodhankar** [comment]
@alma-castant  what will the powers be ??
