### ISSUE TITLE
Travis is not configured properly.

### ISSUE THREAD

**Issue by zarka** [systers/powerup-android#491]
# Whats wrong - 
Travis for the repo hasn't been configured correctly. The tests are not failing when wrong code is pushed (I have opened PR #492 to show this).Actually the app is not being build during the travis test.

Also in the `.travis.yml` file we are using emulators. This is not needed as we are not testing the app on any emulator. This unnecessarily increases the build time for the app.

# What needs to be done - 
1. We need to optimise the `.travis.yml` so that travis builds the code.
2. We need to remove the emulators from the `.travis.yml` file.

Should I send a PR for this?

**Comment by codingblazer** [comment]
@zarka Yeah, this is one of the pending tasks. (Also, we have not yet integrated unit tests with Travis).
As for the emulator configuration, we will eventually need them when we will add the instrumentation tests (UI tests). We planned to add UI tests but were unable to (in given a time frame). So, I don't think there is need to remove emulator part. 
You may send PR for this **if** @aanchal07 feels the same.

**Comment by zarka** [comment]
@codingblazer 
I will w8 for @aanchal07 's approval then.

**Comment by MeepyMay** [comment]
This was completed. Thank you!
