### ISSUE TITLE
No option to deselect store items

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#493]
# Description

I suppose there is no explicit deselect button at the moment to remove the tried accessories / clothes / hair, the back button does the job but its not convenient.

# What can be done : 

- Addition of 'remove' button on every item category.
- An empty choice in the slider menu.

@codingblazer  please guide.

**Comment by codingblazer** [comment]
@sashafierce Are you on the latest branch (GSoC17) ?? If yes, please add some screenshots for better understanding :-)

**Comment by geekanamika** [comment]
@sashafierce @codingblazer can i work on this issue if it's unresolved and available ?

**Comment by Masquerade0097** [comment]
@codingblazer @aanchal07  Can i work on this issue?
