### ISSUE TITLE
Replay/home icon disappears after first selection of replay

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#494]
# Steps to reproduce :  
- Select a scenario 
- press the replay button at any point

When the scenario is replayed, the replay and home icons are no longer present 

@codingblazer  Is this the expected behaviour ?

**Comment by codingblazer** [comment]
Hi, @sashafierce, I think you are on the wrong branch. Replay icon was removed from the scenarios. 

![screen shot 2017-09-29 at 9 06 29 am](https://user-images.githubusercontent.com/13872065/30999928-bc38f80c-a4f5-11e7-8e18-55bfaa016d13.png)

**Comment by geekanamika** [comment]
@codingblazer @MeepyMay @sashafierce This issue can be closed , right ?

**Comment by MeepyMay** [comment]
Correct @geekanamika !
