### ISSUE TITLE
Check on warning dialog box 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#495]
# Description
The warning dialog box that pops up everytime the "NEW GAME" button is clicked should not pop up when the app is installed and launched on the device for the first time as there is no data or previous karma points stored.

# What could be done:
A check if the app is launched for the first time.
If yes the user should be directed to Avatar Room otherwise the warning should be displayed.

**Comment by Shreya001** [comment]
I, am outreachy aspirant and do android development. Can I work on this issue and how?

**Comment by Rimjhim28** [comment]
@Shreya001 I have already done the work just waiting for the approval of @codingblazer  so that I can send the pull request.You can yourself work to find some other issues.

**Comment by codingblazer** [comment]
@Rimjhim28 Seems logical to me !! Let's hear from @aanchal07

**Comment by Rimjhim28** [comment]
@codingblazer Should I send the PR?

**Comment by Rimjhim28** [comment]
@aanchal07 Can I work on this?

**Comment by Rimjhim28** [comment]
The issue is resolved through PR #527

**Comment by geekanamika** [comment]
Issue resolve through GCI Task.
