### ISSUE TITLE
Avatar wrong eyes

### ISSUE THREAD

**Issue by nani92** [systers/powerup-android#496]
# Description
When you create an avatar with default eye color (blue), the result avatar shown in AvatarActivity has wrong eye color (orange).

# Steps to reproduce
1. Click "NEW GAME" button
2. Click "Create new Avatar" in dialog
3. Do not change eye color when creating avatar. _Displayed eye color is blue._
4. Click "CONTINUE" button
5. In new window there is avatar with orange eyes.

![2017_09_30_11_00_06 1](https://user-images.githubusercontent.com/7022074/31044412-41538e60-a5cf-11e7-9bdb-51ef9ee2ce6a.gif)

I found this bug in code. Can I work on this and send PR?

**Comment by geekanamika** [comment]
@codingblazer @Rimjhim28 @MeepyMay Does this issue still persists ? I works good with updated code in my mobile, can you confirm ?

**Comment by MeepyMay** [comment]
Works for me too. Closing the issue. 👍
