### ISSUE TITLE
Distorted avatar in completed scene and store

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#497]
# Description
The avatar gets distorted in the completed scene activity as well as in the store activity.I have checked the issue with devices of various screen sizes. I have uploaded the screenshots.
![screenshot_1506767783](https://user-images.githubusercontent.com/26908195/31045089-bbee7b06-a5f9-11e7-9698-cbe04823f100.png)
![screenshot_1506767238](https://user-images.githubusercontent.com/26908195/31045092-c3cc5b5e-a5f9-11e7-9bbb-554cb8f65106.png)

**Comment by ShailyTyagi** [comment]
I don't think it's the distorted avatar. I think it's just showing the current possessions of the avatar i.e. the dress and the hair.

**Comment by eileenxuan** [comment]
can I try to work on it?

**Comment by eileenxuan** [comment]
Can i work on this?

**Comment by Rimjhim28** [comment]
This is not a valid issue.The UI design of the activity is changed after
the updates to the code :)
