### ISSUE TITLE
Inconsistent Home button behaviour

### ISSUE THREAD

**Issue by nani92** [systers/powerup-android#498]
By Home button I mean button displayed in upper right corner
![img_20170930_195420](https://user-images.githubusercontent.com/7022074/31048271-351d6742-a61a-11e7-9ada-caf0f8dc231a.jpg)

# Description
When playing a scene if you click on home button you are moved to screen with map.
![2017_09_30_19_55_08 1](https://user-images.githubusercontent.com/7022074/31048289-90373c48-a61a-11e7-9d31-45606faaf27f.gif)

When you are in scene final screen if you click on home button, you are moved to startActivity
![2017_09_30_19_55_08 2](https://user-images.githubusercontent.com/7022074/31048307-cd3da8ca-a61a-11e7-8e4a-1f2591177136.gif)

User could expect that after clicking this button in scene final screen he would also be moved to screen with map. 

I would like to work on this.

**Comment by zeroplusone** [comment]
I would like to work on this.

**Comment by MeepyMay** [comment]
Home button is referenced a couple of times in earlier issues. #309 #332  This will be fixed in the next development cycle with an iOS comparison check.
