### ISSUE TITLE
Unexpected behaviour of the Replay button

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#500]
## Description
As a user,
I need fix the logic for replay button,
so that I can that correct scenario is launched when replay is clicked and the app does not crash.

## Mocks
Not applicable

### Update [Required]
- [ ] Fix the logic for replay button

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by eileenxuan** [comment]
Can I work on this?

**Comment by Rimjhim28** [comment]
I would like to work on this issue.I am waiting for the approval.

**Comment by eileenxuan** [comment]
ok!

**Comment by Rimjhim28** [comment]
@codingblazer Can you please check the issue. I would like to work on this.

**Comment by codingblazer** [comment]
@Rimjhim28 This is a valid issue. Please describe the bug which is causing this problem, it's location and what solution you propose for this. Thanks :)

**Comment by Rimjhim28** [comment]
# Description:
@codingblazer The bug lies in handling of the replay button in ScenarioOverActivity, specifically in the following line:
SessionHistory.currSessionID = SessionHistory.prevSessionID;

Currently, the curSessionID is always set to prevSessionID,no matter from where the replay button was clicked. The handling is fine if the user has just finished a particular scenario and wants to replay the same but when the user chooses a scenario from the MapActivity then also the value of currSessionID is set to last played scenario irrespective of the user's choice.

# What could be done
Defining a method in DatabaseHandler.java which returns the id of a particular scenario based on the name.
Modifying the if else block in the handling the click of the view.Specifically adding one more intent extra in the else block to pass the scenario name using which the scenario id can be extracted later in ScenarioOverActivity.java which can be used to reset the value of currSessionID using an if-else block.

**Comment by Rimjhim28** [comment]
@codingblazer I have solved the issue though the approach is different from what I have described here.
The approach is mentioned in the pull request.
