### ISSUE TITLE
The app closes if the device screen is turned off.

### ISSUE THREAD

**Issue by ShailyTyagi** [systers/powerup-android#501]
Current scenario:
If the device goes to sleep while the app is open , the user upon waking it up again should find the same state in which they left it.But here, the app closes automatically.

**Comment by Shreya001** [comment]
can I work on this issue?

**Comment by ShailyTyagi** [comment]
Hey! @Shreya001  I am going to work on it . I just need approval to go ahead! :)

**Comment by Masquerade0097** [comment]
@codingblazer @aanchal07 Can i work on this issue?

**Comment by MeepyMay** [comment]
@ShailyTyagi Please resubmit in the new issue format. Join [Systers OS Slack](systers.io/slack-systers-opensource/) to stay updated on PowerUp's progress.
