### ISSUE TITLE
Improper handling of Back button of the device

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#503]
# Description
The CompletedSceneActivity needs a proper handling of the back button from the device.Currently if the back button is pressed the user is directed to the last question of the previous scenario and answering this again increases the karma points and this could be done multilple times.This also eventually leads to app crash at some point in the game.Some unexpected scenario also appears later.

The screenshot when the scene is completed once:

![8 points](https://user-images.githubusercontent.com/26908195/31166765-78952bb8-a90d-11e7-918c-f6c86a20df52.png)

When the back button from the device is pressed:

![22251268_1408449682606672_347102418_o](https://user-images.githubusercontent.com/26908195/31166773-83c9aa54-a90d-11e7-9d90-53ac8656fac8.png)

If the question is answered again:

![imagr with 10](https://user-images.githubusercontent.com/26908195/31166776-8613f508-a90d-11e7-9f4f-851e1295960b.png)

Notice an increase in the karma points 

Later some unexpected activity is appearing

![22243510_1408449649273342_1675998620_o](https://user-images.githubusercontent.com/26908195/31166912-ff85c416-a90d-11e7-877a-e145252a93bc.png)

I would like to work on this issue.

**Comment by codeb1ooded** [comment]
This issue is already mentioned in issue #375

**Comment by Divya10** [comment]
hello can i work on this issue.

**Comment by Rimjhim28** [comment]
Hey @Divya10 ,here the issue was opened by and I had been waiting for @codingblazer approval.
I can work to get some of other issues :)

**Comment by MKDEVELOPEMENT** [comment]
can i do this issue for GCI

**Comment by Rimjhim28** [comment]
Yes @MKDEVELOPEMENT Proceed! :)

**Comment by ZidBidBee** [comment]
I've claimed it on GCI... may I work on this?

**Comment by vatsalkul** [comment]
I have Fixed the back button functionality. https://github.com/systers/powerup-android/pull/690

**Comment by vatsalkul** [comment]
I have fixed the back button functionality. https://github.com/systers/powerup-android/pull/691

**Comment by sidvenu** [comment]
I have created a pull request for the proper handling of the back button, with provided documentation and comments to explain the code. Thank you for this opportunity! :)
Link: https://github.com/systers/powerup-android/pull/719

**Comment by akshaynexus** [comment]
i have fixed this issue as part of a GCI task,here is the link to the PR https://github.com/systers/powerup-android/pull/759

**Comment by geekanamika** [comment]
Issue has been resolved. Closing this issue.
