### ISSUE TITLE
Update Android Design

### ISSUE THREAD

**Issue by Adeti** [systers/powerup-android#505]
Ensure Android about screen correlate with iOS about screen.

**Comment by Adeti** [comment]
Android's about screen is not updated to the new design like the iOS screen, so we need to make sure they are similar to each other.

**Comment by MeepyMay** [comment]
We need to adjust this issue to new issue template.

**Comment by geekanamika** [comment]
@Adeti As May mention, Can you create another issue with the new template? I'm closing it for now.
