### ISSUE TITLE
The size of repo is big.

### ISSUE THREAD

**Issue by zarka** [systers/powerup-android#514]
Currently the repo is insanely large in size (a 190MB or more). Going by the files currently in the project the maximum size should be 30 MBs. This is most probably because of some previous file in the git history. These files need to be identified and removed from git history.

I would work on this issue but would need help from someone who has worked on the project for a long time and can help identify these files.

**Comment by MeepyMay** [comment]
Closing the issue for now. @zarka please use the new issue template to elaborate on the issue and we'll re-open the issue. Thank you!
