### ISSUE TITLE
Minor issue in Vocab Match.

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#521]
There is a repetition of one of the images in the game. While the first one goes correct for match with "Fat"
the next one goes correct with "Skinny". This creates a bit of ambiguity in the game.
![22550682_1419230741528566_1939487351_o](https://user-images.githubusercontent.com/26908195/31651747-75a64cde-b33a-11e7-9478-acdac36b80ca.png)
@codingblazer Please have a look.

**Comment by codingblazer** [comment]
There is no repetition. Both are different images. Look where the arrow is pointing. First is fatter and second is slim. Yes it does, however, seems less noticeable while playing the game. The design team will look into this. @kimhwins

**Comment by kimhwins** [comment]
as sachin said, they're actually different images. I could make a tile that removes the head so we can zoom in on the stomach and hopefully that makes it more clear?

**Comment by Rimjhim28** [comment]
Oh yes! Just failed to notice.
But as a user, this will go unnoticed. Slight modification in the design could be better. :)
