### ISSUE TITLE
Sink to Swim Game slow question transition 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#523]
Currently, when the skipbutton is pressed during the game the transition to next question is quite slow and the space in which the question is dispplayed remains blank foe ariund 2 seconds which is quite ambiguous.

![slow](https://user-images.githubusercontent.com/26908195/31807835-f6109c62-b58d-11e7-95d2-034ae5913ac3.gif)

 Changed two lines of code to reduce the transition time.This could be reduced even further with slight adjustments in the start off and animation duration. 

![smooth](https://user-images.githubusercontent.com/26908195/31807843-006472d8-b58e-11e7-994b-9d497b8eb98f.gif)

@codingblazer @MeepyMay  Please check if this could be valid issue.

**Comment by Rimjhim28** [comment]
@codingblazer Will this be valid issue to work on?

**Comment by codingblazer** [comment]
@Rimjhim28 Yes, a valid issue !!

**Comment by Rimjhim28** [comment]
@codingblazer Thanks for the review. Already solved through PR #537

**Comment by codingblazer** [comment]
@Rimjhim28 Will be reviewed soon :)
