### ISSUE TITLE
Negative karma points

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#524]
## Description
As a user,
I need to fix the logic behind karma points,
so that I can the karma points do not go to a negetive value.

## Mocks
The error is arising because of the following code line in the handling of the replay button:
 SessionHistory.totalPoints -= SessionHistory.currScenePoints;
Here, as soon as the replay button is pressed the current session points are directly deducted from the total points without any consideration of the total points.
![negative](https://user-images.githubusercontent.com/26908195/31860981-5d78430a-b741-11e7-8783-5dc4bc048a39.png)

### Update [Required]
- [ ] Develop an if-else block to check the value of karma points before deduction

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by saurabhjn76** [comment]
@Rimjhim28 It's a valid issue, please make the PR

**Comment by m-murad** [comment]
@rimjhim28
Please send a PR for this issue

**Comment by Rimjhim28** [comment]
@saurabhjn76 @m-murad Thanks for the approval. Will be sending a PR shortly.
