### ISSUE TITLE
Fix conversation UI for horizontal display: avatar

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#53]
When on a horizontal display, the avatar is shown wrong with the head not correctly placed. This should be fixed so the avatar is correctly displayed in both vertical and horizontal displays

**Comment by vasukiarunachalam** [comment]
I will work on this.

**Comment by vasukiarunachalam** [comment]
The issue is with the avatar and the question view appearing in same column space. I think this has been handled in the previous issue where chavi has resolved it by moving the question and answer views to center of the layout. So I think we can close this issue ?

**Comment by alma-castant** [comment]
@vasukiarunachalam yes, thank you for pointing it out!
