### ISSUE TITLE
Inconsistent display of score in Swim to Sink game

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#530]
## Description
As a user,
I need change the display score text,
so that the game can have more uniformity.

## Mocks
Initially when the game starts the score in the game is diaplyed with two digits,that is, two zeros.
![double 0s](https://user-images.githubusercontent.com/26908195/32003335-50ffa366-b9bc-11e7-88ed-c731fb45f9d7.png)

But just after first response from the user, the score is displayed with just one digit.
If the user pressed the skip button or the answer by the user is wrong, the double digit of the score,that is, double zeros of the score are set to a single zero. 
![single 0](https://user-images.githubusercontent.com/26908195/32003533-03121bd8-b9bd-11e7-9f7c-8bfdaa6a2a5e.png)

If the user answers correctly, the double zeros are set to a single one.
![single 1](https://user-images.githubusercontent.com/26908195/32003522-fbb1b66e-b9bc-11e7-8aec-6e136cc3f830.png)

This seems quite inconsistent. A better option would be to start with one just single digit score.

### Update [Required]
- [ ] Change in xml file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by codingblazer** [comment]
Hi @Rimjhim28 Yes, a valid issue. Please don't send pull requests until assigned in future :)

**Comment by Rimjhim28** [comment]
ok @codingblazer , will keep that in mind :)

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  hii..Are you still working on this issue or is this closed?

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha Since the issue is approved, I have already sent the PR.
