### ISSUE TITLE
Unresolved package in game_activity.xml

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#532]
## Description
As a user,
I need fix the package name,
so that game_activity.xml does not display any error.

## Mocks
![unresolved package](https://user-images.githubusercontent.com/26908195/32047898-12626cd4-ba65-11e7-84d5-c27f027ba619.png)

### Update [Required]
- [ ] Change in game_activity.xml

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by Masquerade0097** [comment]
@Rimjhim28 please have a look at pull request #667

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by m-murad** [comment]
I say this in a screenshot in some other issue as well. Please fix this.

**Comment by Rimjhim28** [comment]
@m-murad Thanks for the approval. Will be sending a PR soon.
