### ISSUE TITLE
Usage of  "dp" for text size 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#534]
Currently, one of the dimension attributes in dimen.xml , about_text_size_section_title is using "dp" and is used for text size in activity_about.xml. Instead, sp or "scale-independent-pixels" should be used, which is preferred and recommended for text sizes as it respects user preference for text sizes.

## Description
As a contributor,
I need to change the dimension attribute in diemn.xml, about_text_size_section_titile to use sp or "scale-independent-pixels" instead of dp,
so that the text could respond to user's preferred text sizes.

## Mocks
Not Applicable

### Update [Required]
- [ ] Change in dimens.xml

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by arundhati24** [comment]
Hi @Rimjhim28,  I would like to fix this issue.

**Comment by Rimjhim28** [comment]
@arundhati24 I will work on this. I just need an approval. You may find some issues yourself and work to resolve those.

**Comment by AjaySharvesh3** [comment]
@Rimjhim28 Can I claim this issue?
Will you give me approval?

**Comment by Rimjhim28** [comment]
@AjaySharvesh3 take up the issue but send a PR only after the issue is approved.
@geekanamika @m-murad please approve the issue.

**Comment by geekanamika** [comment]
@AjaySharvesh3 If you're claiming first time in this repository, Go ahead & send a PR.
