### ISSUE TITLE
Fix conversation UI for horizontal display: conversation

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#54]
When on a horizontal display, the right part of the conversation is almost hidden below the character and can't be read. It should be placed somewhere else (possibly next to the character) in the horizontal mode so it can be easily seen

**Comment by chhavip** [comment]
I have tried to fix this and issue avatar display error together, saw separate issues later. This has been my fix so far, let me know of improvements needed:





![image](https://cloud.githubusercontent.com/assets/7212638/11663813/574198f4-9e04-11e5-975f-fda2dae25528.png)

**Comment by alma-castant** [comment]
This looks good, but what happens if the right character has more text. Does it cover the character? Maybe you can make both text boxes slightly smaller so they don't cover the caracters as they grow

**Comment by chhavip** [comment]
@alma-castant , I have moved the boxes towards the left so that they dont cover the characters, making them smaller would have made them slightly unreadable

![screenshot_20151215-141128](https://cloud.githubusercontent.com/assets/7212638/11805971/d6b6eb9e-a335-11e5-88bd-9dc65b3b23d3.png)

**Comment by alma-castant** [comment]
@chhavip it looks better now. Is there scrolling on the text on the left?

**Comment by chhavip** [comment]
Yes, there is

**Comment by alma-castant** [comment]
It looks good then. You can go ahead ;) @chhavip
