### ISSUE TITLE
Updating Android API version and Android Studio 3.0 Compatibility

### ISSUE THREAD

**Issue by robillo** [systers/powerup-android#540]
### What is wrong?

Currently, the app gradle file for the project aims at Android API 22, which is version Lollipop. As per valid sources, the usage of the version Lollipop is less than 28% of all Android devices, so it is recommended to target latest Android versions. [refer here] (https://fossbytes.com/most-popular-android-versions-always-updated/).

### Expected behaviour.

What do you think should be the expected behaviour?
It is required to target latest Android version. Also, the introduction of latest version of Android Studio (3.0) expects to add a few lines of code integration for future enhancements. Moreover, it is always recommended to write down all app dependencies in the project level gradle file of the application for decent app scalability, which requires to be done.

### Screenshot or GIF
![screen shot 2017-10-31 at 1 31 12 pm](https://user-images.githubusercontent.com/19509186/32213093-d6aac608-be3f-11e7-9dc9-64a0d2e9e33a.png)
![screen shot 2017-10-31 at 1 31 22 pm](https://user-images.githubusercontent.com/19509186/32213095-d702d2f8-be3f-11e7-8b59-8dccabf72d74.png)

**Comment by Masquerade0097** [comment]
@robillo Please have a look at my pull request #653

**Comment by Masquerade0097** [comment]
@codingblazer @aanchal07 Can i work on this issue?

**Comment by geekanamika** [comment]
resolved as a part of #1005
