### ISSUE TITLE
Finish avatar and include feet.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#543]
## Description
As a developer,
I need a full body avatar,
so that I can update.

## Mocks
![new avatar body example](https://user-images.githubusercontent.com/2440938/32242626-a0a25fd0-be49-11e7-802d-c43891df3575.png)
**Note: With the version 2.0 eyes, not version 3.0.**

### Base [Required.]
• [All 16 available skin tones.](https://github.com/systers/powerup-android/tree/design/UI/avatar/skin)

## Definition of Done
- All required elements completed.
- Approved by UI team. (Kim & May)

## Estimation
8 hours

**Comment by debanjanah** [comment]
@meepymay What should the dimensions of the new image be for the app?

**Comment by MeepyMay** [comment]
@debanjanah Can you change to submit files only of bodies? No accessories, for now, I have to review the files separately.
