### ISSUE TITLE
Accessible Options!

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#544]
## Description
As a user,
I want to create an avatar that reflects who I am,
so that I can connect with the avatar.

## Mocks
Use [@debanjanah's mock](https://user-images.githubusercontent.com/11819085/31799182-3a5efeb4-b556-11e7-8f07-a1807415574f.png) and use [full body](https://github.com/systers/powerup-android/tree/design/UI/avatar/full%20body) dimensions to complete avatars who use wheelchairs.

### Base [Required]
• [16 Skin Tones](https://github.com/systers/powerup-android/tree/design/UI/avatar/skin)

### Accessibility [Required]
• Wheelchair

## Definition of Done
- All required complete.
- Approved by UI team. (Kim & May)

## Estimation
16 hours

**Comment by Mandeepsinghchadha** [comment]
hii..Is this issue closed or somebody is working on it right now?

**Comment by MeepyMay** [comment]
@Mandeepsinghchadha Yes. Assigned to our Outreachy intern.
