### ISSUE TITLE
Fix change room screen on tablets

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#55]
Currently, the change room screen displays well in small screens like phones, but on tablets the content stays in the upper left corner. The content should instead be centered and made bigger to fit the tablet screen and still work well on phones

**Comment by vasukiarunachalam** [comment]
I will work on this.

**Comment by vasukiarunachalam** [comment]
Are the creator room and change room same ? For creator room issue , I changed the avatar_room.xml.
What layout should I be working with for this issue ? Is it avatar.xml ? Please let me know.

**Comment by alma-castant** [comment]
Yes, the creator room and the change room are the same. You should be working on an `avatar_room.xml` version for tablets and horizontal displays ;)

**Comment by vasukiarunachalam** [comment]
Thank you. so we can close this , isn't it ? I have included this in creator room issue, for horizontal mode and for tablets.

**Comment by alma-castant** [comment]
The two issues are slightly different. This one is about size (everything is the corner) while the other issue is about horizontal vs. vertical display

**Comment by vasukiarunachalam** [comment]
I included both in the creator room issue. This involves adding different sizes in values/dimens.xml.
The horizontal display requires the creation of new xml file ( layout-land/avatar_room.xml )

Should I submit the changes as separate PRs ?

**Comment by alma-castant** [comment]
I will look at both in that PR. In the future however, I recommend putting one issue per PR only
