### ISSUE TITLE
Include margins for scenario description

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#552]
# Description
Currently the scenario description in all the scenarios seems too much aligned to top left corner of the device screen. A better option would be to include margin or padding for a better view.

# Mocks
![screenshot_1511675724](https://user-images.githubusercontent.com/26908195/33237571-5a1931a2-d29d-11e7-8ef5-0bda81041958.png)

# Acceptance Criteria
There should inclusion of margins for the mentioned text

# Definition of Done
Approval by mentors

# Estimation
1 hour

**Comment by Rimjhim28** [comment]
@MKDEVELOPEMENT You need to claim it on GCI portal first.

**Comment by MKDEVELOPEMENT** [comment]
i have claimed it on GCI

**Comment by Rimjhim28** [comment]
Then you can proceed @MKDEVELOPEMENT

**Comment by mofetej** [comment]
How do i claim the issue here. I already claimed the task on GCI portal

**Comment by ZidBidBee** [comment]
Is is possible for me to still claim this task? Even though someone else has claimed it.

**Comment by Rimjhim28** [comment]
@mofetej You just need to inform that you are working on this issue. If you have claimed it on GCI portal you can go ahead.

**Comment by Rimjhim28** [comment]
@ZidBidBee If you can claim it on GCI portal,that is, if the related task is available on GCI portal you can claim it there. If you can claim the task there you can claim the issue.

**Comment by yuyuan-luo** [comment]
I would like to work on this, I claimed it on the GCI portal. Thank you! :)

**Comment by m-sameer** [comment]
I'm working on it.

**Comment by m-sameer** [comment]
@Rimjhim28 I have added the margins, please review the [PR](https://github.com/systers/powerup-android/pull/603).

**Comment by m-sameer** [comment]
@Rimjhim28 I have also added all the screenshots in the [PR](https://github.com/systers/powerup-android/pull/603).

**Comment by vatsalkul** [comment]
I added margins to scenario description. https://github.com/systers/powerup-android/pull/656

**Comment by vatsalkul** [comment]
I have added margins to the scenario description. https://github.com/systers/powerup-android/pull/657

**Comment by Aryaman21** [comment]
Added the necessary margins with the revised changes. https://github.com/systers/powerup-android/pull/649

**Comment by Rimjhim28** [comment]
Appropriate PR #603 has been merged.
