### ISSUE TITLE
Replace background of AvatarScene by Correct background

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#553]
# **Description**

The current background for avatar creation is not consistent with the iOS version. The background needs to be replaced by the correct one as shown in the mocks.

# **Mocks**

**Current background:**
![screenshot_20171127-010028](https://user-images.githubusercontent.com/13872065/33243548-7b1ed278-d30e-11e7-9c41-238c5349fb2a.png)

**Correct background:**
![screen shot 2017-11-27 at 1 42 18 am](https://user-images.githubusercontent.com/13872065/33243918-654f2ca8-d314-11e7-89cb-2c4d7ec2801f.png)

# **Acceptance Criteria**

The replaced background should work on all configurations and devices.

# **Definition of Done**

Approval by mentors. 

# **Estimation**

1 hour

**Comment by ZidBidBee** [comment]
Can I claim it?

**Comment by Rimjhim28** [comment]
@ZidBidBee Claim the task on GCI Portal and go ahead. I apologize for a late reply.

**Comment by sidvenu** [comment]
I have changed the background image to the required image. It was a one-line substitution of XML code (in the file avatar_room.xml). I have tested it on my phones and tablet. I've used a single commit and is a different branch (branched from GSoC17).
PR Link: https://github.com/systers/powerup-android/pull/727
