### ISSUE TITLE
Report and fix lint issues 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#555]
# Description
Track lint issues throughout the project using android inspect tool. Include the lint output from Android Studio. Rectify all the errors and try to eliminate maximum number of warnings.

# Mocks
Not applicable

# Acceptance criteria
Approval by the mentors

# Estimation
12 hours

**Comment by mhdsmr2** [comment]
Which branch do I have to do it on?

**Comment by Rimjhim28** [comment]
You can get the latest code from branch "GSoC'17".

**Comment by mhdsmr2** [comment]
Okay. Thanks.

**Comment by mhdsmr2** [comment]
Why did you close this?

**Comment by Rimjhim28** [comment]
Hey @mhdsmr2 the issue needed some modificaion. The related task will be published by next week. Till then claim and work on other issues. All the Best! :)

**Comment by mhdsmr2** [comment]
Okay. +1
