### ISSUE TITLE
Include total karma points on final screen of PowerUp Android

### ISSUE THREAD

**Issue by erikaaatan** [systers/powerup-android#556]
To show the total karma points accumulated at the end of the game, GameOverActivity must be changed. Some static variables that should be reused are karma_iv_width and karma_iv_height, which are dimensions for the karma box. The karma box (@drawable/karma_box) and the TextView inside the karma box displaying the points should also be reused.

**Comment by m-sameer** [comment]
Are you a student or a mentor for GCI? I wanna work on this issue.
