### ISSUE TITLE
Enhance the exit option 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#576]
# Description
Currently pressing the back button on PowerUp home screen simply exits the app without any warning. Enhance the exit option so that when the user presses the back button once, a toast message is displayed "Press once more to exit", pressing the back button again within 2 seconds exits the app.

# Mocks
Not applicable

# Acceptance Criteria
Toast message should be displayed. Use string resources to include any new string. The user should be able to exit from the app no matter from which screen he/she migrated to PowerUp screen.

# Definition of Done
Approval by mentors

# Estimated time
6 hours
#

**Comment by m-sameer** [comment]
May I work on this issue?

**Comment by m-sameer** [comment]
I created the [PR](https://github.com/systers/powerup-android/pull/580). Please review it.

**Comment by ZidBidBee** [comment]
Can I claim this?

**Comment by Rimjhim28** [comment]
@ZidBidBee You can claim the task after you have claimed it on gci portal.

**Comment by ZidBidBee** [comment]
@Rimjhim28 I just did... Thanks!

**Comment by Aryaman21** [comment]
@Rimjhim28 @codingblazer done the changes as part of the task, please find the link attached.
Link -

**Comment by yuyuan-luo** [comment]
May I work on this if I have claimed it on the GCI portal?

**Comment by Rimjhim28** [comment]
@yuyuan-luo You can surely proceed if you have claimed it on GCI portal.

**Comment by vatsalkul** [comment]
Enhanced the exit button by making it more responsive. https://github.com/systers/powerup-android/pull/659

**Comment by vatsalkul** [comment]
Enhanced the exit Button. https://github.com/systers/powerup-android/pull/662
