### ISSUE TITLE
Fix start screen for big screens

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#59]
The size of the buttons, icon and text is too small for big screens (tablets). It should be resized according to the screen size

**Comment by chhavip** [comment]
Will do.

**Comment by chhavip** [comment]
I have given new values in dimens for large screens. Preview on 7" screen:
![tablet_7_screenshot](https://cloud.githubusercontent.com/assets/7212638/12009606/9a14bd3c-aca5-11e5-80c6-fa940a4f6214.png)
If this is satisfactory, should I do the same for 10"? Slight concern about the pixels starting to show on large screens.

**Comment by alma-castant** [comment]
I think this ratio is ok. It will be great if you also do it for 10" :)
If you have some photoshop/illustrator skills, you can try to edit the buttons for a bigger resolution. If you don't, I can create a new issue with that so we only solve this one once that one is solved. Let me know what you prefer

**Comment by chhavip** [comment]
I don't have photoshop skills as of now, will try to learn soon. In the meantime, that can be created as a separate issue. I have fixed the start page for 7", 10" in landscape and portrait mode and it looks satisfactory to me. Should I submit the PR?

**Comment by alma-castant** [comment]
Submit the PR since you already have the code. I will test in my tablets and see how big of a problem the pixelation is there

**Comment by chhavip** [comment]
I have submitted the PR, #62
