### ISSUE TITLE
Increasing order of karma points

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#597]
# Description
Currently the required karma points displayed on StoreActivity is quite inconsistent. Change the order of karma points to increasing by modifying the proper variables. Avoid adding any new variables/arrays.

# Mocks 
Current view of karma points is shown in the screenshot
![screenshot_1512242939](https://user-images.githubusercontent.com/26908195/33527811-0edf08e8-d87d-11e7-8a94-f01b05e416ee.png)
Rearrange the required karma points to "5","5","5","5","10","10"

# Acceptance Criteria
Rearrange the required karma points in increasing order. Ordering should be done to all the items in the store.

# Definition of Done 
Approval by the mentors

# Estimated Time
1 hr.

**Comment by ZoroarkDarkrai** [comment]
I should change the value manually? If so, can I claim this? @Rimjhim28

**Comment by Rimjhim28** [comment]
@ZoroarkDarkrai You first need to claim the related task on GCI portal.

**Comment by ZoroarkDarkrai** [comment]
Ook. Just wanna make sure, this should be done manually, right? @Rimjhim28

**Comment by Rimjhim28** [comment]
@ZoroarkDarkrai That is what the task is all about. It depends on your perception. Claim the task and try to submit some work for review. If more work or modifications would be required you'll be guided by the mentors.

**Comment by ZoroarkDarkrai** [comment]
I have claimed it. Can you assign the issue to me? @Rimjhim28

**Comment by Rimjhim28** [comment]
@ZoroarkDarkrai If you have claimed it on GCI portal you can proceed!

**Comment by FizzesShark** [comment]
Hey, I also claimed it on GCI, but I can't find the button to claim it on GitHub. How can I do that?

**Comment by Rimjhim28** [comment]
@FizzesShark If you've claimed it on GCI you can proceed.

**Comment by m-sameer** [comment]
I am working on it. :)

**Comment by Isabel-S** [comment]
@Rimjhim28 Hi, just letting you know that I am working on this for GCI tasks.

**Comment by Rimjhim28** [comment]
@Isabel-S Since you have claimed it you can go ahead. :)

**Comment by bolutej** [comment]
![game1](https://user-images.githubusercontent.com/34077086/33829723-b16e575e-de71-11e7-8545-cdf5767d29ce.png)
![game2](https://user-images.githubusercontent.com/34077086/33829724-b1abf460-de71-11e7-946d-634395306a39.png)

**Comment by bolutej** [comment]
![game2](https://user-images.githubusercontent.com/34077086/33829747-cea2ef4c-de71-11e7-838e-1406647d73ef.png)
![game1](https://user-images.githubusercontent.com/34077086/33829766-d98867a2-de71-11e7-8749-bb59c600f519.png)

**Comment by ZidBidBee** [comment]
I have claimed this task on GCI. May I work on this?

**Comment by vatsalkul** [comment]
I have rearranged the order of required Karma Points #681

**Comment by Aryaman21** [comment]
Completed the task, and added the screenshots as well.
PR - https://github.com/systers/powerup-android/pull/674
