### ISSUE TITLE
LeakCanary for detection of Memory Leaks

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#664]
**Description**
Memory Leaks can occur in an application and can reduce the performance of the app. Moreover it can be difficult for the programmer to detect them.

**Expected Behaviour**
Incorporation of a mechanism to detect memory leaks easily

**Observed Behaviour**
No such mechanism is currently being used in the app.

**Comment by Masquerade0097** [comment]
Let me work on this issue

**Comment by Rimjhim28** [comment]
I think a similar issue is present in #463
