### ISSUE TITLE
Configuring Dimensions for Dialogues

### ISSUE THREAD

**Issue by Aryaman21** [systers/powerup-android#687]
##Description
At some points in the GameActivity, some parts of the dialogues by the second character are not readable due to improper dimensions of the View in the dialogue cloud.
New margins and proper dimensions need to be added in order to fix the appearance of the dialogues.

## Mocks
![Screenshot](https://user-images.githubusercontent.com/19228432/34055747-9aaf0bd4-e1f6-11e7-99ab-86f32a61a52f.png)

### Update [Required]
- [ ] [XML files of the required activities]
- [ ] [Screenshots of corrected margins in the dialogue]
## Definition of Done
- [ ] All the conversation scenes should have proper dialogue margins
- [ ] Approval by 1 mentor.

## Estimation
[2-3] hours

**Comment by Aryaman21** [comment]
@codingblazer can I start working on this?

**Comment by geekanamika** [comment]
@Rimjhim28 I can't find the PRs related to this issue. Can you check once ?

**Comment by Rimjhim28** [comment]
@geekanamika This wasn't taken up in GCI. I think @MeepyMay has added the label by mistake.
I don't think the issue exists anymore. Proper margins were included in PRs like text-overflow and adding ripple effect. As far as I can remember, the accepted PRs were from @Aryaman21 only.
I think it would be good enough to close the issue.
