### ISSUE TITLE
Create start screen icons with bigger resolution

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#69]
The current start screen buttons are suitable for mobile screens, but they get pixelated in bigger screens. This task doesn't include any coding. It consists of creating bigger resolution buttons with Illustrator, Photoshop or similar tools

**Comment by AkankshaBodhankar** [comment]
Adding different sizes like xxhdpi, xhdpi, mdpi  will do the trick
I have the zip folder of the button images which will fit in all the screens
Do let me know if i can proceed with it

**Comment by alma-castant** [comment]
@AkankshaBodhankar have you created new images with these resolutions? If so, can you post one here to see it?

**Comment by AkankshaBodhankar** [comment]
Yes all the resolutions are in this zip folder for the start button ...we can have same for another as well
This is a sample
[start_button_resolutions.zip](https://github.com/systers/powerup-android/files/146638/start_button_resolutions.zip)

**Comment by AkankshaBodhankar** [comment]
@alma-castant  http://developer.android.com/intl/es/training/basics/supporting-devices/screens.html

**Comment by chhavip** [comment]
@AkankshaBodhankar  I saw the images in the folder you attached, they are basically reducing the current start button size , xxdpi has similar dimensions to the current start button which will still get pixelated. The buttons need to be redesigned (using Photoshop or similar tools)

**Comment by AkankshaBodhankar** [comment]
@chhavip Yes, i'll change the resolutions as required
