### ISSUE TITLE
Automatic unlocking of next scene

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#693]
**Description**
When i run the app ( GSoC branch ) on my system this screen is displayed. The user scene is by default completed( Issue #694) and since it is completed therefore the scene right after it should get unlocked but this is not happening.

**Steps To Reproduce**
Load Game -> House -> Map 
or
New Game -> Create New Avatar -> Continue -> House -> Map 

**Mocks**
![power_scr](https://user-images.githubusercontent.com/23634977/34073379-94c9dde8-e2be-11e7-855c-9d2ce015a5eb.png)

**Expected Behaviour**
The next scene should be unlocked automatically after completion of one scene.

**Observed Behaviour**
The scene after completion of House Scene is not getting unlocked.

**Definition of Done**
- [ ] All of the required items are completed.
- [ ] Approval by a mentor.

@codingblazer @MeepyMay  @aanchal07  @dhara04  please approve so that i can work on this.

**Comment by codingblazer** [comment]
Hi @Masquerade0097 
On my device, i can't replicate issue #693. Let's take this issue after we are done with #693.

**Comment by MeepyMay** [comment]
This isn't an issue and can't be replicated, so I'm closing the issue. If @Masquerade0097 can upload a gif, we'll re-open.
