### ISSUE TITLE
Home Scene completed by default on opening

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#694]
**Description**
When i ran the app( GSoC branch ) on my system, after loading game or creating new user when i opened House Scene it was completed by default.

**Expected Behaviour**
The user should click on House Scene and complete it manually by completing the required.

**Observed Behaviour**
The Home scene was completed  by default.

**Mocks**
![power_scr2](https://user-images.githubusercontent.com/23634977/34073456-6859bb64-e2c0-11e7-9797-73225e087711.png)

**Steps to reproduce**
Load Game -> Click on House
New Game -> Create New Avatar -> Click on Continue -> Click on House

**Definition of Done**
- [ ] Resolve the issue
- [ ] Approval by 1 mentor.

@codingblazer @MeepyMay  @aanchal07 @dhara04  please approve so that i can work on this.

**Comment by codingblazer** [comment]
@Masquerade0097 I cannot replicate this issue. Can you upload a gif here. Also, tell us the reason for this problem to get a better idea of it. Thanks.

**Comment by MeepyMay** [comment]
This isn't an issue and can't be replicated, so I'm closing the issue. If @Masquerade0097 can upload a gif, we'll re-open.
