### ISSUE TITLE
Warning: XML Tag has empty body 

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#699]
**Description**
In some XML layout activities -
 
avatar_room.xml,
activity_minesweeper_game.xml
activity_sink_to_swim_game.xml

 there is this warning - 
`XML Tag has empty body`

**Expected Behaviour**
This warning must be resolved.

**Definition of Done**
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Estimation**
< 30 Minutes

**Comment by Masquerade0097** [comment]
@codingblazer Please approve so that i can resolve this issue.

**Comment by Rimjhim28** [comment]
Hey @Masquerade0097 I have reported all the lint issues which includes empty xml tags in #538
