### ISSUE TITLE
Changing access to private instead of public

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#703]
## Description
Most of the classes and methods are declared public which gives a warning in Android Studio but instead they can be made package-private.  This will help counter two problems - 
a) Easier to debug that class or method
b) Would help to reduce the unnecessary Coupling.

I aim to change the access to private for those classes and methods where it is possible to do so. 

## Observed Behaviour
There is this warning - 
`Access can be package-private`

## Steps to reproduce
This warning is present in many java classes. For eg - in AbstractDbAdapter.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Masquerade0097** [comment]
@codingblazer @aanchal07 @MeepyMay Please approve so that I can resolve this error.

**Comment by codingblazer** [comment]
@Masquerade0097 This issue is valid. You can work on this if you want.

**Comment by PiumiHR** [comment]
@geekanamika Can I work on this?

**Comment by PiumiHR** [comment]
@geekanamika yes it is. Thank you. :)

**Comment by ghost** [comment]
@Rimjhim28 @geekanamika I'm a first-timer. Is this issue still open to be worked on?

**Comment by geekanamika** [comment]
I believe that it's already resolved while updating code during gsoc. @Rimjhim28 Correct me if I'm wrong.

**Comment by geekanamika** [comment]
Closing this issue as it's already resolved & it can also be covered under #1101
