### ISSUE TITLE
Invalid layout params in activity_select_features.xml

### ISSUE THREAD

**Issue by arundhati24** [systers/powerup-android#708]
## Description
Currently invalid layout params have been used at several places in the activity_select_features.xml . Such invalid parameters have no effect on the code and they unnecessarily add to the length of the code and create confusion in the mind of the readers/users/developers. 

## Mocks
Here are example screenshots of two such invalid params :
![invalidlayoutparam_1](https://user-images.githubusercontent.com/30979369/34081075-f88d4ef0-e36d-11e7-8016-eefa6503fe75.png)
![invalidlayoutparam_2](https://user-images.githubusercontent.com/30979369/34081078-05f76bd4-e36e-11e7-849d-dffc0cf4fe06.png)

**Comment by arundhati24** [comment]
I would like to fix this issue. May I please proceed with the same?

**Comment by Masquerade0097** [comment]
@arundhati24 I think this issue is included in Issue #538. Please verify.
