### ISSUE TITLE
Disappearance of Home Button

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#725]
## Description

If the home button (located on top right corner) is pressed in mid way of any scenario it takes to Map. Now if the scenario is chosen to be played again, the home button disappears and the user cannot migrate to the map again from the mid of the scenario.
Rectify the implementation of home button such that it does not disappear after the user has used it once.

## Mocks

Not Applicable

## Acceptance Criteria

The home button should not disappear after used once.

## Definition of Done

- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

2 hours

**Comment by grusha02** [comment]
Can I work on this issue?

**Comment by akshaynexus** [comment]
I have fixed this issue ,please see PR https://github.com/systers/powerup-android/pull/740
