### ISSUE TITLE
Include total points dialog box to remove inconsistency of Scenario Over Activity between PowerUp Android and iOS

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#730]
## Description

Currently, in Android version of the app the Scenario Over screen is displayed directly. A better option would be to include a dialog box in Scenario Over screen after the completion of concerned scenario such that it displays the total karma points scored in the scenario. The implementation could be similar to current implementation in iOS version.

## Mocks

Current state of Scenario Over Screen:
![screenshot_2017-12-20-16-47-03-995_powerup systers com powerup](https://user-images.githubusercontent.com/26908195/34204727-c3f8552e-e5a5-11e7-8a18-8261a92b6a5d.png)

Expected Changes:
![img_20171220_163134](https://user-images.githubusercontent.com/26908195/34204610-4c1e0e40-e5a5-11e7-85a8-d57526f6215e.jpg)

![img_20171220_163049](https://user-images.githubusercontent.com/26908195/34204603-46ff2d5e-e5a5-11e7-99b5-0982765ff86b.jpg)

## Acceptance Criteria

Implementation of dialog box so that it pops up after completion of Home, School and Hospital Scene.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by ZoroarkDarkrai** [comment]
Can I work on this? @Rimjhim28

**Comment by ZoroarkDarkrai** [comment]
I can't find the task on the GCI portal. Has someone claimed this or can I work on this? @Rimjhim28

**Comment by Rimjhim28** [comment]
@ZoroarkDarkrai The related task is currently not available to be claimed but will be available soon. Till then go on with other tasks.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28  hii..mam when should the dialogue box be appearing after clicking on continue or just after opening of this page.
