### ISSUE TITLE
Hardcoded column names for DB

### ISSUE THREAD

**Issue by hkasera** [systers/powerup-android#74]
In the [`AbstractDbAdapter.java`](https://github.com/systers/powerup-android/blob/master/PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java#L38), I noticed that we have used hardcoded column names of databases (avatar, questions). Instead, we could create a `DbContract.java` that defines these database schemas. This will help us a lot. I would like to fix this. Is this a welcome contribution right now?

**Comment by alma-castant** [comment]
I assume `DBContract.java` would store the names of the columns as static values to use them as a single instance and avoid errors. This will be a very welcome and needed contribution

**Comment by hkasera** [comment]
Yes, you are right. The contract class will store the column names as static values. I will send a pull request soon. Thank you!

**Comment by hkasera** [comment]
This is merge successfully with PRl #77
