### ISSUE TITLE
Fix conversation flacement in big screens 

### ISSUE THREAD

**Issue by alma-castant** [systers/powerup-android#75]
In horizontal mode AND in big displays, such as tablets, the character speaking and the text associated to them and horizontally aligned. However, since the texts are closer to the other character than to the speaker, the conversation is misleading. The positions of the conversation boxes should be swapped in this cases (not in vertical mode for phones, only for horizontal mode and big displays in any orientation).

**Comment by vasukiarunachalam** [comment]
The current conversation UI looks like this in 10' Tablet. 

![2016-01-29_1037](https://cloud.githubusercontent.com/assets/14137360/12681490/7bc27de0-c674-11e5-9673-b86fc94351ff.png)

In another issue , the conversation boxes are aligned(horizontally) in a line for horizontal display to resolve the space issue. Is this issue same as that or Do we need to make the characters big and also the conversation boxes big for tablets ?

**Comment by alma-castant** [comment]
It's not a size problem. It is that the boy's text is horizontally aligned on the left, being much closer to the girl. Therefore the text boxes should be swapped for the displays mentioned above to avoid this confusion

**Comment by vasukiarunachalam** [comment]
I understand the issue. Currently they are aligned to right and left most edges. The textview and the listview can be re-defined in pgame.xml as aligned closer to characters and then the distance can be defined in various values xml files for bigger screens. Shall I start working on it ?

**Comment by alma-castant** [comment]
Yes, feel free to work on it

**Comment by vasukiarunachalam** [comment]
With slight changes to pgame.xml the conversation appears closer to character only for big screens. 

![2016-02-03_1317](https://cloud.githubusercontent.com/assets/14137360/12804280/633047f2-cab7-11e5-9958-06e8852da205.png)

Small screens still face the problem of avatar character not being displayed properly. ( It is handled in another issue). Shall I make a pull request for this ?

**Comment by alma-castant** [comment]
Yes, feel free to make a PR :)

**Comment by vasukiarunachalam** [comment]
I closed the previous PR and opened a new one for this issue. I tried to squash the commits and ended  up in 7 commits. So I closed that PR. :)

**Comment by top-gun007** [comment]
According to the current version the text box should be more closer to avatar.
Can I correct it
Thank you

**Comment by aanchal07** [comment]
Issue solved so closing this.
