### ISSUE TITLE
Text in Conversation Boxes Overflows 

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#768]
## Description
The text in conversation boxes in scenarios overflows out of boundary in some screen sizes.

## Mocks
![whatsapp image 2017-12-28 at 01 48 46](https://user-images.githubusercontent.com/13872065/34392443-28a3d468-eb72-11e7-9f02-d5ff59d7375f.jpeg)

## Acceptance Criteria
The text should be within the boundary of conversation on all screen sizes and configuration. Add the screenshots for different screen sizes in PR.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by arundhati24** [comment]
@codingblazer May I please work on this issue?

**Comment by Mandeepsinghchadha** [comment]
hii @codingblazer  i have solved this issue and tested on 3 emulaters and my phone it is working fine .Also i have made a pull request for the same.

**Comment by Rimjhim28** [comment]
@Mandeepsinghchadha This issue is taken up for gci. If you are a gci participant wait for the related task to get published.
You should claim the issue before starting to work on it. Please make a note not to send a PR until you are assigned to it.

**Comment by Buddhiprabha** [comment]
The task has been published for GCI participants.

**Comment by Mandeepsinghchadha** [comment]
@Rimjhim28 ....i have closed the pull request now , it didn't have a gci tag when i solved the issue so i thought it was a general issue...

**Comment by vatsalkul** [comment]
I fixed this Issue. PR https://github.com/systers/powerup-android/pull/816
