### ISSUE TITLE
Add "skip tutorial" button to the Vocab Match game

### ISSUE THREAD

**Issue by arundhati24** [systers/powerup-android#774]
## Description
A user who has already played the game before or is re-playing it might wish to skip reading the tutorial every time. Thus, adding a "skip tutorial" button would allow the user, who already knows how to play the game, to directly start playing the game. 

## Mocks
Add a skip button to the following activity :
![activity_vocab_match_tutorial](https://user-images.githubusercontent.com/30979369/34436254-075608c8-ecba-11e7-83f8-5a17c2bd5205.png)

**Comment by arundhati24** [comment]
May I please work on this issue?

**Comment by MeepyMay** [comment]
@arundhati24 Please join the [Systers OS Slack](systers.io/slack-systers-opensource/) to discuss improvements. We're working on a couple other high priority items right now, so I'll add "Open Later" to this issue.

**Comment by arundhati24** [comment]
@m-murad May I now work on this? This issue was closed by @may earlier with the label open later. I had asked again to work on it but there was no reply.. So May I now work on this? :slightly_smiling_face:

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can opened and worked on after discussion on community channel.
