### ISSUE TITLE
Add "skip tutorial' button to the Sink to Swim game

### ISSUE THREAD

**Issue by arundhati24** [systers/powerup-android#775]
## Description
A user who has already played the game before or is re-playing it might wish to skip reading the tutorial every time. Thus, adding a "skip tutorial" button would allow the user, who already knows how to play the game, to directly start playing the game. 

## Mocks
Add "skip tutorial" button in the following activity :
![activity_sink_to_swim_tutorials](https://user-images.githubusercontent.com/30979369/34436325-c4b5ee4c-ecba-11e7-888a-a0e1aecb5c00.png)

**Comment by arundhati24** [comment]
May I please work on this?

**Comment by MeepyMay** [comment]
@arundhati24 Please join the [Systers OS Slack](systers.io/slack-systers-opensource/) to discuss improvements. We're working on a couple other high priority items right now, so I'll add "Open Later" to this issue.

**Comment by arundhati24** [comment]
@m-murad May I now work on this? This issue was closed by @may earlier with the label open later. I had asked again to work on it but there was no reply.. So May I now work on this? :slightly_smiling_face:

**Comment by geekanamika** [comment]
@arundhati24 This will be an enhancement to the current application(every enhancement should be discussed first) . Discuss it on slack & if admin/mentors will approve , you can work on it :) Same goes for #774 & other issues related to skip tutorial.

**Comment by pprathameshmore** [comment]
@arundhati24 Skip button must be required!

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can opened and worked on after discussion on community channel.
