### ISSUE TITLE
Add "skip tutorial" button to the Minesweeper game

### ISSUE THREAD

**Issue by arundhati24** [systers/powerup-android#776]
## Description
A user who has already played the game before or is re-playing it might wish to skip reading the tutorial every time. Thus, adding a "skip tutorial" button would allow the user, who already knows how to play the game, to directly start playing the game.

## Mocks
![activity_minesweeper_tutorials](https://user-images.githubusercontent.com/30979369/34436359-310a22a2-ecbb-11e7-835a-01fa2d74db70.png)

**Comment by arundhati24** [comment]
May I please work on this?

**Comment by apoorvaagupta** [comment]
Hello, Is this issue approved by the mentors? 
i would like to work on it.

**Comment by arundhati24** [comment]
Hey @apoorvaagupta , please have a look at other issues. I opened this issue and I would like to work on this if the mentors approve it.

**Comment by MeepyMay** [comment]
@arundhati24 Please join the [Systers OS Slack](systers.io/slack-systers-opensource/) to discuss improvements. We're working on a couple other high priority items right now, so I'll add "Open Later" to this issue.

**Comment by arundhati24** [comment]
Okay @MeepyMay :+1:

**Comment by arundhati24** [comment]
@MeepyMay @prachi1210  May I now reopen this issue? :slightly_smiling_face:

**Comment by arundhati24** [comment]
@m-murad May I now work on this? This issue was closed by @may earlier with the label open later. I had asked again to work on it but there was no reply.. So May I now work on this? :slightly_smiling_face:

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
