### ISSUE TITLE
Implement Stars to Minesweeper Activity and change NUMBER_OF_ROUNDS

### ISSUE THREAD

**Issue by ZoroarkDarkrai** [systers/powerup-android#804]
## Description

- Everything is ready for minesweeper to have 3 rounds.
- The tutorial indicates that there will be stars to show remaining flip which hasn't been implemented.

## Mocks
![mine1](https://user-images.githubusercontent.com/27900940/34470139-96eea62a-ef5d-11e7-808b-4e5a427cce49.PNG)
Current NUMBER_OF_ROUNDS is 1.
![mine4](https://user-images.githubusercontent.com/27900940/34470143-a3ac89fe-ef5d-11e7-8077-8926e55d6a9e.PNG)
All is set to have 3 rounds.
![screenshot_1514830833](https://user-images.githubusercontent.com/27900940/34470147-b45abc1c-ef5d-11e7-82b7-3a6c0d8d5177.png)
Tutorial indicates there will be stars.
![screenshot_1514830836](https://user-images.githubusercontent.com/27900940/34470149-c0325964-ef5d-11e7-843d-0d140e9a4b4a.png)
No stars are currently implemented.

### Update [Required]
- [ ] Change NUMBER_OF_ROUNDS to 3
- [ ] Implement stars 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
7-8 hours.

@Rimjhim28 @codingblazer Can I work on this? Oh, which one is better make the stars disappear one by one or make it light up one by one too?

**Comment by codingblazer** [comment]
@ZoroarkDarkrai The number of rounds are intentionally kept to 1. Later, we will have more contraceptives and hence more rounds.
As for the stars present in tutorial, that needs discussion with design team. I suggest to not include it because it won't be good design to use stars repeatedly. The stars are used for boxes and using stars in same design for something different won't be good design decision. Discuss about this with @kimhwins and then we can work on it.

**Comment by ZoroarkDarkrai** [comment]
@codingblazer Oh, sorry I didn't know about that I thought it was just a missing feature :sweat_smile:. 
@kimhwins is the basic idea the same but with different icons (like heart, clover, smiley face, etc)? If it's still simple icon maybe I could try to help. ^__^
Thank you for your time.

**Comment by MeepyMay** [comment]
I'm closing this issue for now and discussing with Design team. I think we discussed in GSoC17, which means the tutorial screens themselves need to be updated instead.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can opened and worked on after discussion on community channel.
