### ISSUE TITLE
Add squashing commits instructions to README

### ISSUE THREAD

**Issue by ValentunSergeev** [systers/powerup-android#831]
## Problem
Hi, I noticed that a lot of new participants/contributors don't know how to squash commits when the mentor/maintainer ask them to do it.
So I think it will be good to add squashing commits instructions to reduce all explanations to the reference to README.

### Required changes

- [ ] Add intructions to `README.MD` file

### Definition of Done
 All of the required items are completed.
 Approval by 1 mentor.

 ## Estimation time
30 minutes
  
@Rimjhim28 @codingblazer how do you think is it a good idea?

**Comment by anandwana001** [comment]
@ValentunSergeev I would like to work on this.
Do I have to put solution here only, to get the acceptance?

**Comment by ValentunSergeev** [comment]
@anandwana001 it's issue not approved by mentor yet. @codingblazer @Rimjhim28

**Comment by anandwana001** [comment]
ok, I may update with a solution here! maybe they like or approve this.

**Comment by ValentunSergeev** [comment]
@anandwana001 you may create a solution, but please open a pull request AFTER the issue's approval. Its required by project code guild lines

**Comment by anandwana001** [comment]
yeah sure, I will be doing things according to guidelines only

**Comment by anandwana001** [comment]
### New Contributors
#### Squash Commits 
Squash Commits means when you have a list of commit and you want to make it one commit or you may get asked from any mentor to squash the commits, so here are the steps you can follow:
1. `git log`
     * you get the log of last commits on the branch, which you are working!
2.  `git branch`
     * you can check, on which branch you are!
3. `git rebase -i master`
      * this command will show up a list of all commits
4. leave the commit as `pick` only which you want to be the main commit, and change other commits as `squash` which you want to include in the main commit
It will look something like this:
```
pick fb554f5 commit 1
squash 2bd1903 commit 2
squash d987ebf commit 3
```
run this command and then you can force push if you already submitted a pull request by 
`git push -f`

**Comment by MeepyMay** [comment]
Closing for now. We're adding this to the org-wide level site: systers.io Thank you for bringing it up! 
I'd recommend adding it to the [systers.github.io](https://github.com/systers/systers.github.io) repo.
