### ISSUE TITLE
Crash when pressing replay button

### ISSUE THREAD

**Issue by ValentunSergeev** [systers/powerup-android#849]
## Steps to reproduce
1. Complete any Scenario
2. Finish the app
3. Start app, load the game
4. Choose completed scenerio and press replay

Frequency: 100%
## Mocks
![screenshot_2018-01-06-00-25-25-965_powerup systers com powerup](https://user-images.githubusercontent.com/18180597/34620468-229f48c4-f278-11e7-940c-791e1c1039da.png)

### Update
- [ ] Fix crash

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by ValentunSergeev** [comment]
@codingblazer can I work on that?

**Comment by Rimjhim28** [comment]
@ValentunSergeev The issue related with replay button is reported on #500. The related PR for the issue handles the app crash and is yet to be merged. Once the PR is merged the remaining handling of replay button could be figured out more properly.

**Comment by ValentunSergeev** [comment]
@Rimjhim28  ok, then I'll close it.
