### ISSUE TITLE
Test Missing

### ISSUE THREAD

**Issue by opticod** [systers/powerup-android#85]
Currently there are no tests.
What about adding UI Espresso based test? Should I progress in this?

**Comment by alma-castant** [comment]
Sounds good. Feel free to assign the issue to yourself

**Comment by chhavip** [comment]
This sounds interesting and something I would like to try too, @opticod can you state which activities will you write tests for so I can look at some other?

**Comment by opticod** [comment]
@chhavip ,thank you for your interest...Actually I have already planned about different activites...its more or less similar.

**Comment by opticod** [comment]
Thank You @alma-castant  for assigning.I will definitely make a PR with the tests.

**Comment by alma-castant** [comment]
Please @opticod make the setup for testing and add here a list of the tests you are planning to perform so other contributors can also make others. You should create one PR per test

**Comment by opticod** [comment]
In my PR ,I will be writing test on UI only..
Others contributors...can test for different DB tests...Its missing also

**Comment by alma-castant** [comment]
@opticod The UI has different parts, so please be kind and add the list here

**Comment by opticod** [comment]
-  In AvatarActivity ,I will be testing all the Image views are correctly displayed,and click events are occuring correctly.
- In AvatarRoomActivity, I will be testing the all the  Imageview and smae click events
- In GameActivty, I will be testing the image and text view and its click events
can i progress with this tests  or u want to divide ?

**Comment by opticod** [comment]
Sorry @alma-castant , if i made any mistake..

**Comment by alma-castant** [comment]
Thank you @opticod

**Comment by abs51295** [comment]
@alma-castant @chhavip It seems that tests are not integrated. Can I work on it?

**Comment by aanchal07** [comment]
The database has been updated since this issue so closing it for now.
