### ISSUE TITLE
Using Data Binding

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#861]
## Description
Instead of using findViewById again and again and reprocess the entire layout file again and again, data binding should be used which reduces the app's runtime by traversing the layout file only once and binding them to set click listeners, write declarative layouts and minimize the glue code necessary to bind your application logic and layouts. In total this makes the code clean as well as improve performance.

## Mocks
Not applicable

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Masquerade0097** [comment]
@codingblazer I would like to work on it. Please review.

**Comment by codingblazer** [comment]
Hi, these type of major changes will be taken up in next development cycle. We will come back to this later.

**Comment by Rimjhim28** [comment]
@Masquerade0097 Are you working on this??
If no, I would like to proceed with it.

**Comment by MeepyMay** [comment]
Since no one on the maintainers team have discussed the best practices for data binding, we're closing this issue for now. Whatever happens to one Android project, we'd like to continue for all.

**Comment by geekanamika** [comment]
Similar to #1078 . It can be closed.
