### ISSUE TITLE
Using Timber for logging and Crash analytics

### ISSUE THREAD

**Issue by Masquerade0097** [systers/powerup-android#862]
## Description
Benefits of Timber Library - 

1. No Tags required in logging messages.
2. Developer can add custom logging engines(called Trees) for custom logging. 
3. Single log statement can print log on logcat and report to some other source like Crashlytics

## Mocks
Not applicable

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

@codingblazer Please review, I wanna work on it.

**Comment by codingblazer** [comment]
Hi, that can be useful for the project. Please go ahead if you want.

**Comment by tanvidadu** [comment]
@Masquerade0097  any progress ?

**Comment by Masquerade0097** [comment]
@tanvidadu I ain't working on that, feel free to work on it.

**Comment by Rimjhim28** [comment]
@Masquerade0097 Can I work on it?
