### ISSUE TITLE
Retain of AppState on Orientation Change

### ISSUE THREAD

**Issue by opticod** [systers/powerup-android#88]
Currently on changing the orientation of App.The AppState gets lost and we are set to default one.

While Writing test for PR #87 ,I encountered this.
I will make a PR to fix this shortly. :smile:

**Comment by MKDEVELOPEMENT** [comment]
is this still up for grabs?

**Comment by chhavip** [comment]
Yes you can take up this task, make sure the app state is retained in every screen on orientation change.
