### ISSUE TITLE
Set Check-Mark Specifically to Equipped Item [StoreActivity]

### ISSUE THREAD

**Issue by Aryaman21** [systers/powerup-android#881]
## Description
Right now, there seems no correct demarcation for a user to be able to know which item he has equipped, be it Hair, Accessory or Clothes. To give the user a sign that an item is selected, the green check mark already implemented in the can be used, that would mean that the check mark appears only on the item that is selected in the category.
## Mocks
- Both the items are titled "Select" creating ambiguity

![select item](https://user-images.githubusercontent.com/19228432/34684195-4da4e78c-f4ca-11e7-9d71-cf9f43ef6894.png)

### Updates
- [ ] [Background Card for Selected Item]
- [ ] [Proper Code Implementaion of Selected Item]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by Aryaman21** [comment]
@Rimjhim28 @codingblazer Please review the issue. Will start working on this after approval.

**Comment by m-sameer** [comment]
A better way, in my opinion, would be to show the green check mark only on the item currently selected for the avatar.

**Comment by Aryaman21** [comment]
Yes, that seems the optimum solution, it would be much efficient to do that. Thanks for the suggestion, I'll include this solution in the description. Thanks @m-sameer

**Comment by m-sameer** [comment]
My pleasure! :)

**Comment by Rimjhim28** [comment]
@Aryaman21 Would you mind if this issue is taken up for GCI?

**Comment by Aryaman21** [comment]
I'd be glad to submit as a GCI task. @Rimjhim28
