### ISSUE TITLE
Add 'Already Selected' Dialog Box [StoreActivity]

### ISSUE THREAD

**Issue by Aryaman21** [systers/powerup-android#886]
## Description
As a user, there is no prompt when I tap on an already bought and selected item in the StoreActivity. Thus it is not possible for the user to know whether the item he is choosing is already integrated into the avatar or not. As a small improvement to the user experience, a new AlertDialog can be integrated into the Store Activity, with the title - 'Already Selected', message - 'This item is already chosen' and an option with "OK" button to dismiss the dialog.

## Mocks
![device-2018-01-08-155036](https://user-images.githubusercontent.com/19228432/34725618-7701d024-f577-11e7-9b1c-b3895af9629f.png)

### Update 
- [ ] [Include new AlertDialog Invocation]
- [ ] [Proper Code Implementation of AlertDialog]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by Aryaman21** [comment]
@codingblazer @Rimjhim28 @MeepyMay @aanchal07 please review the issue.

**Comment by Rimjhim28** [comment]
@Aryaman21 Would you mind if this is taken up as a task for GCI?

**Comment by Aryaman21** [comment]
Not at all, I'd be glad to do it as part of a GCI task. @Rimjhim28
