### ISSUE TITLE
Move database to ORM

### ISSUE THREAD

**Issue by chhavip** [systers/powerup-android#89]
Currently the database is maintained locally converted from csv files which is a process that can get cumbersome if the data grows. I suggest Sugar ORM [http://satyan.github.io/sugar/getting-started.html] as it will make handling the data easier, make querying simpler and also reduce a lot of code, leading to reduced application size. This task can be a long one though and may require some discussion.

**Comment by elpoisterio** [comment]
I would like to work on this issue. What has to be changed?

**Comment by aanchal07** [comment]
I would like to work on this.
