### ISSUE TITLE
Take the character's name from user

### ISSUE THREAD

**Issue by medhach** [systers/powerup-android#90]
We can take the name of the user as input and display it in the points bar during the game. It increases the user's interest and makes the app more dynamic.

**Comment by AaskaShah** [comment]
If this needs to be done,can I work on this?

**Comment by medhach** [comment]
@AaskaShah  I will work on this, I want a green signal from the mentor before I start with it. I'm sorry. :)

**Comment by AaskaShah** [comment]
No problem :)

**Comment by alma-castant** [comment]
I think such a change should be discussed with project managers so both Android and iOs versions of the application are coherent. I would not work on it for now ;)
