### ISSUE TITLE
Add Ripple Effect in Conversations

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#903]
## Description
When the user selects any dialogue in the conversation of scenarios, add a ripple effect to the selected item in the listview.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by ShriyaSalian** [comment]
Is the task open to others or would you be working on this? @codingblazer 
If so, I would love to work on this

**Comment by arya-ayush** [comment]
@codingblazer May I work on this issue?
