### ISSUE TITLE
Reduce time for next question in SinkToSwim

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#905]
## Description
When the "?" is chosen as option in SinkToSwim Game, the next question takes a lot of time to load. We want to reduce this time for the user.

## Acceptance Criteria
The time should be reduced such that the fade animation on text of question is still noticeable.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ShriyaSalian** [comment]
Can I work on this issue, if it's open? @codingblazer
