### ISSUE TITLE
Trial of item before purchase in store

### ISSUE THREAD

**Issue by ShriyaSalian** [systers/powerup-android#923]
## Description
As of now, as soon as the user selects any item in the store, the item gets purchased. Neither is there any trial of the item before purchase nor any confirmation of the same.

## Mocks
Not applicable

### Update [Required]
- [ ] When the user purchases in the store there should be a trial as well as a confirmation button before purchase.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-6 hours 

@codingblazer Please review, I would like to work on this.

**Comment by ZoroarkDarkrai** [comment]
@ShriyaSalian Your issue is really similar to this one https://github.com/systers/powerup-android/issues/852 . There are already several PRs fixing your issue which can be seen on the issue page.

**Comment by ShriyaSalian** [comment]
Yes, you're absolutely right @ZoroarkDarkrai 
Thank you for mentioning

**Comment by Rimjhim28** [comment]
A similar issue exist and PRs have already been sent.
@ShriyaSalian Go through the contributing guidelines once before opening any new issue.
Since this is duplicating an older issue, you can close this one.

**Comment by ShriyaSalian** [comment]
Ma'am, there is no issue regarding trial of item before purchase as far as I have gone through. My issue suggests the item can be seen on the avatar when clicked and then there would be a confirmation pop up. @Rimjhim28 
Kindly let me know if I am wrong :)

**Comment by MeepyMay** [comment]
If we're changing the functionality of how the store works, we will need to check in with the iOS team as well.

**Comment by geekanamika** [comment]
Similar issue already exists.
