### ISSUE TITLE
Design Improvements in the Final Screen [GameOverActivity]

### ISSUE THREAD

**Issue by Aryaman21** [systers/powerup-android#953]
## Description
The Final Game screen includes an unformatted message which looks quite untidy, the overall layout of the text is not in accordance with the UI of the application, it could be displayed in a well-formatted dialog (Refer to Fig 1 for an example) in order to make it more visually appealing. The Map button can be improved, it appears a little stretched in the view. Thus, the whole design in the background will have to be changed for a better layout. The inclusion total karma points has been carried out via a GCI task so the new changes should be in accordance with that.

### Figure 1
![final_avatar_title](https://user-images.githubusercontent.com/19228432/34944369-4fd7a7a0-fa25-11e7-979f-d9efa36105ca.png)

## Mocks
![device-2018-01-14-173126](https://user-images.githubusercontent.com/19228432/34919601-b2dfc24a-f98c-11e7-942a-91b5c0a3196f.png)

### Update
- [ ] Re-format layout for final screen
- [ ] Proper Formatting of Text
- [ ] Re-configure Map Button to go in accordance with the UI

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
- 3-4 hours

**Comment by Aryaman21** [comment]
@Rimjhim28 @codingblazer @MeepyMay @aanchal07 Please review the issue, I'd like to work on it.

**Comment by apoorvaagupta** [comment]
Hello, Is this issue approved by the mentors?
I would like to work on it.

**Comment by Akanshi32** [comment]
Hi, I would like to work on this issue. 
@codingblazer  @anubhakushwaha  @MeepyMay

**Comment by Rimjhim28** [comment]
@Aryaman21 Since this requires a UI change please discuss on slck first.
Closing the issue for now. If any decision is reached, you can reopen it.
