### ISSUE TITLE
Debugging with Stetho

### ISSUE THREAD

**Issue by ShriyaSalian** [systers/powerup-android#960]
## Description
An Android debugging bridge such as Stetho would be of great use to debug the layouts as well as see database changes . I propose to implement the use of Stetho for debugging.
Using Stetho we can remotely debug our app using Chrome DevTools

## Mocks
Not Applicable

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
48 hours

**Comment by ShriyaSalian** [comment]
@codingblazer @aanchal07  @MeepyMay Please review, I would like to work on this :)

**Comment by MeepyMay** [comment]
Closing for now. GitHub maintainers are going to chose best tools/practices for Android projects as a whole. If Stetho gets approved, we'll open an issue in all of the Android repos.

**Comment by ShriyaSalian** [comment]
Okay @MeepyMay  :)

**Comment by Rimjhim28** [comment]
Closing the issue for nw. This can be opened after discussion with the community on stheto.
