### ISSUE TITLE
Using Butter Knife for view injection

### ISSUE THREAD

**Issue by ShriyaSalian** [systers/powerup-android#961]
## Description
Butter Knife is a light weight view-binding library to inject views into Android components using annotation process. It helps to bind fields, methods and views and generates boilerplate code.
The library is open source and it will make the code more maintainable and easier to read.

## Mocks
Not Applicable

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
48 hours 

@codingblazer @MeepyMay @aanchal07 Please review, I would like to work on this. :)

**Comment by m-sameer** [comment]
@ShriyaSalian [Data Binding](https://developer.android.com/topic/libraries/data-binding/index.html) library is also a good choice. It is much more powerful than Butter Knife. :)

**Comment by geekanamika** [comment]
A similar issue has been created in #861 . :)

**Comment by arya-ayush** [comment]
@ShriyaSalian May I work on this issue?
And if I'm right then the task that is to be done is to bind all views, click methods, etc. using butterknife.

**Comment by ZoroarkDarkrai** [comment]
@arya-ayush Please see the comment above you. A similar issue has been created, please go see that one. ^__^

**Comment by arya-ayush** [comment]
Yes, but the code hasn't implemented either of the two.So, what to implement in order to close this issue?

**Comment by ZoroarkDarkrai** [comment]
@arya-ayush I just recommended you to comment on the first opened issue so there won't be duplicate issues about the same thing. And if you see the comment on the first issue, this change will be taken in the next development cycle.

**Comment by MeepyMay** [comment]
Since no one on the maintainers team have discussed the best practices for data binding, we're closing this issue for now. Whatever happens to one Android project, we'd like to continue for all.
