### ISSUE TITLE
Add haptic feedback to the mini-games

### ISSUE THREAD

**Issue by m-sameer** [systers/powerup-android#962]
## Description
When the user plays any of the mini-games there's no haptic feedback provided to the user. For more immersive game experience haptic feedback must be provided to the user as described:
- In **Minesweeper** game, the phone must vibrate when red mine is opened. 
- In **Sink to Swim** game, the phone must vibrate on selecting the wrong answer.
- In **VocabMatch** game, the phone must vibrate on a wrong match.

## Acceptance Criteria
Haptic feedback must be provided in all the mini-games.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

**Comment by Mandeepsinghchadha** [comment]
hi @m-sameer   is this issue approved by the mentors ? If yes then i want to work on this issue kindly brief me with the details.

**Comment by m-sameer** [comment]
@Rimjhim28 @MeepyMay @codingblazer Please tell me if this issue is approved by any one of you.

**Comment by MeepyMay** [comment]
Not approved. There is no requirement for haptic feedback right now. We'll push the idea to the "Open Later" issues to focus on higher priority items right now.

**Comment by Rimjhim28** [comment]
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.
