### ISSUE TITLE
TEXT OVERFLOWING FROM THE TEXT BOXES IN SCENARIOS

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#965]
Description
Right now the text in various scenarios is running out of text boxes which reduces the face value of frontend/UI of the app.
(https://user-images.githubusercontent.com/27005975/35188470-b3dca2fc-fe5b-11e7-9001-af70140cee3c.png)

 Acceptance Criteria
The text in various scenarios like school,hospital must be well inside the text boxes in all screen sizes for consistency.Provide screenshots for different screen sizes as well 

Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
 Estimation
3-4 hours

**Comment by Mandeepsinghchadha** [comment]
Hii.   @codingblazer @MeepyMay  @aanchal07  can i work on this issue ?

**Comment by ZoroarkDarkrai** [comment]
This issue has been opened before https://github.com/systers/powerup-android/issues/768. And there are PRs waiting to be merged. @Mandeepsinghchadha
