### ISSUE TITLE
Enhancement of About Page 

### ISSUE THREAD

**Issue by Prashant-Chaurasia** [systers/powerup-android#966]
## Description
The present UI is not looking good having a scrollable box with three questions.What we could do is that separate all these questions in separate cards and make the whole layout scrollable. Also, change the color of the fonts.

### Update [Required]
- [ ] Each question on different cards
- [ ] Improved UI(in terms of text color and size)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by Prashant-Chaurasia** [comment]
Please review this issue. I would like to work on it.

**Comment by Prashant-Chaurasia** [comment]
@MeepyMay @aanchal07 please review this issue.

**Comment by tanvidadu** [comment]
can you share some mock ups ?

**Comment by MeepyMay** [comment]
This isn't approved. We're doing some changes for the setup of the game. Little enhancements like this will be fixed along the way.
