### ISSUE TITLE
Crash on installing app first time or starting new game

### ISSUE THREAD

**Issue by sammy1997** [systers/powerup-android#968]
## Description
Start the app for the first time after installation or build. Click on the first scene. It shows sene already played. Play again causes a crash.

![powerup_error](https://user-images.githubusercontent.com/24635701/35857707-eeb945b8-0b5f-11e8-92f3-e1a96cb79e60.png)

This is the error it shows
## Acceptance Criteria
- [ ] When the app does not crash on opening for the first time.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

@codingblazer @anubhakushwaha Please review this.

**Comment by sammy1997** [comment]
I would like to work on this issue.

**Comment by sammy1997** [comment]
@tanvidadu @MeepyMay @anubhakushwaha @codingblazer Please review this.

**Comment by sammy1997** [comment]
@codingblazer @anubhakushwaha @MeepyMay Please review this. This is causing a crash. I would like to work on this.

**Comment by geekanamika** [comment]
@sammy1997 Can you please mention , which branch code is creating crash on first installation of application and on which device with API level ?

**Comment by sammy1997** [comment]
@geekanamika The branch is develop, and as far as API is considered I have been able to reproduce it on 24 and 25. Rest I haven't tested. I think I can solve this issue. I have been able to localise the error. I would like to work on this.

**Comment by sammy1997** [comment]
@MeepyMay @anubhakushwaha Please review this once

**Comment by geekanamika** [comment]
@sammy1997 GSoc17 branch contains the GCI PR updates , it will be merged soon in develop hopefully. Please check whether the same error persists for Gsoc17 or not.

**Comment by aayushinigam** [comment]
@geekanamika @Rimjhim28 I don't think this issue still persits. I uninstalled it and installed it again. Issue could be closed maybe?
