### ISSUE TITLE
Database error in Home Scene

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#969]
## Description
The "Remains quiet" option in Home scenario does not work as expected. Instead of being to a different dialouge, the user is stuck there. Multiple clicks on the option keeps on increasing the karma points that can be seen on Scenario Over screen.

## Mocks

![videotogif_2018 02 03_14 55 12](https://user-images.githubusercontent.com/26908195/35765977-03b31204-08f5-11e8-8a61-02808145868a.gif)

### Update
- [ ] Modifications in Answer.csv

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours 

I would like to work on this issue.

**Comment by ShriyaSalian** [comment]
Similar issue had been opened by me in #845 :)

**Comment by Rimjhim28** [comment]
@ShriyaSalian It's not all similar to #845. Your issue aims to refractor the who database while the one created here is actually a bug that needs to be handled. Please have a close look at the .gif attached.

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.
