### ISSUE TITLE
Errors generated while trying to access eyes while creating Avatar

### ISSUE THREAD

**Issue by sammy1997** [systers/powerup-android#973]
## Description
Start app for first time. Start creating the avatar. Keep watching logs. Eyes 8 and 9 generate errors. 

## Mocks
![power_up_avatar](https://user-images.githubusercontent.com/24635701/35768240-af829a2c-091e-11e8-8da8-7af097ca56cb.png)

## Acceptance Criteria
- [ ] Remove this error - NoSuchFieldException caused by this.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 mins

**Comment by sammy1997** [comment]
I would like to work on this.

**Comment by sammy1997** [comment]
@codingblazer @anubhakushwaha Please review this

**Comment by sammy1997** [comment]
@anubhakushwaha @may please review this PR.

**Comment by geekanamika** [comment]
Hi @sammy1997 , This is a valid issue although according to the contribution guidelines , You should create a PR only if it is approved by one mentor/maintainer :)

**Comment by geekanamika** [comment]
Hi @sammy1997  , As per contribution guidelines,  Please don't create a pull request unless approved by mentor :) You can work on your fork and it would be considered as an contribution too :)

**Comment by geekanamika** [comment]
It might be similar to #797
