### ISSUE TITLE
A SQLiteConnection object for database was leaked

### ISSUE THREAD

**Issue by sammy1997** [systers/powerup-android#976]
## Description
Each of the scenes use the DatabaseHandler but the cursor connection doesn't get closed after all transactions end. This causes 

##ERROR

A SQLiteConnection object for database '/data/user/0/powerup.systers.com.powerup/databases/PowerUpDB' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

## Acceptance Criteria
- [ ] Leak is stopped for all scenarios.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 mins

@codingblazer  @anubhakushwaha Please review this.

**Comment by sammy1997** [comment]
I have already solved this issue. So I would like to work on this.

**Comment by Rimjhim28** [comment]
The code is updated to use room library so the issue can be closed.
