### ISSUE TITLE
TEXT TO VOICE

### ISSUE THREAD

**Issue by Mandeepsinghchadha** [systers/powerup-android#977]
## Description
Since this is educational game we have to target as many girls to use our app to spread awareness 
.So to make the conversations in form of text to be more interactive we can add text to speech in the conversation in all scenarios.

## Acceptance Criteria
Approved by the mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Mandeepsinghchadha** [comment]
I have worked on this issue and i have sent a pull request for the same.Mentors kindly approve it

**Comment by shivanshsoni** [comment]
Anyone working on this issue??

**Comment by Mandeepsinghchadha** [comment]
yess..this was made by me and i have already worked and sent a pull request for the same

**Comment by shivanshsoni** [comment]
OK thanks

**Comment by geekanamika** [comment]
This should be accepted first in #ideas channel , closing it for now.
