### ISSUE TITLE
Creating adaptive UI for larger screen devices

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#979]
## Description
When the app is run on devices with larger screen like a tablet, there are several places where the text appears too small to be read.
The text for hairs, clothes and skin appear a bit lower than are expected.
Conversation boxes appear too small.
Continue button appears a bit small and could be resized.

## Mocks

![screenshot_1517821697](https://user-images.githubusercontent.com/26908195/35796630-2e717136-0a83-11e8-83e0-90d6e1c2c1f4.png)

![screenshot_1517821705](https://user-images.githubusercontent.com/26908195/35796633-3055603e-0a83-11e8-9718-58fadd9b6afd.png)

![screenshot_1517821713](https://user-images.githubusercontent.com/26908195/35796636-31ed40f6-0a83-11e8-8a94-30be3acbd490.png)

![screenshot_1517821755](https://user-images.githubusercontent.com/26908195/35796638-32da1db8-0a83-11e8-8ef1-676398cfa518.png)

![screenshot_1517821816](https://user-images.githubusercontent.com/26908195/35796761-8c20b364-0a83-11e8-84fd-9a5c47cf0031.png)

### Update
- [ ] Include proper dimensions in dimens.xml for different screen widths.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours 

I would like to work on the issue.

**Comment by sammy1997** [comment]
I would like to work on this.

**Comment by Rimjhim28** [comment]
@sammy1997 I have mentioned on the issue itself that I will be working on it. Please find other open issues (if available) and claim to work on them.
As far as this one is concerned, I have almost done the work and will be sending the PR after it gets approved.

**Comment by sammy1997** [comment]
Okay. Sorry @Rimjhim28 I didn't see that you claimed the task.

**Comment by Rimjhim28** [comment]
I will update this task firther and open another issue
