### ISSUE TITLE
Repetitive declaration of strings for item names to access drawables

### ISSUE THREAD

**Issue by sammy1997** [systers/powerup-android#981]
## Description
Strings for the starting names of drawable files ( like eyes, skin, hair etc) have been declared multiple times in multiple activities. We can use static strings and declare them in a class. We can use this class to get the names.

## Mocks
![avataract](https://user-images.githubusercontent.com/24635701/35856882-573c74aa-0b5d-11e8-9e72-7ed97ecb086c.png)
![gameact](https://user-images.githubusercontent.com/24635701/35856884-57722b9a-0b5d-11e8-92e4-256ea05285b3.png)
![storeact](https://user-images.githubusercontent.com/24635701/35856885-57ce425e-0b5d-11e8-905b-f38b808bc3f1.png)

## Acceptance Criteria
- [ ] Remove the repetitive declaration of strings

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20-30 mins

**Comment by sammy1997** [comment]
@MeepyMay @anubhakushwaha @codingblazer Please review this.
I would like to work on this.

**Comment by tanvidadu** [comment]
The strings are already declared in strings.xml file.  
<img width="512" alt="mockup" src="https://user-images.githubusercontent.com/29161745/35903374-e2df5d5e-0c04-11e8-8324-41a25969cc88.png">

**Comment by sammy1997** [comment]
@tanvidadu What I meant was We are adding additional variables and lines of code to utilise these. Instead we can either directly replace the variables by getResources().getStrin(...) . That would decrease readability. Or we can declare these strings as constants in a class and access these static variables directly. Its repeatedly used in 3 activities. @anubhakushwaha @MeepyMay What are your views?

**Comment by geekanamika** [comment]
@sammy1997 Using getResources().getString() in a one line is a better approach (in my opinion). It wouldn't make sense to create constant variable for something that is already defined in strings.xml

**Comment by Rimjhim28** [comment]
@geekanamika I think this can be closed.
