### ISSUE TITLE
Upgrade gradle and buildTools and sdk versions 

### ISSUE THREAD

**Issue by sammy1997** [systers/powerup-android#983]
## Description
Power Up uses gradle version 2.4, sdk and build tools version 23. Also as an enhancement we can make it compatible on Android Studio 3.0

## Mocks
N.A.
## Acceptance Criteria
- [ ] Upgrade gradle, sdk and build tool versions. The app should not generate new errors or warnings.
### Enhancement to Update [Optional]
- [ ] Compatible on AS 3.0

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sammy1997** [comment]
@anubhakushwaha @MeepyMay Please review this. This is a much needed change.

**Comment by geekanamika** [comment]
@sammy1997 A similar issue has already been created in #540 . As per contribution guidelines, please create an issue only if it doesn't exists already :)

**Comment by MeepyMay** [comment]
Closing issue. @ageekanamika thank you for referencing the opened issue.
