### ISSUE TITLE
Remove redundancy in AndroidManifest.xml 

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#985]
## Description
Currently , manifest file contains *android:screenOrientation="landscape"* in every activity tag. It's very redundant.

## Solution
Better approach would be to create a class which extends *Application* , register an ActivityLifecycleCallbacks object & set screen orientation to landscape inside *setRequestedOrientation* function. 
At the end, set inside application tag in manifest file : *android:name=".SetLandscapeClass"*
For reference : [Stackoverflow discussion](https://stackoverflow.com/questions/6745797/how-to-set-entire-application-in-portrait-mode-only)

## Acceptance Criteria
It would contains a class which extends application and all the functionalities will work properly as before.
### Update 
* AndroidManifest.xml
* Creation of new class file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by geekanamika** [comment]
@codingblazer @anubhakushwaha @MeepyMay Can I work on this issue ?

**Comment by tanvidadu** [comment]
Good Idea. If mentors approve this you can go ahead with this !

**Comment by geekanamika** [comment]
@tanvidadu @m-murad @saurabhjn76 Please approve this issue.

**Comment by geekanamika** [comment]
I tried above approach as mentioned in issue, couldn't solve the problem, app crashes everytime, closing this issue.
