### ISSUE TITLE
Remove Null Pointer Exceptions 

### ISSUE THREAD

**Issue by PrajwalM2212** [systers/powerup-android#990]
## Description
There are plenty of null pointer exceptions present in the project and they can be removed.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- Many Classes in the project

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 1 hour

**Comment by PrajwalM2212** [comment]
@codingblazer @anubhakushwaha @MeepyMay I would like to work on this issue .

**Comment by geekanamika** [comment]
@PrajwalM2212 Can you please specify the classes & functions and how you aim to resolve them ? A detailed description is usually expected :)

**Comment by PrajwalM2212** [comment]
The exceptions are present in every class of the project . In every class there are a handful of them . I have already resolved it .☺

**Comment by Rimjhim28** [comment]
@PrajwalM2212 Are you still working on this?
Poviding some instances would be a better option since it would give a better option on what you intend to solve and how.

**Comment by Rimjhim28** [comment]
Closing the issue since the description is not sufficient.
