### ISSUE TITLE
Remove inconsistencies between Avatar Room and Final Avatar Screen 

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#994]
## Description
Currently, the backgrounds of avatar room and final avatar screen are different. This looks inconsistent.
The final avatar screen should have the correct background to remove inconsistency.
Also the orientation of the screen should be changed to landscape.

## Mocks

Avatar room:
![screenshot_2018-02-14-02-27-27-285_powerup systers com powerup](https://user-images.githubusercontent.com/26908195/36173971-c301421e-1130-11e8-8f31-3ca4ac8913ae.png)

Final Avatar Screen:
![screenshot_2018-02-14-02-27-30-479_powerup systers com powerup](https://user-images.githubusercontent.com/26908195/36173975-c494a90e-1130-11e8-8c62-357900b04915.png)

### Update 
- [ ] Change to correct background in final_avatar.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes.

**I would like to work on this issue.**

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by m-murad** [comment]
This might not be a bug but a desired feature. Please discuss this on slack first.

**Comment by Rimjhim28** [comment]
@m-murad I have already discussed this on slack. The contributors feel this is a valid issue. Can I proceed now?

**Comment by Rimjhim28** [comment]
@m-murad @geekanamika I have already discussed this on channel.
Link to conversation: https://systers-opensource.slack.com/archives/C0C9VK8UE/p1521031644000577

**Comment by ghost** [comment]
@geekanamika Is this available to be worked on for first timers?

**Comment by geekanamika** [comment]
@Rimjhim28 can answer better regarding this issue as I am not updated with UI related discussion of project.

**Comment by Rimjhim28** [comment]
@Arbalest007 The issue still exist. If this is the first issue that you are claiming, please go ahead and submit a PR. :)

**Comment by ghost** [comment]
@Rimjhim28  Awesome I'll start work on it.

**Comment by ghost** [comment]
@Rimjhim28 Just an update but I will submitting a pull request later today for the changes. I was able to get both the orientation and images changes as per the original issue's request.

**Comment by CheshtaK** [comment]
Is this issue open for contribution? If yes, may I claim this issue?

**Comment by Rimjhim28** [comment]
Sure @CheshtaK! Please go ahead and send a PR.
I am assigning the issue to you! :)

**Comment by Rimjhim28** [comment]
@CheshtaK I am not able to assign the issue. Nevertheless, I have removed the Available tag

**Comment by ghost** [comment]
@Rimjhim28 Sorry for the delay but I believe I submitted a PR for this issue a while ago haha.

**Comment by Rimjhim28** [comment]
@Arbalest007 My bad! I am really sorry. I overlooked your comment. 
@CheshtaK The issue isn't available anymore. Sorry for the inconvenience.

**Comment by CheshtaK** [comment]
@Rimjhim28 No issues! :)
