### ISSUE TITLE
Remove inconsistency between home and back button

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#996]
## Description

If the home button is pressed in the middle of the scenario, the user is first presented with a warning dialog. The user can either choose to go to map or dismiss the dialog.
If the back button is pressed, the user is directed to map at once without any warning. It would be better option to implement similar dialog for back button as well.

## Mocks

The warning dialog presented if home button clicked:
![screenshot_2018-02-14-02-53-15-635_powerup systers com powerup](https://user-images.githubusercontent.com/26908195/36174972-f8802fb0-1133-11e8-8185-efe13da433f5.png)

### Update 
- [ ] Making modification to onBackPressed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes.

**I would like to work on the issue**

**Comment by raghavpuri31** [comment]
So I set up the project in Android Studio and build an apk but found that apparently no dialogue box appears when home button is pressed in the middle of scenario @Rimjhim28 !

**Comment by Rimjhim28** [comment]
@raghavpuri31 Please be sure that you are on the GSoC17 branch. The latest code updates have been done there. As implemented by one of our GCI participant, the dialog box would only appear if you have answered atleast one time and scored some points, since it would be completely illogical to make a warning of loosing total points until the user has actually scored some points.

![videotogif_2018 02 18_09 51 59](https://user-images.githubusercontent.com/26908195/36348393-b71012de-1494-11e8-8c9c-7f555f12a9e2.gif)

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by m-murad** [comment]
This is a valid issue. Please fix this.

**Comment by Rimjhim28** [comment]
@m-murad Thanks for the approval. Will be sending the PR soon!!
