### ISSUE TITLE
Rectify the implementation of warning dialog in store

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#998]
## Description

With recent changes in the code, a warning dialog is implemented to warn the user prior to buying an item. The item gets already set on avatar before user's decision whether it should be bought or not.
A rectification is needed here such that, clicking on the item first presents the dialog and only if the userconfirms, the item is bought.

## Mocks

![videotogif_2018 02 14_13 03 58](https://user-images.githubusercontent.com/26908195/36192833-593e34d2-1189-11e8-97b3-45ff08013445.gif)

### Update 
- [ ] Rectification of function showConfirmPurchaseDialog()

## Definition of Done

- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

1 hour

**I would like to work on the issue**

**Comment by shivanshsoni** [comment]
I would like to solve this issue

**Comment by shivanshsoni** [comment]
@Rimjhim28 I have solved this issue So, Can I make the pull request.

**Comment by Rimjhim28** [comment]
@shivanshsoni it's mentioned on the issue itself that I am working on it. Please look into some other available issue.

**Comment by m-murad** [comment]
valid issue. please send PR
