### ISSUE TITLE
Appearance of total points dialog when already played scenario is chosen

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#999]
## Description

When a particular scenario is completed, the user is presented with a dialog that shows the points scored in that particular scenario.
The error here is that the implemented dialog also appears if an already played scenario is chosen againg to be played with a message "You gained 0 karma points" 

## Mocks
![screenshot_2018-02-14-03-27-27-485_powerup systers com powerup](https://user-images.githubusercontent.com/26908195/36176249-ff68b96a-1137-11e8-8de4-e94dc4815839.png)

### Update
- [ ] Include code to differentiate if ScenarioOver screen was launched from GameActivity or MapActivity

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours.

**I would like to work on the issue**

**Comment by Rahul5758** [comment]
@Rimjhim28 Can i work on this issue?

**Comment by Rimjhim28** [comment]
@Rahul5758 I have done the work locally. Once the issue is approved I will send the pr. Please pick some other one.

**Comment by Rimjhim28** [comment]
@m-murad please approve the issue.

**Comment by m-murad** [comment]
Please send a PR for this issue.
